//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class UIButton;

@interface ActionSheetButton : UIControl
{
    _Bool _isBlackModel;
    UIButton *_imageButton;
    UIButton *_titleButton;
}

@property(retain) UIButton *titleButton; // @synthesize titleButton=_titleButton;
@property(retain) UIButton *imageButton; // @synthesize imageButton=_imageButton;
@property(nonatomic) _Bool isBlackModel; // @synthesize isBlackModel=_isBlackModel;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setEnabled:(_Bool)arg1;
- (void)_createSubViews;
- (void)layoutSubviews;
- (void)setTitleColor:(id)arg1 forState:(unsigned long long)arg2;
- (void)setTitleText:(id)arg1;
- (id)getTitleText;
- (void)setImage:(id)arg1 hilightedImage:(id)arg2 title:(id)arg3;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_removeObserver;
- (void)_addObserver;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

