//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

#import "NSURLConnectionDataDelegate-Protocol.h"

@class AdStatInfo, NSMutableData, NSString, NSThread, QQMusicURLConnection;

@interface AdStatInfoReportOperation : NSOperation <NSURLConnectionDataDelegate>
{
    _Bool _executing;
    _Bool _finished;
    AdStatInfo *_adStatInfo;
    NSMutableData *_imageData;
    QQMusicURLConnection *_connection;
    NSThread *_thread;
}

@property(retain) NSThread *thread; // @synthesize thread=_thread;
@property(retain, nonatomic) QQMusicURLConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSMutableData *imageData; // @synthesize imageData=_imageData;
@property(retain, nonatomic) AdStatInfo *adStatInfo; // @synthesize adStatInfo=_adStatInfo;
@property(nonatomic, getter=isFinished) _Bool finished; // @synthesize finished=_finished;
@property(nonatomic, getter=isExecuting) _Bool executing; // @synthesize executing=_executing;
- (void).cxx_destruct;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)cancelInternal;
- (void)cancelInternalAndStop;
- (void)cancel;
- (_Bool)isConcurrent;
- (void)reset;
- (void)done;
- (void)start;
- (id)initWithAdStatInfo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

