//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface AlbumColor : NSObject
{
}

+ (id)hBaseColorForImage:(id)arg1 Width:(int)arg2 Height:(int)arg3;
+ (id)backgroundColorByImage:(id)arg1;
+ (id)lyricColorByImage:(id)arg1;

@end

