//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface AlertViewImageItem : NSObject
{
    NSString *_defaultImageName;
    NSString *_imageUrl;
}

@property(retain, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
@property(retain, nonatomic) NSString *defaultImageName; // @synthesize defaultImageName=_defaultImageName;
- (void).cxx_destruct;
- (id)initWithDefultImageName:(id)arg1 withImageUrl:(id)arg2;

@end

