//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "APMidasPayDelegate-Protocol.h"

@class MidasJSBridge, NSString;

@interface APMidasH5Api : NSObject <APMidasPayDelegate>
{
    MidasJSBridge *bridge;
    CDUnknownBlockType callback;
}

+ (_Bool)handleApplication:(id)arg1 openUrl:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
+ (id)instance;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback;
@property(retain, nonatomic) MidasJSBridge *bridge; // @synthesize bridge;
- (void).cxx_destruct;
- (void)onResp:(id)arg1;
- (void)needLogin;
- (id)fitMidasReq:(id)arg1 data:(id)arg2 callBack:(CDUnknownBlockType)arg3 viewController:(id)arg4;
- (void)registerPay:(id)arg1 webViewDelegate:(id)arg2 viewController:(id)arg3;
- (void)enableLog:(_Bool)arg1;
- (void)setEnv:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

