//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APMidasWebViewCtrl.h"

@protocol APMidasCheckBackDelegate;

@interface APMidasMBH5Ctrl : APMidasWebViewCtrl
{
    id <APMidasCheckBackDelegate> checkDele;
}

@property(nonatomic) id <APMidasCheckBackDelegate> checkDele; // @synthesize checkDele;
- (void)callSave;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)viewDidLoad;

@end

