//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QQJSBridgePluginHelper.h"

@interface AppJSBridgePlugin : QQJSBridgePluginHelper
{
}

- (id)generateStandardScheme:(id)arg1;
- (void)handle_app_downloadApp:(id)arg1 callback:(id)arg2;
- (void)handle_app_isInstalled:(id)arg1 callback:(id)arg2;

@end

