//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FolderInfo;

@interface ApplyEditData : NSObject
{
    int indexOfBase;
    int indexOfEdited;
    FolderInfo *folderInfo;
}

@property(retain) FolderInfo *folderInfo; // @synthesize folderInfo;
@property(nonatomic) int indexOfEdited; // @synthesize indexOfEdited;
@property(nonatomic) int indexOfBase; // @synthesize indexOfBase;
- (void).cxx_destruct;

@end

