//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

#import "AppThemeManagerDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSArray, NSString, UICollectionView;

@interface AppThemeMainVC : SkinViewController <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout, AppThemeManagerDelegate>
{
    _Bool _isCancelBtn;
    NSArray *_cellDataList;
    UICollectionView *_collectionView;
}

@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain) NSArray *cellDataList; // @synthesize cellDataList=_cellDataList;
@property(nonatomic) _Bool isCancelBtn; // @synthesize isCancelBtn=_isCancelBtn;
- (void).cxx_destruct;
- (void)reLayout:(long long)arg1;
- (void)appThemeDownloadFailed:(id)arg1 error:(id)arg2;
- (void)appThemeDownloaded:(id)arg1 changeThemeNow:(_Bool)arg2;
- (id)processAppThemeList:(id)arg1;
- (void)receiveAppThemeList:(id)arg1 workResult:(long long)arg2;
- (void)delayLoadAppThemeList;
- (void)loadAppThemeList;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForFooterInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)registerCollectionCell;
- (void)createCollectionView;
- (void)onNotifySkinChanged:(id)arg1;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (_Bool)useBgImage;
- (void)viewDidLoad;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

