//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ListBase, LocalLyricObject, NSArray, SongInfo, UIImage;

@protocol AudioPlayManagerDelegate <NSObject>
- (void)deleteSongFromPlaylist;
- (void)commonRadioLoadSuccess;
- (void)freshHqView;
- (void)updateIsMyFavorite:(SongInfo *)arg1;
- (void)updateStopPlay;
- (void)updateWaitingSongInfo;
- (void)hideWaitNetInfo;
- (void)updateWaitNetInfo;
- (void)updatePlayStateChange:(unsigned long long)arg1 isLocalFile:(_Bool)arg2;
- (void)updatePlayModeChange;
- (void)updateMusicInfo:(SongInfo *)arg1 PlayList:(ListBase *)arg2 autoPlay:(_Bool)arg3;
- (void)updateTime:(double)arg1 duration:(double)arg2 loading:(double)arg3 buffer:(double)arg4 starting:(double)arg5;
- (void)updateLyricData:(LocalLyricObject *)arg1 State:(int)arg2;
- (void)updateAlbumImageView:(UIImage *)arg1;

@optional
- (void)songQueryBackToPlayingVC:(NSArray *)arg1;
- (void)showBannerTipsOrAlertWhenNoWifiAndIsTips:(_Bool)arg1;
@end

