//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface Base64Helper : NSObject
{
}

+ (_Bool)isValidedBase64EncodedData:(id)arg1;
+ (_Bool)isValidedBase64EncodedChar:(unsigned short)arg1;
+ (id)decode_dat_to_dat:(id)arg1;
+ (id)decode_str_to_dat:(id)arg1;
+ (id)decode_dat_to_str:(id)arg1;
+ (id)decode_str_to_str:(id)arg1;
+ (id)encode_dat_to_dat:(id)arg1;
+ (id)encode_str_to_dat:(id)arg1;
+ (id)encode_dat_to_str:(id)arg1;
+ (id)encode_str_to_str:(id)arg1;

@end

