//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SongListBaseViewController.h"

@class CategoricalSongFolderListItem, ChannelItemKey, ListBase, MusicCluster, SmallWebViewController, SongListItem, UIView, UIViewController;
@protocol TabScrollDelegate;

@interface BaseTabVC : SongListBaseViewController
{
    _Bool _isLoadingMore;
    int _h5TabType;
    id <TabScrollDelegate> _delegate;
    unsigned long long _index;
    double _minY;
    UIView *_tabLoadingView;
    UIView *_tabInfoView;
    SmallWebViewController *_H5VC;
    UIViewController *_retainVCFor3DTouchAddFavor;
    CategoricalSongFolderListItem *_categoryData;
    ListBase *_songList;
    MusicCluster *_thisCluster;
    UIView *_searchBarView;
    UIView *_operateView;
    struct CGRect _frame;
}

@property(retain, nonatomic) UIView *operateView; // @synthesize operateView=_operateView;
@property(retain, nonatomic) UIView *searchBarView; // @synthesize searchBarView=_searchBarView;
@property(retain, nonatomic) MusicCluster *thisCluster; // @synthesize thisCluster=_thisCluster;
@property(retain, nonatomic) ListBase *songList; // @synthesize songList=_songList;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(retain, nonatomic) CategoricalSongFolderListItem *categoryData; // @synthesize categoryData=_categoryData;
@property(retain, nonatomic) UIViewController *retainVCFor3DTouchAddFavor; // @synthesize retainVCFor3DTouchAddFavor=_retainVCFor3DTouchAddFavor;
@property(retain) SmallWebViewController *H5VC; // @synthesize H5VC=_H5VC;
@property(retain, nonatomic) UIView *tabInfoView; // @synthesize tabInfoView=_tabInfoView;
@property(retain, nonatomic) UIView *tabLoadingView; // @synthesize tabLoadingView=_tabLoadingView;
@property _Bool isLoadingMore; // @synthesize isLoadingMore=_isLoadingMore;
@property(nonatomic) int h5TabType; // @synthesize h5TabType=_h5TabType;
@property(nonatomic) double minY; // @synthesize minY=_minY;
@property(nonatomic) unsigned long long index; // @synthesize index=_index;
@property(nonatomic) __weak id <TabScrollDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)showTableViewAtIndex:(long long)arg1;
- (void)showNoNetView;
- (void)showNothingView;
- (void)showNetErrView;
- (void)showTableView:(_Bool)arg1;
- (void)onKeyboardHide:(id)arg1;
- (void)unLikeFolder;
- (void)showEmptyView;
- (_Bool)canDeletetableFootView;
- (void)listDataDidUpdate:(id)arg1;
- (void)onSongsEdit:(id)arg1;
- (void)handleBatchAction:(long long)arg1;
- (void)addSongsTableOperHeader;
- (void)showAction:(id)arg1;
- (void)webViewStateDidChange:(unsigned long long)arg1;
- (void)reloadWebPage;
- (void)showWebViewWithRect:(struct CGRect)arg1 extInfo:(id)arg2;
- (id)getH5TabUrl;
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (int)vcType;
- (void)processingLoadMoreAction:(id)arg1;
- (void)onList:(id)arg1 InfoChangeByInfo:(id)arg2 ChangeType:(int)arg3 Index:(unsigned long long)arg4;
- (void)onList:(id)arg1 WithResult:(int)arg2 AndAct:(id)arg3;
- (void)reFresh;
- (void)setViewFrame:(struct CGRect)arg1;
- (id)_buildCommonClearView;
- (float)infoViewTopOffset;
- (float)emptyViewTopOffset;
- (void)updateHeaderTabNum:(long long)arg1 atIndex:(long long)arg2;
- (void)showTableView;
- (void)hideAll;
- (void)hideNetErrView;
- (void)showNoNetViewWithInfo1:(id)arg1 andInfo2:(id)arg2 iconName:(id)arg3 topOffset:(double)arg4 errorCode:(long long)arg5;
- (void)showNoNetViewWithInfo1:(id)arg1 andInfo2:(id)arg2 iconName:(id)arg3 errorCode:(long long)arg4;
- (void)hideLoadingView;
- (void)showLoadingView;
- (void)hideTabInfoView;
- (void)showTabInfoViewWithTitle:(id)arg1 subtitle:(id)arg2 tapSelector:(SEL)arg3;
- (void)hideTabLoadingView;
- (void)showTabLoadingView;
- (void)onNotifyColorStyleChanged:(id)arg1;
- (_Bool)isNeedRefreshWhenLoadView;
- (_Bool)isNeedDefaultHeader;
- (id)buildTableFooterView;
- (double)totalTableCellsHeight;
- (id)buildBaseTableFooterView;
- (void)goToSearch:(id)arg1;
- (id)getSearchBarPlacerHolderString;
- (id)createSearchBarView;
- (_Bool)isNeedSearchBar;
- (id)buildTableHeaderViewWithoutSearchbarAndOperateView;
- (id)buildTableHeaderView;
- (void)randomButtonClicked:(id)arg1;
- (id)_buildOperateViewWithButtonMode:(long long)arg1;
- (_Bool)isMyFolder;
- (long long)playButtonModeThisVC;
- (void)reLayout:(long long)arg1;
- (struct CGRect)songsTableFrame;
- (struct CGRect)reFrame;
- (void)loadView;
- (id)_buildSongListHeaderView;
- (_Bool)isHasHeaderView;
- (void)setContentInset:(struct UIEdgeInsets)arg1;
- (void)setContentMinY:(double)arg1;
- (void)viewDidLoad;
- (void)willResignCurrentTab;
- (void)willActiveCurrentTab;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (_Bool)useBgImage;
- (id)init;

// Remaining properties
@property(retain, nonatomic) ChannelItemKey *channelItemKey; // @dynamic channelItemKey;
@property(retain, nonatomic) SongListItem *songListItem; // @dynamic songListItem;

@end

