//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "BBAssetViewColumnDelegate-Protocol.h"

@class NSIndexPath, NSMutableArray, NSString;
@protocol BBAssetsTableViewCellDelegate;

@interface BBAssetsCell : UITableViewCell <BBAssetViewColumnDelegate>
{
    id <BBAssetsTableViewCellDelegate> delegate;
    NSMutableArray *arrayViews;
    NSIndexPath *_indexPath;
}

@property(copy, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(retain, nonatomic) NSMutableArray *arrayViews; // @synthesize arrayViews;
@property(nonatomic) __weak id <BBAssetsTableViewCellDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)bbassetViewColoumnDidClick:(id)arg1 selected:(_Bool)arg2;
- (void)setCellAssetViewsArray:(id)arg1;
- (void)stopObserving;
- (void)initFontColums;
- (id)initWithReuseFontIdentifier:(id)arg1;
- (void)initColums;
- (id)initWithReuseIdentifier:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

