//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BEActionSheet.h"

#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, QMSwitch, UIButton, UIImageView, UISlider, UISwitch, UITableView, UIView;
@protocol BEActionSheetForLandscapeDelegate;

@interface BEActionSheetStyleSeparateRowScroll : BEActionSheet <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
{
    long long _scrollViewCount;
    NSMutableArray *_scrollViewArray;
    long long _commentButtonIndex;
    _Bool _isMiddleView;
    _Bool _holdAfterBtnClicked;
    _Bool _isShowSongInfoTitle;
    id <BEActionSheetForLandscapeDelegate> _landscapeDelegate;
    UISlider *_volumeSlider;
    UISwitch *_autoUISwith;
    QMSwitch *_autoQMSwith;
    UIButton *_leftSoundButton;
    UIButton *_playModeButton;
    UIView *_autoDownloadViewBg;
    UIView *_songInfoTitleViewBg;
    UIImageView *_tipNewView;
    UITableView *_cluserTableView;
    UIButton *_cancelButton;
    NSString *_mainLeftTitle;
    NSString *_mainRightTitle;
    NSString *_subTitle;
}

@property(retain, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) NSString *mainRightTitle; // @synthesize mainRightTitle=_mainRightTitle;
@property(retain, nonatomic) NSString *mainLeftTitle; // @synthesize mainLeftTitle=_mainLeftTitle;
@property(nonatomic) _Bool isShowSongInfoTitle; // @synthesize isShowSongInfoTitle=_isShowSongInfoTitle;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UITableView *cluserTableView; // @synthesize cluserTableView=_cluserTableView;
@property(retain, nonatomic) UIImageView *tipNewView; // @synthesize tipNewView=_tipNewView;
@property(retain, nonatomic) UIView *songInfoTitleViewBg; // @synthesize songInfoTitleViewBg=_songInfoTitleViewBg;
@property(retain, nonatomic) UIView *autoDownloadViewBg; // @synthesize autoDownloadViewBg=_autoDownloadViewBg;
@property(retain, nonatomic) UIButton *playModeButton; // @synthesize playModeButton=_playModeButton;
@property(retain, nonatomic) UIButton *leftSoundButton; // @synthesize leftSoundButton=_leftSoundButton;
@property(nonatomic) _Bool holdAfterBtnClicked; // @synthesize holdAfterBtnClicked=_holdAfterBtnClicked;
@property(nonatomic) _Bool isMiddleView; // @synthesize isMiddleView=_isMiddleView;
@property(retain, nonatomic) QMSwitch *autoQMSwith; // @synthesize autoQMSwith=_autoQMSwith;
@property(retain, nonatomic) UISwitch *autoUISwith; // @synthesize autoUISwith=_autoUISwith;
@property(retain, nonatomic) UISlider *volumeSlider; // @synthesize volumeSlider=_volumeSlider;
@property(nonatomic) __weak id <BEActionSheetForLandscapeDelegate> landscapeDelegate; // @synthesize landscapeDelegate=_landscapeDelegate;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)onNotifyPlayModeChanged:(id)arg1;
- (void)updatePlayModeChange;
- (void)updatePlayModeBtnState:(int)arg1;
- (void)setCurrentVolumeNotify:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)volumeSliderValueChangeFinish;
- (void)volumeSliderValueChange;
- (void)volumeSliderValueChangeBegin;
- (void)fireButtonClickInPopoverStyle;
- (void)btnClickAtIndex:(long long)arg1;
- (void)buttonClick:(id)arg1;
- (void)onTouchUpInsideCancel:(id)arg1;
- (void)onTouchUpInsidePlayMode:(id)arg1;
- (void)muteVolume:(id)arg1;
- (void)doNothing;
- (void)offlineSwitchChanged:(id)arg1;
- (void)onCommentCountChangedNotification:(id)arg1;
- (void)addCommentCountChangedNotification:(unsigned long long)arg1 withButtonIndex:(long long)arg2;
- (void)addCountLabelToButton:(id)arg1 withCount:(unsigned long long)arg2 withImageName:(id)arg3;
- (id)getButtonWithIndex:(long long)arg1;
- (id)createMaskView:(struct CGRect)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)buildTableViews;
- (void)buildSongInfoTitleInPopover;
- (id)getActionTitleWithSongInfo:(id)arg1 byVC:(id)arg2;
- (void)_setCancelBtnHighlighted:(_Bool)arg1;
- (void)_setScrollViewCount;
- (void)_setImageForSoundBtn:(id)arg1;
- (id)_buildSeparateLine;
- (void)_buildCancelView;
- (void)_buildVolumeView;
- (void)_buildScrollViewsAndButtons;
- (void)_buildSongInfoTitleView;
- (void)_buildAutoDownView;
- (double)viewWidth;
- (_Bool)viewInPopoverStyle;
- (void)dealloc;
- (int)getActionSheetTag;
- (int)getTotalLength;
- (void)addContentView;
- (id)initWithDelegate:(id)arg1 andActionSheetButtons:(id)arg2 withSongInfo:(id)arg3 isShowVolume:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

