//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface BulletBubbleUserManager : NSObject
{
}

+ (_Bool)isUsedByUser:(unsigned long long)arg1;
+ (long long)lastBubbleIdByUser:(unsigned long long)arg1;
+ (_Bool)updateBulletBubbleUserWithUser:(unsigned long long)arg1 andBubble:(long long)arg2;
+ (_Bool)updateBulletBubbleUserWithUser:(unsigned long long)arg1 andUsed:(_Bool)arg2;

@end

