//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "ProtocolHostDelegate-Protocol.h"

@interface BulletCommentDataManager : NSObject <ProtocolHostDelegate>
{
}

+ (id)sharedManager;
- (void)getBulletGiftDisplayInfoWithSongmid:(id)arg1 starttime:(unsigned long long)arg2;
- (void)addBulletGiftByH5WithSongmid:(id)arg1 orSongId:(unsigned long long)arg2 giftId:(long long)arg3 giftNum:(unsigned long long)arg4 andPassback:(id)arg5;
- (void)addBulletGiftWithSongmid:(id)arg1 orSongId:(unsigned long long)arg2 giftId:(long long)arg3 giftNum:(unsigned long long)arg4 andPassback:(id)arg5 offset:(long long)arg6;
- (long long)vipLevelForUser;
- (void)getBulletGiftListWithSongmid:(id)arg1 orSongId:(unsigned long long)arg2;
- (void)getAllBubbleList;
- (void)_postNotification:(id)arg1 withErrorDict:(id)arg2;
- (void)_postNotification:(id)arg1 withErrorMsg:(id)arg2;
- (void)_postNotification:(id)arg1 data:(id)arg2;
- (void)hostCallBackWithWorkProtocol:(id)arg1 protocolError:(id)arg2;
- (void)favorBulletCommentWithSongmid:(id)arg1 commentId:(id)arg2 commentType:(int)arg3;
- (void)addBulletCommentWithSongmid:(id)arg1 content:(id)arg2 bubble:(unsigned long long)arg3 andPassback:(id)arg4 offset:(long long)arg5;
- (void)getBulletCommentTotalCountWithSongmid:(id)arg1;
- (void)getBulletCommentWithSongmid:(id)arg1 starttime:(unsigned long long)arg2 needVipFlag:(_Bool)arg3;

@end

