//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DownLoadTaskDelegate-Protocol.h"
#import "ProtocolHostDelegate-Protocol.h"

@class DownLoadTask, GiftAnimationItem, NSArray, NSMutableArray, NSString;

@interface BulletGiftAnimationPackageManager : NSObject <DownLoadTaskDelegate, ProtocolHostDelegate>
{
    long long lastNetworkStatus;
    NSArray *_giftAnimationList;
    NSMutableArray *_waitingList;
    GiftAnimationItem *_currentDownloadingItem;
    DownLoadTask *_currentDownloadTask;
}

+ (id)sharedInstance;
@property(retain) DownLoadTask *currentDownloadTask; // @synthesize currentDownloadTask=_currentDownloadTask;
@property(retain) GiftAnimationItem *currentDownloadingItem; // @synthesize currentDownloadingItem=_currentDownloadingItem;
@property(retain) NSMutableArray *waitingList; // @synthesize waitingList=_waitingList;
@property(retain, nonatomic) NSArray *giftAnimationList; // @synthesize giftAnimationList=_giftAnimationList;
@property(nonatomic) long long lastNetworkStatus; // @synthesize lastNetworkStatus;
- (void).cxx_destruct;
- (void)downloadNextItem;
- (void)download:(id)arg1 error:(id)arg2;
- (void)download:(id)arg1 didDownloadSuccWithFile:(id)arg2;
- (void)download:(id)arg1 didAppendProgress:(float)arg2;
- (void)download:(id)arg1 didReceiveResponseHeaders:(id)arg2;
- (int)downloadGiftAnimation:(id)arg1;
- (void)readBulletGiftListFile:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)writeBulletGiftAnimation:(id)arg1 toFilePath:(id)arg2;
- (void)deleteOldGiftAnimation:(id)arg1;
- (id)itemPathOfGiftAnimation:(id)arg1;
- (id)zipPathOfGiftAnimation:(id)arg1;
- (id)bundlePathOfGiftAnimation:(id)arg1;
- (id)dirOfGiftAnimation:(id)arg1;
- (id)giftAnimationListPath;
- (id)folderPathOfBulletGiftAnimationWithId:(long long)arg1;
- (void)unzipFile:(id)arg1 toBundlePath:(id)arg2 overWrite:(_Bool)arg3;
- (id)translateJSONListToGiftAnimationList:(id)arg1;
- (void)processGiftAnimationItem:(id)arg1;
- (void)processGiftAnimationList;
- (void)hostCallBackWithWorkProtocol:(id)arg1 protocolError:(id)arg2;
- (void)delayQueryBulletGiftAnimationList;
- (void)queryBulletGiftAnimationList;
- (void)checkNeedUpdateGiftAnimationListByTime:(long long)arg1;
- (_Bool)canDownloadViaCurrentNetwork;
- (void)netChange;
- (void)reachabilityChanged:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

