//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MoreRequestData, NSArray, NSString;

@interface CategoryChannelData : NSObject <NSCopying, NSCoding>
{
    unsigned long long _layoutStyle;
    NSString *_title;
    NSArray *_channels;
    MoreRequestData *_moreRequestData;
    struct CGPoint _scrollOffset;
}

@property(nonatomic) struct CGPoint scrollOffset; // @synthesize scrollOffset=_scrollOffset;
@property(retain, nonatomic) MoreRequestData *moreRequestData; // @synthesize moreRequestData=_moreRequestData;
@property(retain, nonatomic) NSArray *channels; // @synthesize channels=_channels;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) unsigned long long layoutStyle; // @synthesize layoutStyle=_layoutStyle;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)init;

@end

