//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ChannelV4CellData.h"

@class ChannelAdItem, ChannelItem, NSDictionary, NSString, UIColor;

@interface ChannelV4CellDataForHeaderStyle : ChannelV4CellData
{
    _Bool _showTopSeperationLine;
    _Bool _showButton;
    int _nextUpdateInterval;
    UIColor *_styleColor;
    NSString *_title;
    NSString *_subtitle;
    long long _buttonType;
    NSString *_buttonText;
    id _buttonActionTarget;
    SEL _buttonAction;
    SEL _sortButtonAction;
    id _adImgActionTarget;
    SEL _adImgAction;
    NSDictionary *_userInfo;
    ChannelItem *_moreItem;
    ChannelAdItem *_adItem;
}

@property(nonatomic) int nextUpdateInterval; // @synthesize nextUpdateInterval=_nextUpdateInterval;
@property(retain, nonatomic) ChannelAdItem *adItem; // @synthesize adItem=_adItem;
@property(retain, nonatomic) ChannelItem *moreItem; // @synthesize moreItem=_moreItem;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) SEL adImgAction; // @synthesize adImgAction=_adImgAction;
@property(nonatomic) __weak id adImgActionTarget; // @synthesize adImgActionTarget=_adImgActionTarget;
@property(nonatomic) SEL sortButtonAction; // @synthesize sortButtonAction=_sortButtonAction;
@property(nonatomic) SEL buttonAction; // @synthesize buttonAction=_buttonAction;
@property(nonatomic) __weak id buttonActionTarget; // @synthesize buttonActionTarget=_buttonActionTarget;
@property(retain, nonatomic) NSString *buttonText; // @synthesize buttonText=_buttonText;
@property(nonatomic) long long buttonType; // @synthesize buttonType=_buttonType;
@property(nonatomic) _Bool showButton; // @synthesize showButton=_showButton;
@property(nonatomic) _Bool showTopSeperationLine; // @synthesize showTopSeperationLine=_showTopSeperationLine;
@property(retain, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIColor *styleColor; // @synthesize styleColor=_styleColor;
- (void).cxx_destruct;
- (id)init;

@end

