//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

#import "ForceTouchCellDelegate-Protocol.h"
#import "QMChannelInteractiveProtocol-Protocol.h"

@class NSMutableArray, NSString;

@interface ChannelBaseTabVC : SkinViewController <ForceTouchCellDelegate, QMChannelInteractiveProtocol>
{
    NSMutableArray *_tableArray;
    NSMutableArray *_requestArray;
}

@property(retain, nonatomic) NSMutableArray *requestArray; // @synthesize requestArray=_requestArray;
@property(retain, nonatomic) NSMutableArray *tableArray; // @synthesize tableArray=_tableArray;
- (void).cxx_destruct;
- (void)customPopAction:(id)arg1 commitViewController:(id)arg2;
- (id)vcForForceTouchCell:(id)arg1;
- (void)requestToShowMore:(id)arg1;
- (void)playChannel:(id)arg1 fromSong:(id)arg2;
- (void)requestToPlayChannel:(id)arg1;
- (void)addPlayChannelStat:(id)arg1;
- (void)requestToShowChannel:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)outSideScrollerDidScrollToCurrentTab;
- (void)outSideScrollerDidLeaveCurrentTab;
- (void)recoverGestureState;
- (void)willResignCurrentTab;
- (void)willActiveCurrentTab;
- (void)serverChanged;
- (float)infoViewTopOffset;
- (id)navigationController;
- (_Bool)isNeedAddBottomLine;
- (id)strVCtype;
- (void)loadView;
- (_Bool)useBgImage;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

