//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ChannelV4Cell.h"

@class BEKeyButton, ProfileHeadIcon, UIImageView, UILabel, UIView;

@interface ChannelV4DarenCell : ChannelV4Cell
{
    ProfileHeadIcon *_headIcon;
    BEKeyButton *_followBtn;
    UILabel *_mainTitleLabel;
    UILabel *_subTitleLabel;
    UIImageView *_arrowImageView;
    UIView *_topLine;
    UIView *_bottomLine;
}

+ (double)cellHeightWithRowData:(id)arg1;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UIView *topLine; // @synthesize topLine=_topLine;
@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *mainTitleLabel; // @synthesize mainTitleLabel=_mainTitleLabel;
@property(retain, nonatomic) BEKeyButton *followBtn; // @synthesize followBtn=_followBtn;
@property(retain, nonatomic) ProfileHeadIcon *headIcon; // @synthesize headIcon=_headIcon;
- (void).cxx_destruct;
- (void)onNotifySkinSettingChange:(id)arg1;
- (void)syncFollowStatus:(id)arg1;
- (void)changeCellStyle:(int)arg1;
- (void)updateFollowBtn:(_Bool)arg1;
- (void)updateUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

