//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ChannelV4CellData.h"

@class ChannelItem;

@interface ChannelV4CellDataForOthers : ChannelV4CellData
{
    ChannelItem *_channel;
}

@property(retain, nonatomic) ChannelItem *channel; // @synthesize channel=_channel;
- (void).cxx_destruct;

@end

