//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseScrollerVC.h"

#import "CPDAdViewDelegate-Protocol.h"
#import "ImageManagerDelegate-Protocol.h"
#import "QMTabBarDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class CPDAdItem, CPDAdView, ChannelBaseTabVC, ChannelMVTabVC, NSString, RadioTabVC_V2, RankingTabVC, RecommendTabVC, SquareTabVC, UIScrollView, UIView;

@interface ChannelRootViewController_V4 : BaseScrollerVC <ImageManagerDelegate, CPDAdViewDelegate, UIGestureRecognizerDelegate, QMTabBarDelegate>
{
    _Bool _UIReadyState;
    int _currentIndex;
    UIView *leftCoverView;
    UIView *rightCoverView;
    RecommendTabVC *recommendTabVC;
    RankingTabVC *rankingTabVC;
    SquareTabVC *squareTabVC;
    RadioTabVC_V2 *radioTabVC_V2;
    ChannelMVTabVC *channelMVTabVC;
    _Bool _didLoadCPDAd;
    _Bool _canLoadCPDAd;
    _Bool _notFireWillActive;
    ChannelBaseTabVC *_visibleTabVC;
    UIScrollView *_tabScrollView;
    CPDAdItem *_currentADItem;
    CPDAdView *_currentADView;
}

@property(nonatomic) _Bool notFireWillActive; // @synthesize notFireWillActive=_notFireWillActive;
@property(nonatomic) _Bool canLoadCPDAd; // @synthesize canLoadCPDAd=_canLoadCPDAd;
@property(nonatomic) _Bool didLoadCPDAd; // @synthesize didLoadCPDAd=_didLoadCPDAd;
@property(retain, nonatomic) CPDAdView *currentADView; // @synthesize currentADView=_currentADView;
@property(retain, nonatomic) CPDAdItem *currentADItem; // @synthesize currentADItem=_currentADItem;
@property(retain, nonatomic) UIScrollView *tabScrollView; // @synthesize tabScrollView=_tabScrollView;
@property(retain, nonatomic) ChannelBaseTabVC *visibleTabVC; // @synthesize visibleTabVC=_visibleTabVC;
- (void).cxx_destruct;
- (id)getCurrentVisibleTabVC;
- (int)isContainIntabVC:(Class)arg1;
- (void)handlePanGesture:(id)arg1;
- (void)cpdAdViewClicked:(id)arg1 adItem:(id)arg2;
- (struct CGSize)cpdadViewSize;
- (void)showIconAd:(id)arg1 item:(id)arg2;
- (void)onImagetWithInfo:(id)arg1 Image:(id)arg2;
- (void)loadCPDAdItem;
- (void)cpdIconAdPrepared:(id)arg1;
- (void)setAdHiddenForIndex:(int)arg1;
- (void)didLeaveScrollerVC;
- (void)didEntranceScrollerVC;
- (void)goMusicHallTab:(unsigned long long)arg1;
- (void)goOldMusicHallTab:(unsigned long long)arg1 categoryId:(long long)arg2;
- (void)switchToTabVC:(int)arg1;
- (void)switchToSongListTab;
- (void)switchToRecommandTab;
- (void)onColorStyleChanged;
- (void)indicatorVisibleTabVC;
- (void)loadTabViewAtIndex:(int)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)selectedItem:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)touchDown:(id)arg1 itemAtIndex:(unsigned long long)arg2;
- (long long)maxPreloadTabs;
- (void)touchUpInside:(id)arg1 itemAtIndex:(unsigned long long)arg2;
- (id)selectedImageView:(id)arg1;
- (id)selectetdItemImage:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)backgroundImage:(id)arg1;
- (id)accessibilityLabel:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)imageFor:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)setupHeadTabBar;
- (void)onNotifyUserLanguageChanged:(id)arg1;
- (void)appDidEnterForeground:(id)arg1;
- (void)willSwitchToChannelTab;
- (id)strVCtype;
- (int)vcType;
- (void)touchOnTop;
- (void)popGestureRecognize;
- (void)viewDidPop;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (_Bool)isNeedAddBottomLine;
- (void)loadView;
- (_Bool)useBgImage;
- (void)dealloc;
- (id)init;
- (void)initTabComponents;
- (id)tabComponents;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

