//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class ChannelItemKey, NSDictionary, NSString, SongListItem;

@interface ChannelInfoProtocol : ProtocolBaseJason
{
    _Bool _loadMoreData;
    int _totalNum;
    int _assetsType;
    NSString *_dataUrl;
    SongListItem *_songListItem;
    NSDictionary *_rawJsonData;
    ChannelItemKey *_channelItemKey;
    NSString *namedFlag;
    long long _requestType;
}

@property(nonatomic) long long requestType; // @synthesize requestType=_requestType;
@property(nonatomic) int assetsType; // @synthesize assetsType=_assetsType;
@property(retain, nonatomic) NSString *namedFlag; // @synthesize namedFlag;
@property(nonatomic) int totalNum; // @synthesize totalNum=_totalNum;
@property(retain, nonatomic) ChannelItemKey *channelItemKey; // @synthesize channelItemKey=_channelItemKey;
@property(nonatomic) _Bool loadMoreData; // @synthesize loadMoreData=_loadMoreData;
@property(retain, nonatomic) NSDictionary *rawJsonData; // @synthesize rawJsonData=_rawJsonData;
@property(retain, nonatomic) SongListItem *songListItem; // @synthesize songListItem=_songListItem;
@property(retain, nonatomic) NSString *dataUrl; // @synthesize dataUrl=_dataUrl;
- (void).cxx_destruct;
- (_Bool)hasNextPage;
- (void)onParseJasonData:(id)arg1;
- (id)getUrl;
- (id)initWithChannelItemKey:(id)arg1;
- (_Bool)canReportError;
- (void)getCidAndCgiName;

@end

