//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSMutableArray;

@interface ChannelData : NSObject <NSCopying, NSCoding>
{
    long long _timeTag;
    unsigned long long _uin;
    NSMutableArray *_categoryChannelArray;
}

@property(retain, nonatomic) NSMutableArray *categoryChannelArray; // @synthesize categoryChannelArray=_categoryChannelArray;
@property(nonatomic) unsigned long long uin; // @synthesize uin=_uin;
@property(nonatomic) long long timeTag; // @synthesize timeTag=_timeTag;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)init;

@end

