//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "ProtocolHostDelegate-Protocol.h"

@class NSString, QMAlertView, UIAlertController, UIAlertView;

@interface ChinaUnicomFreeFlowManager : NSObject <ProtocolHostDelegate>
{
    _Bool isShowAlertWhenFreeFlowFirstShow;
    UIAlertController *_alertController;
    QMAlertView *_qmAlertView;
    UIAlertView *_alertView;
    NSString *_alertViewTitle;
    NSString *_alertViewMessage;
    _Bool _isShowingNotChinaUnicomAlert;
}

+ (id)sharedManager;
@property(nonatomic) _Bool isShowingNotChinaUnicomAlert; // @synthesize isShowingNotChinaUnicomAlert=_isShowingNotChinaUnicomAlert;
- (void).cxx_destruct;
- (void)showPopupWindowWithType:(id)arg1;
- (void)willBeRobbedWithType:(unsigned long long)arg1;
- (void)showForceUseChinaFreeAlertView;
- (void)reallyShowFreeFlowPopupWindowTypeNotChinaUincomAlert;
- (void)showNotChinaUnicomAlertView;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)reallyShowFreeFreeFlowPopupWindowTypeActiveAlert;
- (void)onNotificationShowFlowPackChanged:(id)arg1;
- (void)delayShowAlert;
- (void)onNotificationCheckFreeFlowFinish:(id)arg1;
- (void)terminateAction;
- (void)backGroudCheck;
- (void)showChinaUnicomWebView:(id)arg1;
- (void)procressFlowCountReport;
- (void)requestFreeFlowProtocol;
- (void)checkShowAlertView;
- (void)reallyShowFreeFlowPopupWindowTypeOpenWhileFlowCountAlert;
- (void)showFlowTipsAlert:(id)arg1 message:(id)arg2;
- (void)reallyShowFreeFlowPopupWindowTypeOpenWhileLauchAlert;
- (void)againCheckShowChinaUnicomAlert;
- (void)printLog:(id)arg1;
- (void)startGetHostIp;
- (long long)compareCurrentTime:(id)arg1;
- (void)hostCallBackWithWorkProtocol:(id)arg1 protocolError:(id)arg2;
- (_Bool)isFreeFlowUser;
- (void)reportFreeFlowCostToServer;
- (void)initAction;
- (void)dealloc;
- (id)init;

@end

