//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

#import "ImageManagerDelegate-Protocol.h"
#import "ProtocolHostDelegate-Protocol.h"
#import "QMTableViewProtocol-Protocol.h"

@class ChannelItem, CollectorRecvData, NSString;

@interface CollectorViewController : SkinViewController <ImageManagerDelegate, QMTableViewProtocol, ProtocolHostDelegate>
{
    _Bool _loadingMore;
    ChannelItem *_item;
    CollectorRecvData *_recvData;
}

@property(nonatomic) _Bool loadingMore; // @synthesize loadingMore=_loadingMore;
@property(retain, nonatomic) CollectorRecvData *recvData; // @synthesize recvData=_recvData;
@property(retain, nonatomic) ChannelItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)hostCallBackWithWorkProtocol:(id)arg1 protocolError:(id)arg2;
- (void)appendRecvData:(id)arg1;
- (void)onImagetWithInfo:(id)arg1 Image:(id)arg2;
- (void)viewDidPop;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (_Bool)moreDataIsLoading:(id)arg1;
- (void)processingLoadMoreAction:(id)arg1;
- (_Bool)hasMoreDataInTableView:(id)arg1;
- (void)showTable:(long long)arg1;
- (_Bool)hasMore;
- (id)collectors;
- (void)requestMoreCollectors;
- (void)requestCollector:(int)arg1;
- (void)reFresh;
- (void)crateTableView;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithChannelItem:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

