//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIToolbar.h>

@class CALayer;

@interface CRNavigationBar : UIToolbar
{
    CALayer *_colorLayer;
}

@property(retain, nonatomic) CALayer *colorLayer; // @synthesize colorLayer=_colorLayer;
- (void).cxx_destruct;
- (void)displayColorLayer:(_Bool)arg1;
- (void)layoutSubviews;
- (double)convertValue:(double)arg1 withOpacity:(double)arg2;
- (double)minOpacityForValue:(double)arg1;
- (void)setBarTintColor:(id)arg1;

@end

