//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSString;

@interface DailyFreeFlowItem : NSObject <NSCoding, NSCopying>
{
    _Bool bReportSuccess;
    NSString *strDate;
    long long flowCount;
}

@property(nonatomic) _Bool bReportSuccess; // @synthesize bReportSuccess;
@property(nonatomic) long long flowCount; // @synthesize flowCount;
@property(retain, nonatomic) NSString *strDate; // @synthesize strDate;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

