//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface DCCNetworkMonitor : NSObject
{
    struct __SCNetworkReachability *reachRef;
    _Bool isWifiRef;
}

+ (id)reachabilityForLocalWifi;
+ (id)reachabilityForInternetConnection;
+ (id)reachabilityWithAddress:(const struct sockaddr_in *)arg1;
+ (id)reachabilityWithHostName:(id)arg1;
- (void)dealloc;
- (long long)currentStatus;
- (long long)wifiStatusForFlags:(unsigned int)arg1;
- (long long)networkStatusForFlags:(unsigned int)arg1;
- (void)stopNotifier;
- (_Bool)startNotifier;

@end

