//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol DCCSDKConfigurationSource <NSObject>
@property(readonly, nonatomic) _Bool localAccessoryCatalogEnabled;
@property(readonly, nonatomic) _Bool guestUserPersistsLocally;
@property(readonly, nonatomic) _Bool registeredUserAPIEnabled;
@property(readonly, nonatomic) _Bool listeningTestAPIEnabled;
@property(readonly, nonatomic) _Bool webServiceAllowRuntimeSelection;
@property(readonly, nonatomic) _Bool webServicesEnabled;
@property(readonly, nonatomic) NSString *dccSetup_InitValue;
@property(readonly, nonatomic) NSString *dccSetup_DCCSecret;
@property(readonly, nonatomic) NSString *dccSetup_Device;
@property(readonly, nonatomic) NSString *dccSetup_Manufacturer;
@property(readonly, nonatomic) NSString *configurationName;
@property(readonly, nonatomic) NSString *configurationID;
@end

