//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QQJSBridgePluginHelper.h"

@interface DebugJSBridgePlugin : QQJSBridgePluginHelper
{
}

- (void)handle_debug_H5Log:(id)arg1 callback:(id)arg2;
- (void)handle_debug_searchFeedback:(id)arg1 callback:(id)arg2;
- (void)handle_debug_sendNativeLog:(id)arg1 callback:(id)arg2;
- (void)handle_debug_sendFeedback:(id)arg1 callback:(id)arg2;

@end

