//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSSet, UIImage;
@protocol DecoderDelegate;

@interface Decoder : NSObject
{
    NSSet *readers;
    UIImage *image;
    struct CGRect cropRect;
    UIImage *subsetImage;
    char *subsetData;
    int subsetWidth;
    int subsetHeight;
    int subsetBytesPerRow;
    id <DecoderDelegate> delegate;
}

@property(retain, nonatomic) NSSet *readers; // @synthesize readers;
@property(nonatomic) id <DecoderDelegate> delegate; // @synthesize delegate;
@property int subsetBytesPerRow; // @synthesize subsetBytesPerRow;
@property int subsetHeight; // @synthesize subsetHeight;
@property int subsetWidth; // @synthesize subsetWidth;
@property(nonatomic) char *subsetData; // @synthesize subsetData;
@property(retain, nonatomic) UIImage *subsetImage; // @synthesize subsetImage;
@property(nonatomic) struct CGRect cropRect; // @synthesize cropRect;
@property(retain, nonatomic) UIImage *image; // @synthesize image;
- (void)dealloc;
- (_Bool)decodeImage:(id)arg1 cropRect:(struct CGRect)arg2;
- (_Bool)decodeImage:(id)arg1;
- (_Bool)decode;
- (void)prepareSubset;
- (void)resultPointCallback:(struct CGPoint)arg1;
- (void)failedToDecodeImage:(id)arg1;
- (void)didDecodeImage:(id)arg1;
- (void)willDecodeImage;

@end

