//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DownloadHistoryVC, NSArray, NSString;

@protocol DownloadHistoryVCDelegate <NSObject>
- (void)onBatchAddSongsToDownloading:(NSArray *)arg1 stat:(NSString *)arg2;

@optional
- (void)downloadHistoryVCClickHeaderCancel:(DownloadHistoryVC *)arg1;
@end

