//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

#import "DownLoadEditProtocol-Protocol.h"
#import "DownloadHistoryVCDelegate-Protocol.h"

@class DownloadCell, NSIndexPath, NSString, NSTimer, SongListOperateView, UIButton;
@protocol DownLoadingViewController, DownloadHeaderViewDataSource;

@interface DownLoadingViewController : SkinViewController <DownLoadEditProtocol, DownloadHistoryVCDelegate>
{
    int downloadingTag;
    _Bool _startAll;
    NSIndexPath *tableCellSelectIndexPath;
    NSTimer *_updateDownloadSpeedTimer;
    DownloadCell *_currentDownloadingCell;
    id <DownLoadingViewController> _delegate;
    id <DownloadHeaderViewDataSource> _headerDataSource;
    UIButton *_startOrParseAllButton;
    SongListOperateView *_songListOperateView;
}

@property(retain) SongListOperateView *songListOperateView; // @synthesize songListOperateView=_songListOperateView;
@property(retain) UIButton *startOrParseAllButton; // @synthesize startOrParseAllButton=_startOrParseAllButton;
@property _Bool startAll; // @synthesize startAll=_startAll;
@property(nonatomic) __weak id <DownloadHeaderViewDataSource> headerDataSource; // @synthesize headerDataSource=_headerDataSource;
@property __weak id <DownLoadingViewController> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) DownloadCell *currentDownloadingCell; // @synthesize currentDownloadingCell=_currentDownloadingCell;
@property(retain, nonatomic) NSTimer *updateDownloadSpeedTimer; // @synthesize updateDownloadSpeedTimer=_updateDownloadSpeedTimer;
@property(nonatomic) __weak NSIndexPath *tableCellSelectIndexPath; // @synthesize tableCellSelectIndexPath;
@property(nonatomic) int downloadingTag; // @synthesize downloadingTag;
- (void).cxx_destruct;
- (void)onNotifyShowDownloadSongFailedReason:(id)arg1;
- (void)onBatchAddSongsToDownloading:(id)arg1 stat:(id)arg2;
- (_Bool)allSongsDownloadOkInDownloadHistoryInfos:(id)arg1;
- (id)_removeSameAndDownloadedSongs:(id)arg1;
- (_Bool)deleteSongsDisk:(id)arg1;
- (void)onEditDone:(id)arg1 deletedObjects:(id)arg2 withDeleteBlock:(CDUnknownBlockType)arg3;
- (void)onSongsEdit:(id)arg1;
- (void)handleCellLongPress:(id)arg1;
- (void)onTouchUpInsideViewDownloadHistory:(id)arg1;
- (void)_updateStartOrPauseAllButton;
- (_Bool)_startOrParseAllButtonStatus;
- (void)_beginEdit:(id)arg1;
- (void)_startOrPauseAll:(id)arg1;
- (void)handleBatchAction:(long long)arg1;
- (void)changeTableViewHeaderMode:(long long)arg1;
- (void)removeTableViewHeaderView;
- (_Bool)containPayContent;
- (id)createOperateView;
- (void)addTableViewHeaderView;
- (void)showExclusiveBannerTipsIfNeeded:(id)arg1;
- (void)onList:(id)arg1 InfoChangeByInfo:(id)arg2 ChangeType:(int)arg3 Index:(unsigned long long)arg4;
- (void)onList:(id)arg1 WithResult:(int)arg2 AndAct:(id)arg3;
- (void)onList:(id)arg1 ChangeByType:(int)arg2 Index:(int)arg3 Info:(id)arg4;
- (void)dealWithLocalDownloading:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (_Bool)disable3DTouch;
- (void)delObject:(id)arg1;
- (void)batchDeleteDownloadInfo:(id)arg1;
- (id)emptyViewCustomButton;
- (id)emptyViewBgText2;
- (void)addRemainPayCountMsgToEmptyView;
- (void)reFresh;
- (id)getSongInfoAtIndexPath:(id)arg1;
- (void)updateDownloadingSpeed:(id)arg1;
- (void)startSpeedTimer:(id)arg1;
- (id)getAllVCType;
- (int)vcType;
- (void)reLayout:(long long)arg1;
- (struct CGRect)reFrame;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

