//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class EGORefreshTableHeaderView, NSDate;

@protocol EGORefreshTableHeaderDelegate
- (_Bool)egoRefreshTableHeaderDataSourceIsLoading:(EGORefreshTableHeaderView *)arg1;
- (void)egoRefreshTableHeaderDidTriggerRefresh:(EGORefreshTableHeaderView *)arg1;

@optional
- (struct UIEdgeInsets)getScrollViewOriginOffset;
- (void)egoRefreshTableHeaderDidTriggerEnforceRefresh:(EGORefreshTableHeaderView *)arg1;
- (NSDate *)egoRefreshTableHeaderDataSourceLastUpdated:(EGORefreshTableHeaderView *)arg1;
@end

