//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ChannelCreator.h"

@interface FeedZanInfo : ChannelCreator
{
    int _operateState;
}

+ (id)translateFromCircleJsonData:(id)arg1;
@property(nonatomic) int operateState; // @synthesize operateState=_operateState;

@end

