//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

#import "ProtocolHostDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class BEPlaceHolderTextView, NSMutableArray, NSString, UIImageView, UILabel, UIView;

@interface FeedBackDetailVC : SkinViewController <ProtocolHostDelegate, UITableViewDelegate, UIScrollViewDelegate, UITextViewDelegate>
{
    NSString *_feed;
    BEPlaceHolderTextView *_sharedText;
    UILabel *_leftCount;
    UIView *_floatView;
    NSString *_subTitle;
    NSMutableArray *_feedData;
    long long _lastSelect;
    UIImageView *_noSelectedImage;
    UIImageView *_didSelectedImage;
}

@property(retain, nonatomic) UIImageView *didSelectedImage; // @synthesize didSelectedImage=_didSelectedImage;
@property(retain, nonatomic) UIImageView *noSelectedImage; // @synthesize noSelectedImage=_noSelectedImage;
@property(nonatomic) long long lastSelect; // @synthesize lastSelect=_lastSelect;
@property(retain, nonatomic) NSMutableArray *feedData; // @synthesize feedData=_feedData;
@property(retain, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) UIView *floatView; // @synthesize floatView=_floatView;
@property(retain, nonatomic) UILabel *leftCount; // @synthesize leftCount=_leftCount;
@property(retain, nonatomic) BEPlaceHolderTextView *sharedText; // @synthesize sharedText=_sharedText;
@property(retain, nonatomic) NSString *feed; // @synthesize feed=_feed;
- (void).cxx_destruct;
- (id)createTableFootView;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)dismissKeyboard;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showActionResult:(int)arg1;
- (void)shareMessage:(id)arg1;
- (void)loginOKFunc;
- (void)feedBackClick:(id)arg1;
- (void)setSeperateLineLeftMargin:(id)arg1;
- (id)createMoreRootCell:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (int)vcType;
- (void)didReceiveMemoryWarning;
- (void)readJsonFile;
- (void)setDefaultFeedback:(long long)arg1;
- (void)touchOnTop;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

