//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSArray;

@interface FetchUserGeneProtocol : ProtocolBaseJason
{
    unsigned long long _userUin;
    NSArray *_geneList;
}

@property(readonly, nonatomic) NSArray *geneList; // @synthesize geneList=_geneList;
@property(nonatomic) unsigned long long userUin; // @synthesize userUin=_userUin;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getUrl;
- (int)cid;
- (id)init;

@end

