//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ListBase, NSArray, NSString, TodayKey;

@interface FetchTodaykeyResult : NSObject
{
    _Bool _continueWorking;
    ListBase *_listBase;
    NSString *_err;
    TodayKey *_todaykey;
    CDUnknownBlockType _finishBlock;
    long long _backupSongListId;
    NSArray *_recentListenTids;
}

@property(retain) NSArray *recentListenTids; // @synthesize recentListenTids=_recentListenTids;
@property long long backupSongListId; // @synthesize backupSongListId=_backupSongListId;
@property _Bool continueWorking; // @synthesize continueWorking=_continueWorking;
@property(copy) CDUnknownBlockType finishBlock; // @synthesize finishBlock=_finishBlock;
@property(retain) TodayKey *todaykey; // @synthesize todaykey=_todaykey;
@property(copy) NSString *err; // @synthesize err=_err;
@property(retain) ListBase *listBase; // @synthesize listBase=_listBase;
- (void).cxx_destruct;

@end

