//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FingerPrintSessionProtocol-Protocol.h"

@class NSMutableSet, NSString;
@protocol FingerPrintManagerDelegate;

@interface FingerPrintManager : NSObject <FingerPrintSessionProtocol>
{
    NSMutableSet *_setFingerPrintSession;
    id <FingerPrintManagerDelegate> _fingerPrintManagerdelegate;
}

+ (id)sharedFingerPrintManager;
@property(nonatomic) __weak id <FingerPrintManagerDelegate> fingerPrintManagerdelegate; // @synthesize fingerPrintManagerdelegate=_fingerPrintManagerdelegate;
@property(retain, nonatomic) NSMutableSet *setFingerPrintSession; // @synthesize setFingerPrintSession=_setFingerPrintSession;
- (void).cxx_destruct;
- (void)onFingerPrintStatusChange:(id)arg1 fingerPrintStatus:(int)arg2;
- (void)getFingerPrintForSong:(id)arg1 manualCause:(_Bool)arg2;
- (_Bool)isFindingFingerPrintOfSong:(id)arg1;
- (id)getUrlForFingerPrint:(id)arg1 uuid:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

