//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, SongInfoKey;

@interface FirstPieceCacheSong : NSObject
{
    SongInfoKey *_songInfoKey;
    NSString *_mediaMid;
    double _duration;
}

@property double duration; // @synthesize duration=_duration;
@property(retain) NSString *mediaMid; // @synthesize mediaMid=_mediaMid;
@property(retain) SongInfoKey *songInfoKey; // @synthesize songInfoKey=_songInfoKey;
- (void).cxx_destruct;

@end

