//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ChannelItem, FlashWindow;

@protocol FlashWindowDelegate <NSObject>
- (void)onFlashWindowClicked:(FlashWindow *)arg1 channelItem:(ChannelItem *)arg2;
- (void)onFlashWindowWillRelease:(FlashWindow *)arg1;
@end

