//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMCAppLinkProtocolHeader.h"

@interface FMCAppLinkV1ProtocolHeader : FMCAppLinkProtocolHeader
{
}

- (id)description;
- (void)parse:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)data;
- (id)init;

@end

