//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;
@protocol FMCProtocolListener;

@interface FMCApplinkProtocolRecievedMessageRouter : NSObject
{
    _Bool _alreadyDestructed;
    id <FMCProtocolListener> _delegate;
    NSMutableDictionary *_messageAssemblers;
}

@property(retain) NSMutableDictionary *messageAssemblers; // @synthesize messageAssemblers=_messageAssemblers;
@property _Bool alreadyDestructed; // @synthesize alreadyDestructed=_alreadyDestructed;
@property __weak id <FMCProtocolListener> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)dispose;
- (void)destructObjects;
- (void)dispatchMultiPartMessage:(id)arg1;
- (void)dispatchControlMessage:(id)arg1;
- (void)dispatchProtocolMessage:(id)arg1;
- (void)handleRecievedMessage:(id)arg1;
- (id)init;

@end

