//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;
@protocol FMCTransportDelegate;

@interface FMCAbstractTransport : NSObject
{
    id <FMCTransportDelegate> _delegate;
    NSString *_debugConsoleGroupName;
}

@property(retain) NSString *debugConsoleGroupName; // @synthesize debugConsoleGroupName=_debugConsoleGroupName;
@property __weak id <FMCTransportDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (double)retryDelay;
- (void)dispose;
- (void)sendData:(id)arg1;
- (void)disconnect;
- (void)connect;
- (id)init;

@end

