//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMCEnum.h"

@interface FMCCompassDirection : FMCEnum
{
}

+ (id)NORTHEAST;
+ (id)EAST;
+ (id)SOUTHEAST;
+ (id)SOUTH;
+ (id)SOUTHWEST;
+ (id)WEST;
+ (id)NORTHWEST;
+ (id)NORTH;
+ (id)values;
+ (id)valueOf:(id)arg1;

@end

