//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMCRPCStruct.h"

@class NSNumber, NSString;

@interface FMCDeviceInfo : FMCRPCStruct
{
}

@property(retain) NSNumber *maxNumberRFCOMMPorts;
@property(retain) NSString *carrier;
@property(retain) NSString *osVersion;
@property(retain) NSString *os;
@property(retain) NSString *firmwareRev;
@property(retain) NSString *hardware;
- (id)initWithDictionary:(id)arg1;
- (id)init;

@end

