//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMCRPCNotification.h"

@class FMCFileType, FMCRequestType, NSNumber, NSString;

@interface FMCOnSystemRequest : FMCRPCNotification
{
}

@property(retain) NSNumber *length;
@property(retain) NSNumber *offset;
@property(retain) FMCFileType *fileType;
@property(retain) NSNumber *timeout;
@property(retain) NSString *url;
@property(retain) FMCRequestType *requestType;
- (id)initWithDictionary:(id)arg1;
- (id)init;

@end

