//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMCRPCRequest.h"

@class NSMutableArray, NSNumber, NSString;

@interface FMCSlider : FMCRPCRequest
{
}

@property(retain) NSNumber *timeout;
@property(retain) NSMutableArray *sliderFooter;
@property(retain) NSString *sliderHeader;
@property(retain) NSNumber *position;
@property(retain) NSNumber *numTicks;
- (id)initWithDictionary:(id)arg1;
- (id)init;

@end

