//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, NSURLSession;

@interface FMCURLSession : NSObject
{
    NSURLSession *systemRequestSession;
    NSURLSession *encodedSyncPDataSession;
    id _delegate;
    NSString *_debugConsoleGroupName;
}

@property(retain) NSString *debugConsoleGroupName; // @synthesize debugConsoleGroupName=_debugConsoleGroupName;
- (void).cxx_destruct;
- (void)cancelAndInvalidate;
- (void)uploadTaskWithSystemProprietaryDictionary:(id)arg1 withURLString:(id)arg2;
- (void)uploadTaskWithPData:(id)arg1 withRequest:(id)arg2 withTimeout:(id)arg3;
- (id)initWithDelegate:(id)arg1 withDebugConsoleGroup:(id)arg2;

@end

