//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate, NSString;

@interface FolderIcoUploadHistory : NSObject
{
    NSDate *_uploadTime;
    NSString *_uploadSuccessUrl;
}

@property(retain) NSString *uploadSuccessUrl; // @synthesize uploadSuccessUrl=_uploadSuccessUrl;
@property(retain) NSDate *uploadTime; // @synthesize uploadTime=_uploadTime;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

