//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

#import "FollowTableViewImageManagerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class FollowMoreDataManager, NSString, QMSearchBar, QMTableView, UITableView, UIView;

@interface FollowMoreViewController : SkinViewController <UITableViewDataSource, UITableViewDelegate, FollowTableViewImageManagerDelegate>
{
    UITableView *currentTableView;
    long long currentGroupid;
    _Bool isShowingQQFriendsTable;
    _Bool isShowingSearchTable;
    _Bool afterLoad;
    _Bool needRefresh;
    _Bool singersLoadingMore;
    _Bool daRensLoadingMore;
    unsigned long long currentSingersPage;
    unsigned long long currentDaRensPage;
    long long _currentTab;
    UIView *_headerTabBar;
    QMTableView *_singerTable;
    QMTableView *_daRenTable;
    QMTableView *_wxFriendsTable;
    QMTableView *_normalUserTable;
    UITableView *_QQFriendsGroupTable;
    UITableView *_QQFriendsTable;
    UITableView *_searchTable;
    FollowMoreDataManager *_dataManager;
    QMSearchBar *_searchBar;
}

@property(retain, nonatomic) QMSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) FollowMoreDataManager *dataManager; // @synthesize dataManager=_dataManager;
@property(retain, nonatomic) UITableView *searchTable; // @synthesize searchTable=_searchTable;
@property(retain, nonatomic) UITableView *QQFriendsTable; // @synthesize QQFriendsTable=_QQFriendsTable;
@property(retain, nonatomic) UITableView *QQFriendsGroupTable; // @synthesize QQFriendsGroupTable=_QQFriendsGroupTable;
@property(retain, nonatomic) QMTableView *normalUserTable; // @synthesize normalUserTable=_normalUserTable;
@property(retain, nonatomic) QMTableView *wxFriendsTable; // @synthesize wxFriendsTable=_wxFriendsTable;
@property(retain, nonatomic) QMTableView *daRenTable; // @synthesize daRenTable=_daRenTable;
@property(retain, nonatomic) QMTableView *singerTable; // @synthesize singerTable=_singerTable;
@property(retain, nonatomic) UIView *headerTabBar; // @synthesize headerTabBar=_headerTabBar;
@property(nonatomic) long long currentTab; // @synthesize currentTab=_currentTab;
- (void).cxx_destruct;
- (void)onNotifyFollowMoreDataWXFriendsDataChanged:(id)arg1;
- (void)onNotifyFollowMoreDataUserDataChanged:(id)arg1;
- (void)onNotifyFollowMoreDataSingerDataChanged:(id)arg1;
- (void)onNotifyFollowMoreDataDarrenDataChanged:(id)arg1;
- (void)onNotifyFollowMoreDataQQFriendsGroupDataChanged:(id)arg1;
- (_Bool)moreDataIsLoading:(id)arg1;
- (void)processingLoadMoreAction:(id)arg1;
- (_Bool)hasMoreDataInTableView:(id)arg1;
- (_Bool)searchRemarkName:(id)arg1 inQQFriendItem:(id)arg2;
- (_Bool)searchUserName:(id)arg1 inQQFriendItem:(id)arg2;
- (_Bool)searchUin:(id)arg1 inQQFriendItem:(id)arg2;
- (void)beginSearchWithSearchKey:(id)arg1;
- (void)searchTextChanged:(id)arg1;
- (void)onImagetWithInfo:(id)arg1 TableView:(id)arg2 Image:(id)arg3;
- (void)headerFinish:(id)arg1;
- (void)viewDidPop;
- (void)tableView:(id)arg1 didUnhighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didHighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)createWXFriendsCell:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)createDaRensCell:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)createSingersCell:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)createQQFriendsCell:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)createGroupCell:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)_listenOrCancelListenSuccessCallback:(id)arg1;
- (void)onFollowOrCancelViewClicked:(_Bool)arg1 WithSingerInfo:(id)arg2;
- (void)syncFollowStatus:(id)arg1;
- (void)queryGeneSimiliarDarenByPage:(unsigned long long)arg1;
- (void)queryGeneSimiliarSingerByPage:(unsigned long long)arg1;
- (void)queryFollowSingerWithSingerId:(unsigned long long)arg1 isFollow:(_Bool)arg2 AndCellIndex:(long long)arg3;
- (void)queryFollowWXFriendWithUin:(unsigned long long)arg1 isFollow:(_Bool)arg2 AndCellIndex:(long long)arg3;
- (void)queryFollowDarenWithUin:(unsigned long long)arg1 isFollow:(_Bool)arg2 AndCellIndex:(long long)arg3;
- (void)queryWXFriendList;
- (void)queryQQFriendGroupDetailInfo:(long long)arg1;
- (void)queryQQFriendGroupInfo;
- (void)didReceiveMemoryWarning;
- (void)animationFromLastTable:(id)arg1 withOrientation:(long long)arg2 showLoadingView:(_Bool)arg3;
- (id)createTableViewWithTab:(long long)arg1;
- (void)changeCurrentTable:(long long)arg1 WithAnimation:(_Bool)arg2;
- (void)changeSelectedView:(id)arg1;
- (void)switchCurrentTab:(id)arg1;
- (void)switchCurrentTabWithNoAnimation:(id)arg1;
- (void)createHeaderTabBar;
- (void)reFresh;
- (void)showNetErrWithResult:(int)arg1 tab:(long long)arg2;
- (void)showEmptyView;
- (float)infoViewTopOffset;
- (float)emptyViewTopOffset;
- (id)emptyViewText;
- (int)vcType;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

