//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

#import "ImageManagerDelegate-Protocol.h"
#import "ProfileViewControllerDelegate-Protocol.h"
#import "QMTabBarDelegate-Protocol.h"

@class NSMutableArray, NSString;

@interface FollowsViewController : SkinViewController <ImageManagerDelegate, ProfileViewControllerDelegate, QMTabBarDelegate>
{
    _Bool shouldUpdateFollowList;
    _Bool singerNewborn;
    _Bool userNewborn;
    _Bool _loadingMore;
    _Bool _bUserEvent;
    int currentIndex;
    int _selectIndex;
    long long SingerTotalCount;
    long long UserTotalCount;
    unsigned long long _visitUin;
    long long _followsTotalCount;
    NSMutableArray *_FollowsList;
}

@property(nonatomic) int selectIndex; // @synthesize selectIndex=_selectIndex;
@property(nonatomic) _Bool bUserEvent; // @synthesize bUserEvent=_bUserEvent;
@property(retain, nonatomic) NSMutableArray *FollowsList; // @synthesize FollowsList=_FollowsList;
@property(nonatomic) _Bool loadingMore; // @synthesize loadingMore=_loadingMore;
@property(nonatomic) long long followsTotalCount; // @synthesize followsTotalCount=_followsTotalCount;
@property(nonatomic) unsigned long long visitUin; // @synthesize visitUin=_visitUin;
@property(nonatomic) long long UserTotalCount; // @synthesize UserTotalCount;
@property(nonatomic) long long SingerTotalCount; // @synthesize SingerTotalCount;
@property(nonatomic) int currentIndex; // @synthesize currentIndex;
@property(nonatomic) _Bool userNewborn; // @synthesize userNewborn;
@property(nonatomic) _Bool singerNewborn; // @synthesize singerNewborn;
- (void).cxx_destruct;
- (void)onNotifyUpdateFollowList;
- (void)doMoreAboutTabBar:(id)arg1;
- (void)cancelFollowUser:(unsigned long long)arg1;
- (void)touchDown:(id)arg1 itemAtIndex:(unsigned long long)arg2;
- (void)touchUpInside:(id)arg1 itemAtIndex:(unsigned long long)arg2;
- (id)selectedImageView:(id)arg1;
- (id)selectetdItemImage:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)pressedItemImage:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)backgroundImage:(id)arg1;
- (id)accessibilityLabel:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)imageFor:(id)arg1 atIndex:(unsigned long long)arg2;
- (_Bool)moreDataIsLoading:(id)arg1;
- (void)processingLoadMoreAction:(id)arg1;
- (_Bool)hasMoreDataInTableView:(id)arg1;
- (void)onImagetWithInfo:(id)arg1 Image:(id)arg2;
- (void)showTable;
- (void)reFresh;
- (void)_showTabInfoViewWithTitle:(id)arg1 subtitle:(id)arg2 tapSelector:(SEL)arg3 iconName:(id)arg4;
- (void)_showTabLoadingView;
- (void)_blankMethod;
- (_Bool)isGuest;
- (void)onNotifyFollowsListUpdate:(id)arg1;
- (void)showEmptyFollows:(int)arg1;
- (void)viewDidPop;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)_hideTabLoadingView;
- (void)_loadUserList;
- (void)_loadSingerList;
- (void)refreshTable;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
- (void)enterFollowMoreVC;
- (void)setSubviewsSelected:(_Bool)arg1;
- (void)setSubviewsNotSelected;
- (void)setSubviewsSelected;
- (void)freshHeaderSeprateLine;
- (void)buildTableHeaderView;
- (void)_buildHeaderTabBar;
- (void)resetSongTableFrame;
- (void)reLayout:(long long)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (int)statusBarOffset;
- (struct CGRect)reFrame;
- (id)initWithUin:(unsigned long long)arg1 totalFollowsCount:(long long)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

