//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "HookViewController.h"

@class UINavigationController;

@interface FormSheetContainerVC : HookViewController
{
    UINavigationController *_navVC;
    long long _beforeStatusStyle;
}

@property(nonatomic) long long beforeStatusStyle; // @synthesize beforeStatusStyle=_beforeStatusStyle;
@property(retain, nonatomic) UINavigationController *navVC; // @synthesize navVC=_navVC;
- (void).cxx_destruct;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

@end

