//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ClickInfo, ExposureInfo, GDTAD, GDTLoadAdRequest, GDTNetRequest, NSData, NSDictionary, NSString;

@protocol GDTAdProtoDelegate <NSObject>
- (GDTNetRequest *)encodeFeedBackRequest:(GDTAD *)arg1 feedBackType:(int)arg2;
- (GDTNetRequest *)encodeCloseRequest:(GDTAD *)arg1 clickInfo:(ClickInfo *)arg2;
- (NSString *)encodeLinkClickUrl:(GDTAD *)arg1 clickInfo:(ClickInfo *)arg2;
- (GDTNetRequest *)encodeExposureRequest:(NSString *)arg1 exposureInfo:(ExposureInfo *)arg2;
- (NSDictionary *)decodeLoadAdResponse:(NSData *)arg1 adRequest:(GDTLoadAdRequest *)arg2;
- (GDTNetRequest *)encodeLoadAdRequest:(GDTLoadAdRequest *)arg1;
@end

