//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray;

@interface GetAllBubbleLists : NSObject
{
    NSMutableArray *_allBubbleList;
    long long _tabsNum;
}

@property(nonatomic) long long tabsNum; // @synthesize tabsNum=_tabsNum;
@property(retain, nonatomic) NSMutableArray *allBubbleList; // @synthesize allBubbleList=_allBubbleList;
- (void).cxx_destruct;

@end

