//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSString;

@interface GetMusickeyProtocol : ProtocolBaseJason
{
    _Bool _getAccToken;
    NSString *_accToken;
    NSString *_code;
}

@property(retain, nonatomic) NSString *code; // @synthesize code=_code;
@property(retain, nonatomic) NSString *accToken; // @synthesize accToken=_accToken;
@property(nonatomic) _Bool getAccToken; // @synthesize getAccToken=_getAccToken;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getUrl;
- (int)cid;
- (id)initWithWxCode:(id)arg1;

@end

