//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageTwoInputFilter.h"

@interface GPUImageMoveRightFilter : GPUImageTwoInputFilter
{
    int bounceXUniform;
    int bounceYUniform;
    double _bounceX;
    double _bounceY;
}

@property(nonatomic) double bounceY; // @synthesize bounceY=_bounceY;
@property(nonatomic) double bounceX; // @synthesize bounceX=_bounceX;
- (id)init;

@end

