//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MyCamGPUFilter.h"

@interface GPUImageMultiplyBlendFilter2 : MyCamGPUFilter
{
}

- (void)setColor3:(float)arg1 andG:(float)arg2 andB:(float)arg3 andA:(float)arg4 andTransParency:(float)arg5;
- (void)setColor2:(float)arg1 andG:(float)arg2 andB:(float)arg3 andA:(float)arg4;
- (id)init;

@end

