//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface GreenDayView : UIView
{
    UILabel *_dayLabel;
    UILabel *_expireLabel;
}

@property(retain, nonatomic) UILabel *expireLabel; // @synthesize expireLabel=_expireLabel;
@property(retain, nonatomic) UILabel *dayLabel; // @synthesize dayLabel=_dayLabel;
- (void).cxx_destruct;
- (void)setUpgradeDay:(int)arg1 expire:(id)arg2;
- (void)addAllSubviews;
- (id)createLabel:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

