//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IDEtchSession.h"

@interface IDEtchSession (Error)
- (id)etchExceptionError:(id)arg1 forCall:(id)arg2;
- (id)invalidValueErrorForParameter:(id)arg1 callName:(id)arg2;
- (id)nilParameterErrorForParameter:(id)arg1 callName:(id)arg2;
- (id)wrongStateErrorForCall:(id)arg1;
@end

