//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "IDApplicationDataSource-Protocol.h"
#import "IDApplicationManagementServiceDataSource-Protocol.h"
#import "IDApplicationManagementServiceDelegate-Protocol.h"
#import "IDMessagingServiceSubscriber-Protocol.h"
#import "IDRhmiConnectedAppsViewControllerDelegate-Protocol.h"

@class IDApplication, IDApplicationManagementService, IDMessagingService, IDRhmiConnectedAppsViewController, NSConditionLock, NSDictionary, NSMutableDictionary, NSString;

@interface IDRhmiAppSwitcher : NSObject <IDApplicationManagementServiceDelegate, IDApplicationManagementServiceDataSource, IDMessagingServiceSubscriber, IDRhmiConnectedAppsViewControllerDelegate, IDApplicationDataSource>
{
    IDApplication *_application;
    IDApplicationManagementService *_amService;
    IDMessagingService *_messagingService;
    id _featureInfoDeleteObserver;
    id _featureInfoUpdateObserver;
    NSMutableDictionary *_connectedApplications;
    NSConditionLock *_stateCondition;
    IDRhmiConnectedAppsViewController *_connectedAppsViewController;
    NSString *_shouldLaunchAppIdentifier;
    NSDictionary *_localizedAppNotStartedHints;
    NSString *_bundleIdentifier;
}

@property(readonly) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(readonly) NSDictionary *localizedAppNotStartedHints; // @synthesize localizedAppNotStartedHints=_localizedAppNotStartedHints;
@property(retain) NSString *shouldLaunchAppIdentifier; // @synthesize shouldLaunchAppIdentifier=_shouldLaunchAppIdentifier;
@property(retain) IDRhmiConnectedAppsViewController *connectedAppsViewController; // @synthesize connectedAppsViewController=_connectedAppsViewController;
@property(retain) NSConditionLock *stateCondition; // @synthesize stateCondition=_stateCondition;
@property(retain) NSMutableDictionary *connectedApplications; // @synthesize connectedApplications=_connectedApplications;
@property(retain) id featureInfoUpdateObserver; // @synthesize featureInfoUpdateObserver=_featureInfoUpdateObserver;
@property(retain) id featureInfoDeleteObserver; // @synthesize featureInfoDeleteObserver=_featureInfoDeleteObserver;
@property __weak IDMessagingService *messagingService; // @synthesize messagingService=_messagingService;
@property(retain) IDApplicationManagementService *amService; // @synthesize amService=_amService;
@property(retain) IDApplication *application; // @synthesize application=_application;
- (void).cxx_destruct;
- (id)findFeatureInfoWithAppIdentifier:(id)arg1;
- (void)onUpdateLanguage:(id)arg1;
- (id)textDatabasesForApplication:(id)arg1;
- (id)hmiDescriptionForApplication:(id)arg1;
- (id)manifestForApplication:(id)arg1;
- (void)deleteDisconnectedAppsAfterTimeout:(double)arg1;
- (void)saveNamedBundleIdentifier:(id)arg1;
- (void)enqueueDisconnectApplicationRequest:(id)arg1;
- (void)enqueueBroadcastProtocolRequest;
- (void)handleNotification:(id)arg1;
- (void)handleResponse:(id)arg1;
- (void)handleRequest:(id)arg1;
- (void)handleMessage:(id)arg1;
- (void)didSelectBundleIdentifier:(id)arg1;
- (id)localizedApplicationNotConnectedPreviewStrings;
- (void)switchToRhmiFeature:(id)arg1;
- (void)launchAppIdentifier:(id)arg1;
- (void)applicationManagementService:(id)arg1 shouldStartAppIdentifier:(id)arg2;
- (void)waitForApplicationPingWithTimeout:(float)arg1;
- (void)registerFeatureInfo:(id)arg1;
- (void)registerFeatureInfosWithBundleIdentifiers:(id)arg1;
- (void)registerInstalledFeatureInfos;
- (void)disconnect;
- (void)connect;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

