//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IDTable;

@protocol IDTableDelegate <NSObject>

@optional
- (void)table:(IDTable *)arg1 didFocusItemAtIndex:(long long)arg2;
- (void)table:(IDTable *)arg1 didSelectItemAtIndex:(long long)arg2;
@end

