//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSStreamDelegate-Protocol.h"

@class IDA4APacketQueue, IDWorkerThread, NSData, NSInputStream, NSLock, NSOutputStream, NSString;
@protocol IDTcpConnectionDelegate;

@interface IDTcpConnection : NSObject <NSStreamDelegate>
{
    _Bool _paused;
    unsigned short _connectionID;
    int _nativeHandle;
    id <IDTcpConnectionDelegate> _delegate;
    unsigned long long _state;
    IDA4APacketQueue *_packetWriteQueue;
    NSData *_outgoingDataBuffer;
    NSInputStream *_inputStream;
    NSOutputStream *_outputStream;
    NSLock *_connectionStateLock;
    IDWorkerThread *_workerThread;
}

@property(readonly) IDWorkerThread *workerThread; // @synthesize workerThread=_workerThread;
@property(getter=isPaused) _Bool paused; // @synthesize paused=_paused;
@property(retain) NSLock *connectionStateLock; // @synthesize connectionStateLock=_connectionStateLock;
@property(retain) NSOutputStream *outputStream; // @synthesize outputStream=_outputStream;
@property(retain) NSInputStream *inputStream; // @synthesize inputStream=_inputStream;
@property(retain) NSData *outgoingDataBuffer; // @synthesize outgoingDataBuffer=_outgoingDataBuffer;
@property(readonly) IDA4APacketQueue *packetWriteQueue; // @synthesize packetWriteQueue=_packetWriteQueue;
@property int nativeHandle; // @synthesize nativeHandle=_nativeHandle;
@property unsigned long long state; // @synthesize state=_state;
@property unsigned short connectionID; // @synthesize connectionID=_connectionID;
@property __weak id <IDTcpConnectionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)informDelegateAboutError:(id)arg1;
- (id)stringWithState:(unsigned long long)arg1;
@property(readonly, copy) NSString *description;
- (_Bool)isAllowedToRead;
- (void)enqueuePacket:(id)arg1;
- (void)readIncomingData;
- (void)writeOutgoingData;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;
- (void)resumeReading;
- (void)pauseReading;
- (void)stopReading;
- (void)startReading;
- (void)closeStreams;
- (void)openStreams;
- (id)initWithSocketNativeHandle:(int)arg1 connectionID:(unsigned short)arg2 delegate:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

