//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray;

@interface ImportSongList : NSObject
{
    long long _totalSize;
    long long _sn;
    long long _count;
    NSMutableArray *_list;
}

@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
@property(nonatomic) long long count; // @synthesize count=_count;
@property(nonatomic) long long sn; // @synthesize sn=_sn;
@property(nonatomic) long long totalSize; // @synthesize totalSize=_totalSize;
- (void).cxx_destruct;

@end

