//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AudioPlayerBase.h"

@class AVAsset, AVPlayer;

@interface IPodAVPlayer : AudioPlayerBase
{
    AVPlayer *player;
    AVAsset *currentAsset;
    _Bool isLoadAssetOK;
    double _notSuccessSeekPos;
}

@property(nonatomic) double notSuccessSeekPos; // @synthesize notSuccessSeekPos=_notSuccessSeekPos;
@property(retain) AVAsset *currentAsset; // @synthesize currentAsset;
@property(retain) AVPlayer *player; // @synthesize player;
- (void).cxx_destruct;
- (void)clearAudioMix;
- (void)fadeVolumeFrom:(double)arg1 toVolume:(double)arg2 duration:(double)arg3;
- (void)pauseAndFadeOutVolumeWithDuration:(double)arg1;
- (void)playAndFadeInVolumeWithDuration:(double)arg1;
- (double)duration;
- (double)progress;
- (void)postAVPlayerStateChangedNotification;
- (void)setSeekTime:(double)arg1;
- (void)destroy;
- (void)stop;
- (void)resume;
- (void)pauseImmediately:(_Bool)arg1;
- (void)pause;
- (void)mainThreadPlay;
- (void)play;
- (void)prepareWithAVAsset:(id)arg1;
- (void)playerItemDidReachEnd:(id)arg1;

@end

