//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class KSAudioDataProvider, KSAudioProcessor, KSLimitNetParam, KSSongInfo, LZAudioDataDownloader, NSObject, NSString;
@protocol KSAudioPlayerUserDefineProtocol, OS_dispatch_queue;

@protocol KSAudioPlayerUserDefineProtocol <NSObject>
- (_Bool)isNetOk;

@optional
- (KSLimitNetParam *)limitNetParam;
- (NSString *)retryUrlFilter:(KSSongInfo *)arg1 lastUrl:(NSString *)arg2 retryCnt:(unsigned int)arg3;
- (unsigned int)downloadRetryCnt;
- (LZAudioDataDownloader *)createAudioDownloader;
- (KSAudioDataProvider *)createDataProvider:(KSSongInfo *)arg1 queue:(NSObject<OS_dispatch_queue> *)arg2 context:(void *)arg3 downloadProtocol:(id <KSAudioPlayerUserDefineProtocol>)arg4;
- (KSAudioProcessor *)createUserAudioProcessor:(KSSongInfo *)arg1;
@end

