//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface KSongNewInfo : NSObject
{
    _Bool _bSHowRed;
    NSString *_strUid;
    double _dTimeStamp;
}

@property(nonatomic) _Bool bSHowRed; // @synthesize bSHowRed=_bSHowRed;
@property(nonatomic) double dTimeStamp; // @synthesize dTimeStamp=_dTimeStamp;
@property(retain, nonatomic) NSString *strUid; // @synthesize strUid=_strUid;
- (void).cxx_destruct;
- (void)resetNewInfo;

@end

