//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SearchResultBaseVC.h"

#import "ImageManagerDelegate-Protocol.h"

@class DirectItem, NSString, SkinViewController, UIButton, UIView;

@interface LibrarySearchSongsListVC : SearchResultBaseVC <ImageManagerDelegate>
{
    SkinViewController *viewController;
    UIButton *btRadioPlay;
    DirectItem *curDirectItem;
    UIView *_directView;
}

@property(retain, nonatomic) UIView *directView; // @synthesize directView=_directView;
@property(retain, nonatomic) DirectItem *curDirectItem; // @synthesize curDirectItem;
@property(retain, nonatomic) UIButton *btRadioPlay; // @synthesize btRadioPlay;
@property(nonatomic) __weak SkinViewController *viewController; // @synthesize viewController;
- (void).cxx_destruct;
- (void)handleFetchRadioListStatus:(long long)arg1 radioProtocol:(id)arg2 protocolError:(id)arg3;
- (id)createVCFrom:(id)arg1;
- (void)jumpToPlayRadio:(id)arg1;
- (void)radioPlayBtnPress:(id)arg1;
- (void)playStatusDidChange:(id)arg1;
- (void)jumptoYuyiVC;
- (void)onDirect:(id)arg1;
- (void)reSearchWithOutCorret:(id)arg1;
- (void)resizeHeadViewHeight;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)createDirectButton;
- (void)reFreshSuccess;
- (void)onImagetWithInfo:(id)arg1 Image:(id)arg2;
- (_Bool)showDelBtnInActionSheet:(id)arg1;
- (void)updateBtnClicked:(id)arg1;
- (id)getAllVCType;
- (id)strVCtype;
- (void)dealloc;
- (void)viewDidLoad;
- (struct CGRect)reFrame;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

