//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSMutableArray, NSString;

@protocol LyricChangeDelegate <NSObject>

@optional
- (void)onLyricDidShowLastLyric:(long long)arg1;
- (void)onLyricLongPress:(long long)arg1;
- (void)onLyricMoveToNext:(NSString *)arg1 lineNum:(int)arg2;
- (void)onLyricChangeWithTextArray:(NSMutableArray *)arg1;
@end

