//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel;

@interface LyricTableViewCell : UITableViewCell
{
    UIImageView *_iconImgView;
    UILabel *_lblOrignal;
    UILabel *_lblTranslate;
    long long _type;
    _Bool _bSelected;
}

@property(nonatomic) _Bool bSelected; // @synthesize bSelected=_bSelected;
- (void).cxx_destruct;
- (void)setLyricItem:(id)arg1;
- (id)initWithReuseIdentifier:(id)arg1 type:(long long)arg2;

@end

