//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MarqueeLabel.h"

@interface MarqueeForPlayVCLabel : MarqueeLabel
{
    _Bool _enableScrolling;
    _Bool _isScrolling;
}

@property(nonatomic) _Bool isScrolling; // @synthesize isScrolling=_isScrolling;
@property(nonatomic) _Bool enableScrolling; // @synthesize enableScrolling=_enableScrolling;
- (_Bool)shouldContinueToScrolling;
- (void)labelReturnedToHome:(_Bool)arg1;

@end

