//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSArray, NSMutableArray;
@protocol MultiColumnTableViewDelegate;

@interface MultiColumnTableViewCell : UITableViewCell
{
    NSMutableArray *_arrayViews;
    float _fTotalWidth;
    float _fMargin;
    int _iColumns;
    NSArray *_arrayColumns;
    id <MultiColumnTableViewDelegate> _delegate;
}

@property(nonatomic) id <MultiColumnTableViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *arrayColumns; // @synthesize arrayColumns=_arrayColumns;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)stopObserving;
- (void)initColums;
- (id)initWithReuseIdentifier:(id)arg1 withColumn:(int)arg2 width:(float)arg3;
- (void)dealloc;

@end

