//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSArray;

@interface MultiStateButton : UIButton
{
    CDUnknownBlockType _mutilBtnBlock;
    unsigned long long _nState;
    NSArray *_normalImages;
    NSArray *_hlImages;
    NSArray *_accessibilityArray;
}

@property(retain, nonatomic) NSArray *accessibilityArray; // @synthesize accessibilityArray=_accessibilityArray;
@property(retain, nonatomic) NSArray *hlImages; // @synthesize hlImages=_hlImages;
@property(retain, nonatomic) NSArray *normalImages; // @synthesize normalImages=_normalImages;
@property(nonatomic) unsigned long long nState; // @synthesize nState=_nState;
@property(copy, nonatomic) CDUnknownBlockType mutilBtnBlock; // @synthesize mutilBtnBlock=_mutilBtnBlock;
- (void).cxx_destruct;
- (void)btnPressed:(id)arg1;
- (void)resetBtnState;
- (void)changeBtnState;
- (id)initWithTitle:(id)arg1 normalImages:(id)arg2 hlImages:(id)arg3 accessibilityLabels:(id)arg4;

@end

