//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCopying-Protocol.h"

@class ChannelCreator, NSArray, NSAttributedString, NSString;

@interface MusicCircleFeed : NSObject <NSCopying>
{
    _Bool zanFlg;
    _Bool bShowCompleteDesc;
    _Bool _hasMoreComment;
    int serverFeedSubType;
    int serverFeedType;
    int downFlg;
    float zanHeight;
    float descHeight;
    float commentHeight;
    int zanNum;
    int commentNum;
    float subDescHeight;
    int _circleFeedType;
    int _operateState;
    NSString *feedId;
    NSString *feedDesc;
    ChannelCreator *owner;
    double createTime;
    NSString *feedPic;
    NSString *feedJsonURL;
    NSArray *songArray;
    NSArray *zanArray;
    NSArray *commentArray;
    NSString *tmpCommentMsg;
    NSAttributedString *attributedZanString;
    NSAttributedString *attributedDescString;
    NSAttributedString *attributedCommentString;
    NSString *actionName;
    NSString *mainContentName;
    NSString *subContentName;
    NSString *thrContentName;
    NSString *smallContentName;
    unsigned long long _contentId;
}

+ (void)tranlateFromJsonData:(id)arg1 toFeed:(id)arg2;
+ (id)tranlateFromJsonData:(id)arg1;
@property(nonatomic) int operateState; // @synthesize operateState=_operateState;
@property(nonatomic) _Bool hasMoreComment; // @synthesize hasMoreComment=_hasMoreComment;
@property(nonatomic) unsigned long long contentId; // @synthesize contentId=_contentId;
@property(nonatomic) int circleFeedType; // @synthesize circleFeedType=_circleFeedType;
@property(nonatomic) float subDescHeight; // @synthesize subDescHeight;
@property(nonatomic) int commentNum; // @synthesize commentNum;
@property(nonatomic) int zanNum; // @synthesize zanNum;
@property(retain, nonatomic) NSString *smallContentName; // @synthesize smallContentName;
@property(retain, nonatomic) NSString *thrContentName; // @synthesize thrContentName;
@property(retain, nonatomic) NSString *subContentName; // @synthesize subContentName;
@property(retain, nonatomic) NSString *mainContentName; // @synthesize mainContentName;
@property(retain, nonatomic) NSString *actionName; // @synthesize actionName;
@property(nonatomic) float commentHeight; // @synthesize commentHeight;
@property(nonatomic) float descHeight; // @synthesize descHeight;
@property(nonatomic) float zanHeight; // @synthesize zanHeight;
@property(retain, nonatomic) NSAttributedString *attributedCommentString; // @synthesize attributedCommentString;
@property(retain, nonatomic) NSAttributedString *attributedDescString; // @synthesize attributedDescString;
@property(retain, nonatomic) NSAttributedString *attributedZanString; // @synthesize attributedZanString;
@property(nonatomic) _Bool bShowCompleteDesc; // @synthesize bShowCompleteDesc;
@property(retain, nonatomic) NSString *tmpCommentMsg; // @synthesize tmpCommentMsg;
@property(retain, nonatomic) NSArray *commentArray; // @synthesize commentArray;
@property(retain, nonatomic) NSArray *zanArray; // @synthesize zanArray;
@property(retain, nonatomic) NSArray *songArray; // @synthesize songArray;
@property(retain, nonatomic) NSString *feedJsonURL; // @synthesize feedJsonURL;
@property(nonatomic) _Bool zanFlg; // @synthesize zanFlg;
@property(retain, nonatomic) NSString *feedPic; // @synthesize feedPic;
@property(nonatomic) int downFlg; // @synthesize downFlg;
@property(nonatomic) double createTime; // @synthesize createTime;
@property(retain, nonatomic) ChannelCreator *owner; // @synthesize owner;
@property(nonatomic) int serverFeedType; // @synthesize serverFeedType;
@property(nonatomic) int serverFeedSubType; // @synthesize serverFeedSubType;
@property(retain, nonatomic) NSString *feedDesc; // @synthesize feedDesc;
@property(retain, nonatomic) NSString *feedId; // @synthesize feedId;
- (void).cxx_destruct;
- (void)freshAllString:(id)arg1;
- (void)refreshAttributeDescString;
- (id)attributeDescString;
- (void)refreshAttributeZanString;
- (id)attributeZanString;
- (void)refreshAttributeCommentString;
- (id)attributeCommentString;
- (id)transLateToChannelItem;
- (float)fullHeight;
- (float)baseHeight;
- (_Bool)isCurrentPlaying;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;

@end

