//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface MusicBubbleInfo : NSObject
{
    _Bool _enabled;
    unsigned long long _uBubbleId;
    NSString *_strDescription;
    NSString *_strCoverUrl;
    NSString *_strRealUrl;
    unsigned long long _userLevel;
    long long _msgid;
}

@property(nonatomic) long long msgid; // @synthesize msgid=_msgid;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) unsigned long long userLevel; // @synthesize userLevel=_userLevel;
@property(retain, nonatomic) NSString *strRealUrl; // @synthesize strRealUrl=_strRealUrl;
@property(retain, nonatomic) NSString *strCoverUrl; // @synthesize strCoverUrl=_strCoverUrl;
@property(retain, nonatomic) NSString *strDescription; // @synthesize strDescription=_strDescription;
@property(nonatomic) unsigned long long uBubbleId; // @synthesize uBubbleId=_uBubbleId;
- (void).cxx_destruct;

@end

