//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface MusicBulletGift : NSObject
{
    unsigned long long _songid;
    NSString *_userLogoUrl;
    NSString *_nick;
    unsigned long long _offset;
    unsigned long long _optime;
    NSString *_giftMessage;
    NSString *_giftPicUrl;
    unsigned long long _giftNum;
    unsigned long long _animationID;
}

@property(nonatomic) unsigned long long animationID; // @synthesize animationID=_animationID;
@property(nonatomic) unsigned long long giftNum; // @synthesize giftNum=_giftNum;
@property(retain, nonatomic) NSString *giftPicUrl; // @synthesize giftPicUrl=_giftPicUrl;
@property(retain, nonatomic) NSString *giftMessage; // @synthesize giftMessage=_giftMessage;
@property(nonatomic) unsigned long long optime; // @synthesize optime=_optime;
@property(nonatomic) unsigned long long offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSString *nick; // @synthesize nick=_nick;
@property(retain, nonatomic) NSString *userLogoUrl; // @synthesize userLogoUrl=_userLogoUrl;
@property(nonatomic) unsigned long long songid; // @synthesize songid=_songid;
- (void).cxx_destruct;
- (id)description;

@end

