//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController_Comment.h"

#import "EGORefreshTableHeaderDelegate-Protocol.h"
#import "ImageManagerDelegate-Protocol.h"
#import "ListTagDelegate-Protocol.h"
#import "MusicCircleCellDelegate-Protocol.h"
#import "OHAttributedLabelDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class EGORefreshTableHeaderView, MusicCircleBannerItem, NSArray, NSMutableArray, NSString, UIControl, UIView;

@interface MusicCircleVC : SkinViewController_Comment <UITableViewDataSource, UITableViewDelegate, ListTagDelegate, EGORefreshTableHeaderDelegate, MusicCircleCellDelegate, ImageManagerDelegate, OHAttributedLabelDelegate>
{
    _Bool _reloading;
    _Bool _loadingMore;
    _Bool _bAutoScroll;
    _Bool _bNeedResetPosition;
    EGORefreshTableHeaderView *_refreshHeaderView;
    NSMutableArray *_requestArray;
    UIView *_headerView;
    NSArray *_resultArray;
    UIView *_tableFootView;
    MusicCircleBannerItem *_bannerItem;
    UIControl *_bannerView;
}

@property(retain, nonatomic) UIControl *bannerView; // @synthesize bannerView=_bannerView;
@property(retain, nonatomic) MusicCircleBannerItem *bannerItem; // @synthesize bannerItem=_bannerItem;
@property(retain, nonatomic) UIView *tableFootView; // @synthesize tableFootView=_tableFootView;
@property(retain, nonatomic) NSArray *resultArray; // @synthesize resultArray=_resultArray;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) NSMutableArray *requestArray; // @synthesize requestArray=_requestArray;
@property(retain, nonatomic) EGORefreshTableHeaderView *refreshHeaderView; // @synthesize refreshHeaderView=_refreshHeaderView;
- (void).cxx_destruct;
- (void)doDelThisFeed:(id)arg1 withSender:(id)arg2;
- (_Bool)isNeedHideContainViewWhenKeyBoardHide;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onList:(id)arg1 WithResult:(int)arg2 AndAct:(id)arg3;
- (double)headerOffsetY;
- (void)resetHeaderView;
- (void)reloadData;
- (void)gotoNewInfoVC;
- (void)onImagetWithInfo:(id)arg1 Image:(id)arg2;
- (void)onImagetWithInfo:(id)arg1 ImageFile:(id)arg2;
- (id)buildHeaderView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (_Bool)attributedLabel:(id)arg1 shouldFollowLink:(id)arg2;
- (void)buildTableFootView;
- (id)buildEnterSquareVCLabelView;
- (id)buildMayInterestPersonView;
- (_Bool)moreDataIsLoading:(id)arg1;
- (void)processingLoadMoreAction:(id)arg1;
- (_Bool)hasMoreDataInTableView:(id)arg1;
- (id)egoRefreshTableHeaderDataSourceLastUpdated:(id)arg1;
- (_Bool)egoRefreshTableHeaderDataSourceIsLoading:(id)arg1;
- (void)egoRefreshTableHeaderDidTriggerRefresh:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)doneLoadingTableViewData;
- (void)reloadTableViewDataSource;
- (void)jumpToBannerTarget;
- (void)updateBannerView;
- (void)updateBannerViewWithImage:(id)arg1;
- (void)updateBannerView:(id)arg1;
- (void)enterMyFollowVC;
- (void)enterSquareVC;
- (void)autoDragScrollView;
- (void)reFresh;
- (void)makeList;
- (void)onNotifyLogout:(id)arg1;
- (void)resetEmptyViewPosition;
- (void)showEmptyView;
- (id)emptyViewText;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (int)vcType;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

