//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QQMusicCell.h"

#import "ImageManagerDelegate-Protocol.h"
#import "OHAttributedLabelDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class FeedCommentInfo, MusicCircleFeed, NSString, OHAttributedLabel, UIButton, UIImageView, UILabel;
@protocol MusicCircleCellDelegate><MusicFeedDetailImagAndTextCellDelegate;

@interface MusicFeedDetailImagAndTextCell : QQMusicCell <ImageManagerDelegate, OHAttributedLabelDelegate, UIActionSheetDelegate>
{
    _Bool _isShowDeleteView;
    _Bool _isShowKeyboard;
    UIImageView *_commentFaceView;
    UILabel *_commentNickLable;
    UILabel *_commentDateLable;
    OHAttributedLabel *_mainCommentLable;
    MusicCircleFeed *_detailFeed;
    UIButton *_delButton;
    FeedCommentInfo *_commentInfo;
    id <MusicCircleCellDelegate><MusicFeedDetailImagAndTextCellDelegate> delegate;
}

@property(nonatomic) _Bool isShowKeyboard; // @synthesize isShowKeyboard=_isShowKeyboard;
@property(nonatomic) __weak id <MusicCircleCellDelegate><MusicFeedDetailImagAndTextCellDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) FeedCommentInfo *commentInfo; // @synthesize commentInfo=_commentInfo;
@property _Bool isShowDeleteView; // @synthesize isShowDeleteView=_isShowDeleteView;
@property(retain, nonatomic) UIButton *delButton; // @synthesize delButton=_delButton;
@property(retain, nonatomic) MusicCircleFeed *detailFeed; // @synthesize detailFeed=_detailFeed;
@property(retain, nonatomic) OHAttributedLabel *mainCommentLable; // @synthesize mainCommentLable=_mainCommentLable;
@property(retain, nonatomic) UILabel *commentDateLable; // @synthesize commentDateLable=_commentDateLable;
@property(retain, nonatomic) UILabel *commentNickLable; // @synthesize commentNickLable=_commentNickLable;
@property(retain, nonatomic) UIImageView *commentFaceView; // @synthesize commentFaceView=_commentFaceView;
- (void).cxx_destruct;
- (void)onNotifySkinSettingChange:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showActionSheet:(id)arg1;
- (void)recommentAction;
- (void)delayDoRecomment;
- (void)longPressToDo:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)attributedLabel:(id)arg1 shouldFollowLink:(id)arg2;
- (void)clickNickName:(id)arg1;
- (void)doDelThisCell:(id)arg1;
- (int)qmCellType;
- (void)clickFaceImage:(id)arg1;
- (void)onImagetWithInfo:(id)arg1 Image:(id)arg2;
- (void)setFeedCommentInfo:(id)arg1 currentFeed:(id)arg2;
- (void)setFaceImageViewTag:(int)arg1;
- (void)setShowDeleteView:(_Bool)arg1;
- (void)updateDataInfo:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

