//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageTwoInputFilter.h"

@interface MyCamTwoAlphaBlendFilter : GPUImageTwoInputFilter
{
    int mix0Uniform;
    int mix1Uniform;
    double _mix0;
    double _mix1;
}

@property(nonatomic) double mix1; // @synthesize mix1=_mix1;
@property(nonatomic) double mix0; // @synthesize mix0=_mix0;
- (id)init;

@end

