//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinTabBaseViewController.h"

#import "QMCreatorViewDelegate-Protocol.h"

@class MyLoveFolderTabVC, MyLoveSongTabVC, NSMutableArray, NSString, QMMyLoveSongSearchVC, QQUser, UIButton, UIView;

@interface MyLoveGroupVC : SkinTabBaseViewController <QMCreatorViewDelegate>
{
    QQUser *_thisUser;
    UIView *_smallView;
    MyLoveSongTabVC *_myLoveSongTabVC;
    MyLoveFolderTabVC *_myAlbumTabVC;
    MyLoveFolderTabVC *_mySongListTabVC;
    UIButton *_navBarRightButton;
    QMMyLoveSongSearchVC *_searchViewController;
    unsigned long long _songsCount;
}

@property(nonatomic) unsigned long long songsCount; // @synthesize songsCount=_songsCount;
@property(retain, nonatomic) QMMyLoveSongSearchVC *searchViewController; // @synthesize searchViewController=_searchViewController;
@property(retain, nonatomic) UIButton *navBarRightButton; // @synthesize navBarRightButton=_navBarRightButton;
@property(retain, nonatomic) MyLoveFolderTabVC *mySongListTabVC; // @synthesize mySongListTabVC=_mySongListTabVC;
@property(retain, nonatomic) MyLoveFolderTabVC *myAlbumTabVC; // @synthesize myAlbumTabVC=_myAlbumTabVC;
@property(retain, nonatomic) MyLoveSongTabVC *myLoveSongTabVC; // @synthesize myLoveSongTabVC=_myLoveSongTabVC;
@property(retain, nonatomic) UIView *smallView; // @synthesize smallView=_smallView;
@property(retain, nonatomic) QQUser *thisUser; // @synthesize thisUser=_thisUser;
- (void).cxx_destruct;
- (_Bool)shouldShowSearchBar;
- (void)goToSearch;
- (void)onNotifyFolderDataSaved:(id)arg1;
- (_Bool)isGuest;
- (void)notifyAutoDownloadLoveFolder;
- (void)animatetionForScrollView:(id)arg1 headerBigView:(id)arg2 headerBigImageView:(id)arg3 smallView:(id)arg4 smallImageView:(id)arg5 tabView:(id)arg6 title:(id)arg7 isBlur:(_Bool)arg8 withScrollDelta:(double)arg9;
- (void)reFreshWithNetworkDetection;
- (void)didLoadTabViewAtIndex:(int)arg1;
- (id)getAllVCType;
- (int)vcType;
- (void)addStatByJumpToIndex:(int)arg1;
- (void)creatorViewDidClick:(id)arg1;
- (void)tabDidscroll:(id)arg1 toPoint:(struct CGPoint)arg2;
- (void)buildScrollViewAndTabbar;
- (double)getClearViewHeight;
- (id)getSmallView;
- (void)updateHeaderTabNum:(long long)arg1 atIndex:(long long)arg2;
- (id)buildSmallView;
- (id)getCreator;
- (void)onTouchUpInsideMore:(id)arg1;
- (id)headerRightView;
- (unsigned long long)defaultTabIndex;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadView;
- (_Bool)isMySongList;
@property(nonatomic) int tabIndex; // @dynamic tabIndex;
- (void)initlizeTabBarTitleNum:(id)arg1;
- (id)getSongIdList:(id)arg1;
- (id)title;
- (void)createHeaderWithBg:(_Bool)arg1 LeftView:(id)arg2 HeaderText:(_Bool)arg3 RightView:(id)arg4;
- (id)initWithUser:(id)arg1 target:(int)arg2 isPartView:(_Bool)arg3;
- (id)initWithUser:(id)arg1 target:(int)arg2;
- (id)initWithUser:(id)arg1;
- (double)getHeaderImageViewY;
- (id)defaultHeadImage;
- (id)headerText;
- (unsigned long long)getHeadBgViewHeight;
- (unsigned long long)getHeadImageViewHeight;
- (_Bool)_shouldHeaderWithBg;
- (_Bool)isVerticalTabbar;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) NSMutableArray *tabTitleNums; // @dynamic tabTitleNums;

@end

