//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MyMusicMusicNumCollectionCell.h"

@interface MyMusicConciseNumCell : MyMusicMusicNumCollectionCell
{
}

- (double)titlefontSize;
- (double)separateLineIndent;
- (_Bool)showSeparateLine;
- (void)onNotifySkinSettingChange:(id)arg1;
- (id)subTitleLabel;
- (void)updateRedPoint:(_Bool)arg1;
- (void)updateSubTitle:(id)arg1;
- (void)updateData:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

