//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MyMusicSearchViewController.h"

#import "SongListSearchResultVCDelegate-Protocol.h"

@class SongListSearchResultVC;
@protocol SongListSearchResultVCDelegate;

@interface MyMusicFoderSongSearchVC : MyMusicSearchViewController <SongListSearchResultVCDelegate>
{
    _Bool _bFromPlayingList;
    _Bool _bFromCipai;
    id <SongListSearchResultVCDelegate> _songListSearchResultDelegate;
    SongListSearchResultVC *_detailVC;
}

@property(retain, nonatomic) SongListSearchResultVC *detailVC; // @synthesize detailVC=_detailVC;
@property(nonatomic) _Bool bFromCipai; // @synthesize bFromCipai=_bFromCipai;
@property(nonatomic) _Bool bFromPlayingList; // @synthesize bFromPlayingList=_bFromPlayingList;
@property(nonatomic) __weak id <SongListSearchResultVCDelegate> songListSearchResultDelegate; // @synthesize songListSearchResultDelegate=_songListSearchResultDelegate;
- (void).cxx_destruct;
- (_Bool)canAddSongToFolder:(id)arg1;
- (void)headerCancel:(id)arg1;
- (void)didSelectSong:(id)arg1 assetsType:(int)arg2;
- (void)handleCellLongPress:(id)arg1;
- (void)goOnlineSearch:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)showAddSongTips:(id)arg1;
- (void)viewDidLoad;

@end

