//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseScrollerVC.h"

#import "BannerVCDelegate-Protocol.h"
#import "CPDAdViewDelegate-Protocol.h"
#import "ImageManagerDelegate-Protocol.h"
#import "MyMusicRootProtocol-Protocol.h"
#import "MyMusicUserInfoCellDelegate-Protocol.h"
#import "NoNetBannerDelegate-Protocol.h"
#import "QMSearchHeaderViewDelegate-Protocol.h"
#import "QMSilentUserRecommendViewDelegate-Protocol.h"
#import "QMWordingViewDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "UIViewControllerPreviewingDelegate-Protocol.h"
#import "UserListenTimeUpdateDelegate-Protocol.h"

@class CPDAdItem, CPDAdView, FolderInfo, MyMusicSelectItem, NSArray, NSDictionary, NSIndexPath, NSMutableArray, NSString, NSTimer, QMSearchHeaderView, QMWordingTipsView, TemptToLoginTip, ThreeButtonItemData, UICollectionView;
@protocol MasterVCDelegate;

@interface MyMusicRootController : BaseScrollerVC <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout, UIViewControllerPreviewingDelegate, QMSearchHeaderViewDelegate, BannerVCDelegate, CPDAdViewDelegate, ImageManagerDelegate, MyMusicUserInfoCellDelegate, QMSilentUserRecommendViewDelegate, NoNetBannerDelegate, QMWordingViewDelegate, UserListenTimeUpdateDelegate, MyMusicRootProtocol>
{
    double _bannerHeight;
    _Bool _isBannerToShow;
    long long checkNoNetRepeatTimes;
    _Bool _hasNoNetBanner;
    _Bool _laterShowWordingTip;
    _Bool _showDownloadHistoryCount;
    _Bool _didLoadView;
    _Bool _canReloadIndexsPath;
    _Bool _didLoadCPDAd;
    _Bool _canLoadCPDAd;
    _Bool _hasMyDigitalExpose;
    int _folderType;
    int _userListenTime;
    id <MasterVCDelegate> _jumpdelegate;
    UICollectionView *_collectionView;
    QMSearchHeaderView *_collectionHederView;
    NSMutableArray *_arrayAll;
    FolderInfo *_currentFolder;
    NSArray *_folders;
    NSArray *_digitalAlbumFolders;
    long long _digitalFolderCount;
    NSIndexPath *_userInfoIndexPath;
    ThreeButtonItemData *_allSongsData;
    ThreeButtonItemData *_localSongsData;
    ThreeButtonItemData *_downloadedSongsData;
    ThreeButtonItemData *_recentPlaySongsData;
    ThreeButtonItemData *_iLikeSongData;
    ThreeButtonItemData *_mvDownloadSongsData;
    ThreeButtonItemData *_recronizedSongsData;
    NSArray *_localSectionData;
    TemptToLoginTip *_randomTip;
    NSTimer *_folderDataSavedUpdateTimer;
    NSTimer *_freeCountUpdateTimer;
    NSMutableArray *_reloadIndexsPathList;
    CPDAdItem *_currentADItem;
    CPDAdView *_currentADView;
    QMWordingTipsView *_listenTimeTipsView;
    QMWordingTipsView *_activityTipsView;
    NSDictionary *_userActivityInfo;
    NSIndexPath *_defaultIndex;
    MyMusicSelectItem *_nowSelect;
    NSIndexPath *_settedSelectIndex;
}

@property(retain, nonatomic) NSIndexPath *settedSelectIndex; // @synthesize settedSelectIndex=_settedSelectIndex;
@property(retain, nonatomic) MyMusicSelectItem *nowSelect; // @synthesize nowSelect=_nowSelect;
@property(retain, nonatomic) NSIndexPath *defaultIndex; // @synthesize defaultIndex=_defaultIndex;
@property(retain, nonatomic) NSDictionary *userActivityInfo; // @synthesize userActivityInfo=_userActivityInfo;
@property(retain, nonatomic) QMWordingTipsView *activityTipsView; // @synthesize activityTipsView=_activityTipsView;
@property(retain, nonatomic) QMWordingTipsView *listenTimeTipsView; // @synthesize listenTimeTipsView=_listenTimeTipsView;
@property(nonatomic) _Bool hasMyDigitalExpose; // @synthesize hasMyDigitalExpose=_hasMyDigitalExpose;
@property(nonatomic) _Bool canLoadCPDAd; // @synthesize canLoadCPDAd=_canLoadCPDAd;
@property(nonatomic) _Bool didLoadCPDAd; // @synthesize didLoadCPDAd=_didLoadCPDAd;
@property(retain, nonatomic) CPDAdView *currentADView; // @synthesize currentADView=_currentADView;
@property(retain, nonatomic) CPDAdItem *currentADItem; // @synthesize currentADItem=_currentADItem;
@property(retain, nonatomic) NSMutableArray *reloadIndexsPathList; // @synthesize reloadIndexsPathList=_reloadIndexsPathList;
@property(nonatomic) _Bool canReloadIndexsPath; // @synthesize canReloadIndexsPath=_canReloadIndexsPath;
@property(nonatomic) int userListenTime; // @synthesize userListenTime=_userListenTime;
@property _Bool didLoadView; // @synthesize didLoadView=_didLoadView;
@property _Bool showDownloadHistoryCount; // @synthesize showDownloadHistoryCount=_showDownloadHistoryCount;
@property(nonatomic) _Bool laterShowWordingTip; // @synthesize laterShowWordingTip=_laterShowWordingTip;
@property(retain) NSTimer *freeCountUpdateTimer; // @synthesize freeCountUpdateTimer=_freeCountUpdateTimer;
@property(retain) NSTimer *folderDataSavedUpdateTimer; // @synthesize folderDataSavedUpdateTimer=_folderDataSavedUpdateTimer;
@property(retain) TemptToLoginTip *randomTip; // @synthesize randomTip=_randomTip;
@property(retain) NSArray *localSectionData; // @synthesize localSectionData=_localSectionData;
@property(retain) ThreeButtonItemData *recronizedSongsData; // @synthesize recronizedSongsData=_recronizedSongsData;
@property(retain) ThreeButtonItemData *mvDownloadSongsData; // @synthesize mvDownloadSongsData=_mvDownloadSongsData;
@property(retain) ThreeButtonItemData *iLikeSongData; // @synthesize iLikeSongData=_iLikeSongData;
@property(retain) ThreeButtonItemData *recentPlaySongsData; // @synthesize recentPlaySongsData=_recentPlaySongsData;
@property(retain) ThreeButtonItemData *downloadedSongsData; // @synthesize downloadedSongsData=_downloadedSongsData;
@property(retain) ThreeButtonItemData *localSongsData; // @synthesize localSongsData=_localSongsData;
@property(retain) ThreeButtonItemData *allSongsData; // @synthesize allSongsData=_allSongsData;
@property(retain) NSIndexPath *userInfoIndexPath; // @synthesize userInfoIndexPath=_userInfoIndexPath;
@property long long digitalFolderCount; // @synthesize digitalFolderCount=_digitalFolderCount;
@property(retain) NSArray *digitalAlbumFolders; // @synthesize digitalAlbumFolders=_digitalAlbumFolders;
@property(retain) NSArray *folders; // @synthesize folders=_folders;
@property(retain) FolderInfo *currentFolder; // @synthesize currentFolder=_currentFolder;
@property int folderType; // @synthesize folderType=_folderType;
@property(retain) NSMutableArray *arrayAll; // @synthesize arrayAll=_arrayAll;
@property(retain) QMSearchHeaderView *collectionHederView; // @synthesize collectionHederView=_collectionHederView;
@property(retain) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) id <MasterVCDelegate> jumpdelegate; // @synthesize jumpdelegate=_jumpdelegate;
@property(nonatomic) _Bool hasNoNetBanner; // @synthesize hasNoNetBanner=_hasNoNetBanner;
- (void).cxx_destruct;
- (void)guessULikeToExpose;
- (void)deselectSettedCell;
- (void)resetSelectIndex;
- (void)deselectCollectionView;
- (void)jumpToDefault;
- (void)onTouchUpInsideUserHeader:(id)arg1;
- (void)showWordingTip;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)registerForceTouch;
- (void)onSilentUserRecommendViewCancelButtonClicked:(id)arg1 itemIndex:(long long)arg2;
- (void)onSilentUserRecommendViewConfirmButtonClicked:(id)arg1 itemIndex:(long long)arg2;
- (void)hideSilentUserRecommendView;
- (void)showSilentUserRecommendView:(long long)arg1;
- (void)onNoNetBannerCloseButtonClicked;
- (void)bannerViewImageDidLoaded:(id)arg1;
- (void)bannerViewContentDataIsUpdated:(id)arg1;
- (void)bannerViewCloseBtnTapped:(id)arg1;
- (void)hideBannerView:(_Bool)arg1;
- (void)showBannerView:(id)arg1;
- (void)cpdAdViewClicked:(id)arg1 adItem:(id)arg2;
- (void)showIconAd:(id)arg1 item:(id)arg2;
- (void)onImagetWithInfo:(id)arg1 Image:(id)arg2;
- (void)loadCPDAdItem;
- (void)onNotifyGreenDiamondAdPrepared:(id)arg1;
- (void)didLeaveScrollerVC;
- (void)didEntranceScrollerVC;
- (void)jumpToRecognize;
- (void)onQMSearchViewRecognizeButtonClicked:(id)arg1;
- (void)onQMSearchViewDidSelected:(id)arg1;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionViewDidClickedAtIndexPath:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)countNumberOfSections:(id)arg1;
- (long long)sectionTypeOfSection:(long long)arg1;
- (void)jumpToMoreFoldersWithCheckCanAutoLogin:(id)arg1;
- (void)jumpToMoreFoldersWithOutCheckCanAutoLogin;
- (void)deleteCollectedFolder:(id)arg1;
- (void)jumpToAlbumIndexView:(id)arg1;
- (void)jumpToCreateNewFolder;
- (void)jumpTpCreateFolder;
- (id)cellForMoreFolder:(id)arg1 atIndexPath:(id)arg2;
- (id)cellForAllFolder:(id)arg1 atIndexPath:(id)arg2 title:(id)arg3 folderCount:(long long)arg4 hideRedPoint:(_Bool)arg5;
- (id)cellForAlbums:(id)arg1 atIndexPath:(id)arg2 albumFolders:(id)arg3;
- (id)cellForAddAlbumFolder:(id)arg1 atIndexPath:(id)arg2;
- (id)createFolderCell:(id)arg1 atIndexPath:(id)arg2;
- (id)cellForDigitalAlbum:(id)arg1 atIndexPath:(id)arg2;
- (id)createDigitalFolderCell:(id)arg1 atIndexPath:(id)arg2;
- (void)updateFolderImage:(id)arg1 image:(id)arg2;
- (id)createGuessiLikeCell:(id)arg1 atIndexPath:(id)arg2;
- (void)onTouchUpInsideUserListen;
- (void)onTouchUpInsideBuy;
- (void)refreshUserListenTime;
- (void)addUserActivityClickStat;
- (void)addUserActivityTipClickStat;
- (void)addUserActivityExposureStat;
- (void)jumpToActivityPage;
- (void)didClickedTipsView:(id)arg1;
- (void)wordingViewWillRemoved:(id)arg1;
- (void)showActivityTip:(id)arg1 expireTime:(int)arg2;
- (void)clearActivityViews;
- (void)actuallyShowActivityViews;
- (void)tryShowActivityViews;
- (void)onNotifyGetUserActivityInfo:(id)arg1;
- (void)showUserListenTips;
- (void)setCurDayAndListenTime;
- (void)updateUserListenTime:(int)arg1;
- (id)createUserInfoCell:(id)arg1 atIndexPath:(id)arg2;
- (id)createLocalSectionCell:(id)arg1 atIndexPath:(id)arg2;
- (id)createHeaderSectionCell:(id)arg1 atIndexPath:(id)arg2;
- (void)loadDigitalAlbumData:(_Bool)arg1;
- (void)makeList;
- (id)currentFolders;
- (long long)getMyDigitalAlbumNumberOfRow;
- (long long)getMyFolderNumberOfRow;
- (void)reloadSections;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)reloadDownloadCell:(_Bool)arg1;
- (void)updateAllSongCell;
- (int)loveGroupIndexByAddToLoveType:(long long)arg1;
- (id)indexPathByVCTAG:(long long)arg1;
- (void)navigateToLocalSectionVC:(long long)arg1 index:(id)arg2;
- (void)navigateToLocalSectionVC:(long long)arg1;
- (void)onTouchUpInsideLocalSectionCell:(id)arg1 index:(id)arg2;
- (id)formatCountNumber:(long long)arg1;
- (double)getSeperateLineWidth;
- (long long)songCountByListTag:(int)arg1;
- (_Bool)getShowDownloadHistoryCount;
- (id)subTitleForDownloaded;
- (id)subtitleByTag:(long long)arg1 cell:(id)arg2;
- (_Bool)_shouldShowRedPointForAllSongs;
- (_Bool)isRedPointHiddenByTag:(long long)arg1;
- (id)localSectionIndexForTag:(long long)arg1;
- (void)loadThreeButtonDatas;
- (void)reloadLocalSectionData;
- (void)onNotifyListenTimeIncreased:(id)arg1;
- (void)showNoNetBanner;
- (void)delayCheckToShowNoNetBanner;
- (void)onNotifyNetReachabilityChanged:(id)arg1;
- (void)onNotifyUserLanguageChanged:(id)arg1;
- (void)onNotifyConcisePattenOn:(id)arg1;
- (void)onNotifyUserButDigitalAlbum:(id)arg1;
- (void)onNotifyNeedShowSilentUserRecommend:(id)arg1;
- (void)onNotifyGetSilentUserRecommendInfo:(id)arg1;
- (void)onNotifySystemFolderRedpointReasonGone:(id)arg1;
- (void)onNotifyUserFolderRedpointReasonGone:(id)arg1;
- (_Bool)shouldReloadMVCell;
- (void)updateSubTitleForTag:(long long)arg1 updateRedPoint:(_Bool)arg2;
- (void)onNotifyUpdateNumber:(id)arg1;
- (long long)tagByPosition:(int)arg1;
- (void)onNotifyUpdateMVDownloadCell:(id)arg1;
- (void)onNotifyRefreshMVitem:(id)arg1;
- (void)onNotifyCollectToILikeMessageChanged:(id)arg1;
- (void)onNotifyNewTipUpdate:(id)arg1;
- (void)onNotifyLoginFailed:(id)arg1;
- (void)onNotifyLogout:(id)arg1;
- (void)loadUserInfoCellProcess;
- (void)onNotifyFolderPictureChanged:(id)arg1;
- (void)onNotifyGetUserInfoSuccess:(id)arg1;
- (void)onNotifyFolderSongDataSaved:(id)arg1;
- (void)onNotifyUpdateCloudFolderLocalSonngsCount:(id)arg1;
- (void)onNotifyFolderDataSaved:(id)arg1;
- (void)onNotifyHideOrShowGuessULike:(id)arg1;
- (_Bool)existIndexPath:(id)arg1;
- (void)reloadIndexPathes:(id)arg1;
- (void)reloadCollectionViewIndexPaths:(id)arg1;
- (void)reloadFolderSection;
- (void)addNotifications;
- (void)registerCollectionCell;
- (void)createCollectionView;
- (void)didReceiveMemoryWarning;
- (void)onColorStyleChanged;
- (void)viewDidPop;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)reLayout:(long long)arg1;
- (struct CGRect)reFrame;
- (int)headerHight;
- (_Bool)isNeedAddBottomLine;
- (int)vcType;
- (void)loadView;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

