//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSString;

@interface NetGetNumberProtocol : ProtocolBaseJason
{
    NSString *_phoneNumber;
}

@property(retain) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
- (void).cxx_destruct;
- (_Bool)containReturnCode;
- (void)onParseJasonData:(id)arg1;
- (_Bool)needsUnzip:(id)arg1;
- (_Bool)isDataBeginWithFiveZero;
- (int)cid;
- (void)netBase:(id)arg1 didFailWithError:(long long)arg2;
- (id)getUrl;

@end

