//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (DDData)
- (id)base64Decoded;
- (id)base64Encoded;
- (id)hexStringValue;
- (id)sha1Digest;
- (id)md5Digest;
@end

