//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSError.h>

@interface NSError (BMWAppKit)
+ (id)errorWithFrameworkCode:(long long)arg1 description:(id)arg2 underlyingError:(id)arg3;
+ (id)errorWithFrameworkCode:(long long)arg1 description:(id)arg2;
@end

