//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (NSStringHTMLAdditions)
- (id)stringByUnescapingFromHTML;
- (id)stringByEscapingForAsciiHTML;
- (id)stringByEscapingForHTML;
- (id)stringByEscapingHTMLUsingTable:(CDStruct_815e4876 *)arg1 ofSize:(unsigned long long)arg2 escapingUnicode:(_Bool)arg3;
@end

