//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (version)
- (int)isBiger:(id)arg1;
- (_Bool)isEqualToVersion:(id)arg1;
- (_Bool)isLessEqualToVersion:(id)arg1;
- (_Bool)isLessThanVersion:(id)arg1;
- (_Bool)isBiggerEqualToVersion:(id)arg1;
- (_Bool)isBiggerThanVersion:(id)arg1;
- (long long)_compareDotVersion:(id)arg1;
@end

