//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (UrlEncode)
+ (id)urlEncodeBase64Encode:(id)arg1;
+ (id)urlDecode:(id)arg1;
- (id)URLEncodedStringWithCFStringEncoding:(unsigned int)arg1;
- (id)URLEncodedString;
@end

