//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSArray;

@interface OnlineListAIRandomProtocol : ProtocolBaseJason
{
    _Bool _isQueryConfigInfo;
    unsigned long long _type;
    long long _itemID;
    NSArray *_randomSongIDList;
    long long _timeOutSecond;
    unsigned long long _removeHistoryDenominator;
    unsigned long long _groupedDenominator;
    unsigned long long _sin;
    unsigned long long _ein;
}

@property(nonatomic) unsigned long long ein; // @synthesize ein=_ein;
@property(nonatomic) unsigned long long sin; // @synthesize sin=_sin;
@property(nonatomic) unsigned long long groupedDenominator; // @synthesize groupedDenominator=_groupedDenominator;
@property(nonatomic) unsigned long long removeHistoryDenominator; // @synthesize removeHistoryDenominator=_removeHistoryDenominator;
@property(nonatomic) long long timeOutSecond; // @synthesize timeOutSecond=_timeOutSecond;
@property(retain, nonatomic) NSArray *randomSongIDList; // @synthesize randomSongIDList=_randomSongIDList;
@property(nonatomic) long long itemID; // @synthesize itemID=_itemID;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) _Bool isQueryConfigInfo; // @synthesize isQueryConfigInfo=_isQueryConfigInfo;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getUrl;
- (int)cid;

@end

