//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ClientJceBase.h"

@class ClientJce_AllSongAlerts, SongInfo;

@interface PaidContentBlockAlert : ClientJceBase
{
    ClientJce_AllSongAlerts *_allAlerts;
    SongInfo *_alertSong;
}

+ (struct SFlexInteger)alertForPlaySong:(id)arg1 assetsType:(int)arg2 showAlert:(_Bool)arg3;
+ (struct SFlexInteger)alertForPlayGraySong:(id)arg1 assetsType:(int)arg2 vcType:(id)arg3 showMV:(_Bool)arg4;
+ (id)sharedInstance;
@property(retain, nonatomic) SongInfo *alertSong; // @synthesize alertSong=_alertSong;
@property(retain, nonatomic) ClientJce_AllSongAlerts *allAlerts; // @synthesize allAlerts=_allAlerts;
- (void).cxx_destruct;
- (id)getSavePath;
- (id)getDownloadPayContentMessage:(long long)arg1 selectedCount:(long long)arg2;
- (void)updateAllAlertInfos;
- (void)showWebViewController:(id)arg1;
- (void)unifyPayFromVC:(id)arg1 source:(id)arg2 aid:(id)arg3 alertViewInfo:(id)arg4;
- (void)showAlertTypeOld:(id)arg1 jumpUrl:(id)arg2 description:(id)arg3;
- (void)showAlert:(id)arg1;
- (id)cutSingerNameToFitButton:(id)arg1 singerName:(id)arg2;
- (void)delayShowAlertById:(id)arg1;
- (id)getPaySongNoteById:(long long)arg1;
- (_Bool)showAlertById:(long long)arg1 type:(long long)arg2 forSong:(id)arg3;
- (id)init;

@end

