//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class ListBase;

@interface ParticularIndexSingerProtocol : ProtocolBaseJason
{
    int retState;
    ListBase *list;
}

@property(nonatomic) __weak ListBase *list; // @synthesize list;
@property(nonatomic) int retState; // @synthesize retState;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (_Bool)canReportError;
- (_Bool)containReturnCode;
- (id)getUrl;
- (int)cid;
- (id)init;

@end

