//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface PatchInfo : NSObject <NSCoding>
{
    NSString *_sdkVersion;
    NSString *_patchVersion;
    NSString *_patchMD5;
}

+ (id)initPatchInfo;
@property(retain, nonatomic) NSString *patchMD5; // @synthesize patchMD5=_patchMD5;
@property(retain, nonatomic) NSString *patchVersion; // @synthesize patchVersion=_patchVersion;
@property(retain, nonatomic) NSString *sdkVersion; // @synthesize sdkVersion=_sdkVersion;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

