//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSURLConnectionDataDelegate-Protocol.h"

@class ASIHTTPRequest, NSDate, NSString, NSTimer, SingleHourglass;

@interface PersistentConnection : NSObject <NSURLConnectionDataDelegate>
{
    ASIHTTPRequest *pURLConnection;
    int status;
    float tryTime;
    NSDate *lastReceiveDate;
    NSTimer *timer;
    int heartbeat;
    _Bool usePool;
    int _connectedCount;
    _Bool _expectHelloMessage;
    NSString *_serverIpAddress;
    NSString *_serverHostAndPort;
    unsigned long long _lastSeqId;
    SingleHourglass *_shakeSingleHourglass;
    unsigned long long _uin;
}

@property(nonatomic) unsigned long long uin; // @synthesize uin=_uin;
@property(retain, nonatomic) SingleHourglass *shakeSingleHourglass; // @synthesize shakeSingleHourglass=_shakeSingleHourglass;
@property(nonatomic) unsigned long long lastSeqId; // @synthesize lastSeqId=_lastSeqId;
@property(retain, nonatomic) NSString *serverHostAndPort; // @synthesize serverHostAndPort=_serverHostAndPort;
@property(nonatomic) _Bool expectHelloMessage; // @synthesize expectHelloMessage=_expectHelloMessage;
@property(retain, nonatomic) NSString *serverIpAddress; // @synthesize serverIpAddress=_serverIpAddress;
@property(nonatomic) float tryTime; // @synthesize tryTime;
@property(nonatomic) int status; // @synthesize status;
@property(retain, nonatomic) ASIHTTPRequest *pURLConnection; // @synthesize pURLConnection;
- (void).cxx_destruct;
- (id)_getRandomString;
- (void)_statMsgCommand:(id)arg1 firstMsg:(id)arg2 messageCount:(unsigned long long)arg3 otherMessageId:(id)arg4 lastSeqID:(unsigned long long)arg5;
- (void)_statHelloCommand:(id)arg1;
- (_Bool)_isCommandContainsMsg:(id)arg1;
- (_Bool)_isHelloMessage:(id)arg1;
- (id)_parseMsgContent:(id)arg1;
- (void)_onConnectSuccessed;
- (void)onLogOut;
- (void)dealloc;
- (void)parseDictMsg:(id)arg1;
- (void)dispatchSingleCommand:(id)arg1;
- (void)dispatchCommand:(id)arg1;
- (void)processJasonData:(id)arg1;
- (void)requestFailed:(id)arg1;
- (void)requestFinished:(id)arg1;
- (void)request:(id)arg1 didReceiveData:(id)arg2;
- (void)request:(id)arg1 didReceiveResponseHeaders:(id)arg2;
- (void)requestStarted:(id)arg1;
- (void)checkConnection;
- (void)resetTryTime;
- (void)plusTryTime;
- (void)start;
- (void)stop;
- (void)startAfterNetAvailable;
- (void)netAvailable:(id)arg1;
- (id)initWithUin:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

