//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FavSongCell.h"

@class UIImageView, UILabel;

@interface PlayCountSongCell : FavSongCell
{
    UIImageView *_listenImageView;
    UILabel *_playCountLabel;
}

@property(retain, nonatomic) UILabel *playCountLabel; // @synthesize playCountLabel=_playCountLabel;
@property(retain, nonatomic) UIImageView *listenImageView; // @synthesize listenImageView=_listenImageView;
- (void).cxx_destruct;
- (void)onNotifySkinSettingChange:(id)arg1;
- (void)setPlayCount:(unsigned long long)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

