//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MultiFilterConnect.h"

@class GlowCenter;

@interface PortraitBeauty : MultiFilterConnect
{
    int pflag;
    GlowCenter *glow;
    _Bool _beauty;
}

@property(nonatomic) _Bool beauty; // @synthesize beauty=_beauty;
- (void).cxx_destruct;
- (void)setGPUFilterSubImageInfo:(id)arg1;
- (void)NewFilter;
- (id)init:(int)arg1 scale:(float)arg2;

@end

