//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSMutableArray, SongInfo;

@interface PostersPreViewListProtocol : ProtocolBaseJason
{
    SongInfo *_songinfo;
    NSMutableArray *_arrayData;
}

@property(retain, nonatomic) NSMutableArray *arrayData; // @synthesize arrayData=_arrayData;
@property(retain, nonatomic) SongInfo *songinfo; // @synthesize songinfo=_songinfo;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (_Bool)needsUnzip:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getUrl;
- (int)cid;

@end

