//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BasePPTVC.h"

#import "TouchUIImageDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UIPageControl, UIScrollView;

@interface PPTVC : BasePPTVC <UIScrollViewDelegate, TouchUIImageDelegate>
{
    _Bool _pageControlIsChangingPage;
    _Bool _changedStatusBarFrame;
    NSMutableArray *_scrollViewPageViews;
    long long _currentPage;
    UIScrollView *_pagingScrollView;
    UIPageControl *_pageControl;
}

@property(nonatomic) _Bool changedStatusBarFrame; // @synthesize changedStatusBarFrame=_changedStatusBarFrame;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) UIScrollView *pagingScrollView; // @synthesize pagingScrollView=_pagingScrollView;
@property(nonatomic) _Bool pageControlIsChangingPage; // @synthesize pageControlIsChangingPage=_pageControlIsChangingPage;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(retain, nonatomic) NSMutableArray *scrollViewPageViews; // @synthesize scrollViewPageViews=_scrollViewPageViews;
- (void).cxx_destruct;
- (void)changePage:(id)arg1;
- (void)imageTouch:(id)arg1 withEvent:(id)arg2 whichView:(id)arg3;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)addButtonByImageName:(id)arg1 selectImageName:(id)arg2 frame:(struct CGRect)arg3 toView:(id)arg4 selector:(SEL)arg5 voiceOver:(id)arg6 hidden:(_Bool)arg7;
- (void)createPageControl;
- (void)createPagingScrollView;
- (void)finishPPTVC;
- (void)fadeBgAndFinishSelf;
- (void)onTouchUpInside:(id)arg1;
- (void)reLayoutTo:(int)arg1;
- (void)reLayout:(long long)arg1;
- (void)doHandlePushComming:(id)arg1;
- (void)applicationDidEnterBackground;
- (id)PPTImageName:(int)arg1;
- (double)pageControlTop;
- (double)pageControlHeight;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)createPageViewAtIndex:(long long)arg1;
- (id)createDefaultPageViewWithFrame:(struct CGRect)arg1;
- (double)viewHeight;
- (double)viewTopInset;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

