//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

#import "ProtocolHostDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString;

@interface PreferencesConfVC : SkinViewController <UITableViewDataSource, UITableViewDelegate, ProtocolHostDelegate>
{
    _Bool _isFriendListenPrivacyChanged;
    _Bool _isShowFriendListenPrivacySwitch;
    long long _qqAssetImportIndex;
    long long _todayRowIndex;
    long long _qZoneBackgroundMusicRowIndex;
    long long _shareToWeiboRowindex;
    long long _notificationRowIndex;
    long long _privateSettingRowIndex;
    long long _fluencyModeRowIndex;
    long long _multiLanguageRowIndex;
}

@property(nonatomic) long long multiLanguageRowIndex; // @synthesize multiLanguageRowIndex=_multiLanguageRowIndex;
@property(nonatomic) long long fluencyModeRowIndex; // @synthesize fluencyModeRowIndex=_fluencyModeRowIndex;
@property(nonatomic) long long privateSettingRowIndex; // @synthesize privateSettingRowIndex=_privateSettingRowIndex;
@property(nonatomic) long long notificationRowIndex; // @synthesize notificationRowIndex=_notificationRowIndex;
@property(nonatomic) long long shareToWeiboRowindex; // @synthesize shareToWeiboRowindex=_shareToWeiboRowindex;
@property(nonatomic) long long qZoneBackgroundMusicRowIndex; // @synthesize qZoneBackgroundMusicRowIndex=_qZoneBackgroundMusicRowIndex;
@property(nonatomic) long long todayRowIndex; // @synthesize todayRowIndex=_todayRowIndex;
@property(nonatomic) long long qqAssetImportIndex; // @synthesize qqAssetImportIndex=_qqAssetImportIndex;
@property(nonatomic) _Bool isShowFriendListenPrivacySwitch; // @synthesize isShowFriendListenPrivacySwitch=_isShowFriendListenPrivacySwitch;
@property(nonatomic) _Bool isFriendListenPrivacyChanged; // @synthesize isFriendListenPrivacyChanged=_isFriendListenPrivacyChanged;
- (void)cellForRowForThirdSection:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)cellForRowForSecondSection:(id)arg1 cell:(id)arg2 cellForRowAtIndexPath:(id)arg3;
- (id)detailLabelTextForAlbumModeSettingCell;
- (id)cellForRowForFirstSection:(id)arg1 cell:(id)arg2 cellForRowAtIndexPath:(id)arg3;
- (void)delayFresh;
- (void)onNotifyNetStateChange:(id)arg1;
- (void)onNotifyNoWifiAlertSettingChange:(id)arg1;
- (void)onNotifyDownloadWhileCahcingChange:(id)arg1;
- (void)onNotifyDownloadQulityChange:(id)arg1;
- (void)downloadSwitchChanged:(id)arg1;
- (void)offlineDownloadModeSettingChanged;
- (void)changeIndex;
- (void)reloadSection2;
- (void)reloadSection0;
- (void)onNotifyUserLanguageChanged:(id)arg1;
- (void)_onAlbumImageCanRotateSwitch:(id)arg1;
- (void)_onPlayingViewAndMiniPlayerSwitch:(id)arg1;
- (void)_onUseSystemFontSwitch:(id)arg1;
- (void)_enableShakeFunctionSwitchChanged:(id)arg1;
- (void)_onAlertSwitchChanged:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)resetRowIndexes;
- (void)dealloc;
- (void)viewDidPop;
- (int)vcType;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

