//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ParsedResult.h"

@class NSString;

@interface ProductParsedResult : ParsedResult
{
    NSString *productID;
    NSString *normalizedProductID;
}

@property(copy, nonatomic) NSString *normalizedProductID; // @synthesize normalizedProductID;
@property(copy, nonatomic) NSString *productID; // @synthesize productID;
- (id)stringForDisplay;
- (id)initWithProductID:(id)arg1 normalizedProductID:(id)arg2;

@end

