//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QMBaseModel.h"

@class NSString;

@interface ProfileBgMusic : QMBaseModel
{
    _Bool _isHasBgMusic;
    NSString *_songName;
    NSString *_jumpUrl;
}

+ (id)translateFromJsonData:(id)arg1;
@property(retain, nonatomic) NSString *jumpUrl; // @synthesize jumpUrl=_jumpUrl;
@property(retain, nonatomic) NSString *songName; // @synthesize songName=_songName;
@property(nonatomic) _Bool isHasBgMusic; // @synthesize isHasBgMusic=_isHasBgMusic;
- (void).cxx_destruct;

@end

