//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ProfileHeadIconDelegate-Protocol.h"

@class NSString, ProfileHeadIcon, ProfileNickIdentifyView, QMFollowOrCancelView;
@protocol ProfileHeadViewDelegate;

@interface ProfileHeadView_V2 : UIView <ProfileHeadIconDelegate>
{
    ProfileHeadIcon *_headIcon;
    ProfileNickIdentifyView *_idView;
    QMFollowOrCancelView *_followView;
    id <ProfileHeadViewDelegate> _delegate;
}

@property(nonatomic) __weak id <ProfileHeadViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) QMFollowOrCancelView *followView; // @synthesize followView=_followView;
@property(retain, nonatomic) ProfileNickIdentifyView *idView; // @synthesize idView=_idView;
@property(retain, nonatomic) ProfileHeadIcon *headIcon; // @synthesize headIcon=_headIcon;
- (void).cxx_destruct;
- (void)imageChanged:(id)arg1;
- (void)headViewClick;
- (void)setIsGuest:(_Bool)arg1;
- (void)buildSubView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

