//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QMBaseModel.h"

@class NSArray, NSString;

@interface ProfileBackPic : QMBaseModel
{
    _Bool _isHasBgPic;
    _Bool _isCustomPic;
    NSArray *_backpicUrls;
    NSString *_minibarpicUrl;
    NSString *_bgcolor;
    NSString *_bgTilte;
}

+ (id)translateFromJsonData:(id)arg1;
@property(retain, nonatomic) NSString *bgTilte; // @synthesize bgTilte=_bgTilte;
@property(retain, nonatomic) NSString *bgcolor; // @synthesize bgcolor=_bgcolor;
@property(retain, nonatomic) NSString *minibarpicUrl; // @synthesize minibarpicUrl=_minibarpicUrl;
@property(nonatomic) _Bool isCustomPic; // @synthesize isCustomPic=_isCustomPic;
@property(retain, nonatomic) NSArray *backpicUrls; // @synthesize backpicUrls=_backpicUrls;
@property(nonatomic) _Bool isHasBgPic; // @synthesize isHasBgPic=_isHasBgPic;
- (void).cxx_destruct;

@end

