//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

@class NSMutableArray;

@interface ProfileVisitorViewController : SkinViewController
{
    unsigned long long _visitUin;
    NSMutableArray *_visitorList;
}

@property(retain, nonatomic) NSMutableArray *visitorList; // @synthesize visitorList=_visitorList;
@property(nonatomic) unsigned long long visitUin; // @synthesize visitUin=_visitUin;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)deleteVisitorRecord:(id)arg1;
- (void)visitorListDataDidUpdate:(id)arg1;
- (id)initWithUin:(unsigned long long)arg1;
- (id)emptyViewBgText;
- (void)reFresh;
- (void)viewDidLoad;

@end

