//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProfileCollectionViewCell.h"

@class RelationSubControl;

@interface ProfileRelationCollectionViewCell : ProfileCollectionViewCell
{
    RelationSubControl *_fanControl;
    RelationSubControl *_followControl;
}

@property(retain, nonatomic) RelationSubControl *followControl; // @synthesize followControl=_followControl;
@property(retain, nonatomic) RelationSubControl *fanControl; // @synthesize fanControl=_fanControl;
- (void).cxx_destruct;
- (void)setCellBgColor:(id)arg1 bgAlpha:(double)arg2;
- (void)updateByItem:(id)arg1 isGuest:(_Bool)arg2;
- (void)buildSubView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

