//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProfileCollectionViewCell.h"

@class UIImageView, UILabel;

@interface ProfileNormalCollectionViewCell : ProfileCollectionViewCell
{
    UILabel *_titleLabel3;
    UIImageView *_bgImageView;
    UILabel *_titleLabel4;
}

@property(retain, nonatomic) UILabel *titleLabel4; // @synthesize titleLabel4=_titleLabel4;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(retain, nonatomic) UILabel *titleLabel3; // @synthesize titleLabel3=_titleLabel3;
- (void).cxx_destruct;
- (void)updateByItem:(id)arg1 isGuest:(_Bool)arg2;
- (void)buildSubView;

@end

