//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

#import "ProfileBgPicSettingDelegate-Protocol.h"
#import "ProtocolHostDelegate-Protocol.h"

@class NSArray, NSString;

@interface ProfileBgImageViewController : SkinViewController <ProtocolHostDelegate, ProfileBgPicSettingDelegate>
{
    _Bool _isUseCustomPic;
    NSArray *_bgPicItems;
}

@property(nonatomic) _Bool isUseCustomPic; // @synthesize isUseCustomPic=_isUseCustomPic;
@property(retain, nonatomic) NSArray *bgPicItems; // @synthesize bgPicItems=_bgPicItems;
- (void).cxx_destruct;
- (void)profileBgpicSetting:(id)arg1;
- (void)hostCallBackWithWorkProtocol:(id)arg1 protocolError:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)updateBgPicItemsByPicId:(unsigned long long)arg1;
- (void)settingCustomPicSuccess;
- (void)reFresh;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

