//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSString, UICollectionView;

@interface QMAlbumModeSettingVC : SkinViewController <UICollectionViewDataSource, UICollectionViewDelegate>
{
    UICollectionView *_collectionView;
    long long _albumModeIndexCDRotate;
    long long _albumModeIndexCDStatic;
    long long _albumModeIndexSquare;
    long long _albumModeNumberCount;
}

@property(nonatomic) long long albumModeNumberCount; // @synthesize albumModeNumberCount=_albumModeNumberCount;
@property(nonatomic) long long albumModeIndexSquare; // @synthesize albumModeIndexSquare=_albumModeIndexSquare;
@property(nonatomic) long long albumModeIndexCDStatic; // @synthesize albumModeIndexCDStatic=_albumModeIndexCDStatic;
@property(nonatomic) long long albumModeIndexCDRotate; // @synthesize albumModeIndexCDRotate=_albumModeIndexCDRotate;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (void)updateAutoRotate:(_Bool)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (int)vcType;
- (id)currentModeIndexPath;
- (void)buildMainView;
- (void)calculateIndexAndCount;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

