//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSNumber, UILabel;

@interface QMCloudBtn : UIButton
{
    unsigned long long _cloudState;
    NSNumber *_cloudCount;
    UILabel *_countLabel;
}

@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) NSNumber *cloudCount; // @synthesize cloudCount=_cloudCount;
@property(nonatomic) unsigned long long cloudState; // @synthesize cloudState=_cloudState;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1;
- (void)updateViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

