//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@class NSString;

@interface QMFadeImageView : UIImageView
{
    NSString *_imgIdentifier;
}

@property(retain, nonatomic) NSString *imgIdentifier; // @synthesize imgIdentifier=_imgIdentifier;
- (void).cxx_destruct;
- (void)setImage:(id)arg1 animated:(_Bool)arg2;
- (void)setImage:(id)arg1;

@end

