//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FMCDisplayType, NSArray, NSMutableArray, NSNumber, NSString;

@interface QMFordManager : NSObject
{
    _Bool _isConnected;
    _Bool _isFordMaker;
    _Bool _bNeedResumed;
    _Bool _isGraphicsSupported;
    _Bool _UIReady;
    _Bool _coverArtToDisplay;
    NSMutableArray *_songListArray;
    FMCDisplayType *_displayType;
    NSArray *_textFields;
    NSArray *_templatesAvailable;
    NSNumber *_appIconPutFileID;
    NSString *_coverArtHandle;
    NSNumber *_coverArtCorId;
    unsigned long long _lastUploadImageSongId;
}

+ (id)shareInstance;
@property(nonatomic) unsigned long long lastUploadImageSongId; // @synthesize lastUploadImageSongId=_lastUploadImageSongId;
@property(retain, nonatomic) NSNumber *coverArtCorId; // @synthesize coverArtCorId=_coverArtCorId;
@property(nonatomic) _Bool coverArtToDisplay; // @synthesize coverArtToDisplay=_coverArtToDisplay;
@property(retain, nonatomic) NSString *coverArtHandle; // @synthesize coverArtHandle=_coverArtHandle;
@property(nonatomic) _Bool UIReady; // @synthesize UIReady=_UIReady;
@property(retain, nonatomic) NSNumber *appIconPutFileID; // @synthesize appIconPutFileID=_appIconPutFileID;
@property(retain, nonatomic) NSArray *templatesAvailable; // @synthesize templatesAvailable=_templatesAvailable;
@property(retain, nonatomic) NSArray *textFields; // @synthesize textFields=_textFields;
@property(retain, nonatomic) FMCDisplayType *displayType; // @synthesize displayType=_displayType;
@property(nonatomic) _Bool isGraphicsSupported; // @synthesize isGraphicsSupported=_isGraphicsSupported;
@property(nonatomic) _Bool bNeedResumed; // @synthesize bNeedResumed=_bNeedResumed;
@property(retain, nonatomic) NSMutableArray *songListArray; // @synthesize songListArray=_songListArray;
@property(nonatomic) _Bool isFordMaker; // @synthesize isFordMaker=_isFordMaker;
@property(nonatomic) _Bool isConnected; // @synthesize isConnected=_isConnected;
- (void).cxx_destruct;
- (void)alert:(id)arg1;
- (void)onNotifyPlayingSongChange:(id)arg1;
- (void)showAlertMsg:(id)arg1;
- (void)_registerHelpCmd;
- (void)_subSubscribeHardBtn;
- (void)_playRadio;
- (void)_prepareChoiceSet;
- (void)showSongList:(id)arg1;
- (id)allSoftButtons;
- (id)allSoftButtonCommandsNoGraphic;
- (id)allSoftButtonCommandsGraphic;
- (void)_registerAllCmd;
- (id)allSoundCmds;
- (void)receivedRequestResult:(id)arg1;
- (void)fordChoiceCommand:(id)arg1;
- (void)setupAppIcon;
- (void)onAppInterfaceResponse:(id)arg1;
- (void)onPutFileResponse:(id)arg1;
- (void)doFordCmdMsg:(int)arg1;
- (void)fordSoftButtonCommand:(id)arg1;
- (void)fordVoiceCommand:(id)arg1;
- (void)thirdStepInit;
- (void)secondStepInit;
- (void)firstStepInit;
- (void)fordConnected:(id)arg1;
- (void)audioAviablel;
- (void)audioNotAviablel;
- (id)timeIntervalToStartTime:(double)arg1;
- (void)pauseProgressBar;
- (void)updateProgressBar;
- (void)showMsgWithStr1:(id)arg1 AndStr2:(id)arg2 AndMideaTrack:(id)arg3 NeedTimer:(_Bool)arg4;
- (void)uploadAlbumImage:(id)arg1;
- (void)refreshNowPlayingInfo;
- (void)refreshPlayState;
- (void)stop;
- (void)startUp;

@end

