//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@interface QMForwardNoneDraggingTouchesScrollView : UIScrollView
{
}

- (void)setContentSizeWithoutNotifyingDelegate:(struct CGSize)arg1;
- (void)setContentInsetWithoutNotifyingDelegate:(struct UIEdgeInsets)arg1;
- (void)setContentOffsetWithoutNotifyingDelegate:(struct CGPoint)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;

@end

