//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSMutableArray, NSString;

@interface QMGlobalCommentList : NSObject
{
    _Bool _hasMoreHotComment;
    _Bool _hasCheckedHotComment;
    unsigned long long _muscritCount;
    unsigned long long _hotCommentCount;
    double _lastScore;
    NSArray *_selfMuscritItemArray;
    NSArray *_zhihuMuscitItemArray;
    NSString *_selfMoreUrl;
    NSString *_zhihuMoreUrl;
    NSArray *_doubanMuscitItemArray;
    NSString *_doubanMoreUrl;
    NSMutableArray *_hotCommentItemArray;
    unsigned long long _topId;
}

@property(nonatomic) unsigned long long topId; // @synthesize topId=_topId;
@property(nonatomic) _Bool hasCheckedHotComment; // @synthesize hasCheckedHotComment=_hasCheckedHotComment;
@property(retain, nonatomic) NSMutableArray *hotCommentItemArray; // @synthesize hotCommentItemArray=_hotCommentItemArray;
@property(retain, nonatomic) NSString *doubanMoreUrl; // @synthesize doubanMoreUrl=_doubanMoreUrl;
@property(retain, nonatomic) NSArray *doubanMuscitItemArray; // @synthesize doubanMuscitItemArray=_doubanMuscitItemArray;
@property(retain, nonatomic) NSString *zhihuMoreUrl; // @synthesize zhihuMoreUrl=_zhihuMoreUrl;
@property(retain, nonatomic) NSString *selfMoreUrl; // @synthesize selfMoreUrl=_selfMoreUrl;
@property(retain, nonatomic) NSArray *zhihuMuscitItemArray; // @synthesize zhihuMuscitItemArray=_zhihuMuscitItemArray;
@property(retain, nonatomic) NSArray *selfMuscritItemArray; // @synthesize selfMuscritItemArray=_selfMuscritItemArray;
@property(nonatomic) _Bool hasMoreHotComment; // @synthesize hasMoreHotComment=_hasMoreHotComment;
@property(nonatomic) double lastScore; // @synthesize lastScore=_lastScore;
@property(nonatomic) unsigned long long hotCommentCount; // @synthesize hotCommentCount=_hotCommentCount;
@property(nonatomic) unsigned long long muscritCount; // @synthesize muscritCount=_muscritCount;
- (void).cxx_destruct;

@end

