//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QQMusicCell.h"

@class QMLabel;

@interface QMGlobalCommentHeaderCell : QQMusicCell
{
    QMLabel *_titleLabel;
    QMLabel *_countLabel;
}

@property(retain, nonatomic) QMLabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) QMLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (double)caculateTitleWidth:(id)arg1;
- (void)setTitle:(id)arg1 count:(unsigned long long)arg2;
- (void)buildSubViews;
- (void)prepareForReuse;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

