//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface QMLogoItem : NSObject
{
    NSString *_strBlack;
    NSString *_strWhite;
    long long _nLogoId;
}

@property(nonatomic) long long nLogoId; // @synthesize nLogoId=_nLogoId;
@property(retain, nonatomic) NSString *strWhite; // @synthesize strWhite=_strWhite;
@property(retain, nonatomic) NSString *strBlack; // @synthesize strBlack=_strBlack;
- (void).cxx_destruct;

@end

