//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ProcessViewDelegate-Protocol.h"
#import "QMChorusSliderDelegate-Protocol.h"
#import "QMMiniPlayerSongInfoViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class CAGradientLayer, NSString, ProgressRing, QMChorusSlider, QMMiniPlayerSongInfoView, UIButton, UIImageView, UILabel, UIScrollView;
@protocol QMMiniPlayerViewDelegate;

@interface QMMiniPlayerView : UIView <QMChorusSliderDelegate, ProcessViewDelegate, UIScrollViewDelegate, QMMiniPlayerSongInfoViewDelegate>
{
    double animationPauseTime;
    _Bool isPlayedRadio;
    _Bool _isSliderUse;
    _Bool _isSliderUsing;
    _Bool _canNotDel;
    _Bool _canScrollSongInfoView;
    _Bool _hasShowedTips;
    _Bool _shouldUpdateLyric;
    _Bool _isTipshowing;
    id <QMMiniPlayerViewDelegate> _playingDelegate;
    UIButton *_playButton;
    UIButton *_playPreButton;
    UIButton *_playNextButton;
    UIScrollView *_songInfoBaseScrollView;
    QMMiniPlayerSongInfoView *_songInfoView;
    CAGradientLayer *_gradientMaskLayer;
    QMChorusSlider *_curPlayProgressSlider;
    UIButton *_myFavorButton;
    UIButton *_downLoadButton;
    UIImageView *_seperateView;
    UIButton *_moreButton;
    UIButton *_songListButton;
    UIButton *_deleteButton;
    UIImageView *_topSeperateView;
    UIButton *_ciButton;
    ProgressRing *_progressRing;
    UILabel *_leftTip;
    UILabel *_rightTip;
    NSString *_fullTime;
    NSString *_remainTime;
    UILabel *_timeLable;
    QMMiniPlayerSongInfoView *_emptySongInfo;
}

@property(retain, nonatomic) QMMiniPlayerSongInfoView *emptySongInfo; // @synthesize emptySongInfo=_emptySongInfo;
@property(retain, nonatomic) UILabel *timeLable; // @synthesize timeLable=_timeLable;
@property(retain, nonatomic) NSString *remainTime; // @synthesize remainTime=_remainTime;
@property(retain, nonatomic) NSString *fullTime; // @synthesize fullTime=_fullTime;
@property(nonatomic) _Bool isTipshowing; // @synthesize isTipshowing=_isTipshowing;
@property(nonatomic) _Bool shouldUpdateLyric; // @synthesize shouldUpdateLyric=_shouldUpdateLyric;
@property(nonatomic) _Bool hasShowedTips; // @synthesize hasShowedTips=_hasShowedTips;
@property(nonatomic) _Bool canScrollSongInfoView; // @synthesize canScrollSongInfoView=_canScrollSongInfoView;
@property(nonatomic) _Bool canNotDel; // @synthesize canNotDel=_canNotDel;
@property(nonatomic) _Bool isSliderUsing; // @synthesize isSliderUsing=_isSliderUsing;
@property(nonatomic) _Bool isSliderUse; // @synthesize isSliderUse=_isSliderUse;
@property(retain, nonatomic) UILabel *rightTip; // @synthesize rightTip=_rightTip;
@property(retain, nonatomic) UILabel *leftTip; // @synthesize leftTip=_leftTip;
@property(retain, nonatomic) ProgressRing *progressRing; // @synthesize progressRing=_progressRing;
@property(retain, nonatomic) UIButton *ciButton; // @synthesize ciButton=_ciButton;
@property(retain, nonatomic) UIImageView *topSeperateView; // @synthesize topSeperateView=_topSeperateView;
@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(retain, nonatomic) UIButton *songListButton; // @synthesize songListButton=_songListButton;
@property(retain, nonatomic) UIButton *moreButton; // @synthesize moreButton=_moreButton;
@property(retain, nonatomic) UIImageView *seperateView; // @synthesize seperateView=_seperateView;
@property(retain, nonatomic) UIButton *downLoadButton; // @synthesize downLoadButton=_downLoadButton;
@property(retain, nonatomic) UIButton *myFavorButton; // @synthesize myFavorButton=_myFavorButton;
@property(retain, nonatomic) QMChorusSlider *curPlayProgressSlider; // @synthesize curPlayProgressSlider=_curPlayProgressSlider;
@property(retain, nonatomic) CAGradientLayer *gradientMaskLayer; // @synthesize gradientMaskLayer=_gradientMaskLayer;
@property(retain, nonatomic) QMMiniPlayerSongInfoView *songInfoView; // @synthesize songInfoView=_songInfoView;
@property(retain, nonatomic) UIScrollView *songInfoBaseScrollView; // @synthesize songInfoBaseScrollView=_songInfoBaseScrollView;
@property(retain, nonatomic) UIButton *playNextButton; // @synthesize playNextButton=_playNextButton;
@property(retain, nonatomic) UIButton *playPreButton; // @synthesize playPreButton=_playPreButton;
@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(nonatomic) id <QMMiniPlayerViewDelegate> playingDelegate; // @synthesize playingDelegate=_playingDelegate;
- (void).cxx_destruct;
- (struct CGSize)imageSizeForProcessView:(id)arg1 position:(int)arg2;
- (id)imageNameForProcessView:(id)arg1 position:(int)arg2;
- (void)resetScrollViewContentOffset;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)touchEndAction;
- (void)curPlayProgressSliderTouchCancel:(id)arg1;
- (void)curPlayProgressSliderTouchUp:(id)arg1;
- (void)curPlayProgressValueChanged:(id)arg1;
- (void)curPlayProgressSliderDrag:(id)arg1;
- (void)curPlayProgressSliderTouchDown:(id)arg1;
- (void)QMChorusSliderTapGesture:(id)arg1 location:(struct CGPoint)arg2 tapChorusPoint:(_Bool)arg3;
- (void)goToFullScreenPlay:(id)arg1;
- (id)playingSongAlbumImageView;
- (void)showPlayList:(id)arg1;
- (void)clickDeleteButton:(id)arg1;
- (void)clickMoreButton:(id)arg1;
- (void)downLoadSong:(id)arg1;
- (void)addToMyLoveOnline:(id)arg1;
- (void)playPreviousSong:(id)arg1;
- (void)playNextSong:(id)arg1;
- (void)playOrPauseButtonPressed:(id)arg1;
- (void)setEmptyView:(_Bool)arg1;
- (void)setFullTime:(id)arg1 remainTime:(id)arg2;
- (void)updatePlayAnimation:(_Bool)arg1 needBuffer:(_Bool)arg2;
- (void)updateDownLoadState:(_Bool)arg1 canDownLoad:(_Bool)arg2;
- (void)updateTime:(double)arg1 duration:(double)arg2 loading:(double)arg3 buffer:(double)arg4 starting:(double)arg5;
- (void)setSongInfoBaseScrollViewEnabled:(_Bool)arg1;
- (void)setDisplayingLyricText:(id)arg1;
- (void)resumeUpdateLyric;
- (void)setDisplayingSingerName:(id)arg1 forSeconds:(double)arg2;
- (void)setDisplayingSingerName:(id)arg1;
- (void)setCurrentSingerNameIsTips:(_Bool)arg1;
- (void)setTipsShow:(int)arg1;
- (void)setTipsHidden;
- (void)changeSongListIcon:(_Bool)arg1;
- (void)enableInSubViews:(id)arg1 enable:(_Bool)arg2 deepIn:(_Bool)arg3;
- (void)canUse:(_Bool)arg1;
- (void)onUserLanguageChanged;
- (void)onColorChange;
- (void)fillEmptyView;
- (id)applyGradientMaskView:(id)arg1;
- (void)reLayoutTo:(int)arg1;
- (void)reLayout;
- (void)buildView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

