//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "APMidasPayDelegate-Protocol.h"
#import "IAPGetProductListDelegate-Protocol.h"
#import "IAPPayDelegate-Protocol.h"
#import "ProtocolHostDelegate-Protocol.h"

@class NSString, QMProductsRequest;

@interface QMMidasManager : NSObject <IAPGetProductListDelegate, IAPPayDelegate, ProtocolHostDelegate, APMidasPayDelegate>
{
    _Bool _inPurchasing;
    _Bool _isPurchasing;
    NSString *_env;
    NSString *_currentPurchaseCode;
    NSString *_currentAid;
    long long _retryTimes;
    QMProductsRequest *_currentRequest;
}

+ (id)sharedManager;
@property(nonatomic) _Bool isPurchasing; // @synthesize isPurchasing=_isPurchasing;
@property(retain, nonatomic) QMProductsRequest *currentRequest; // @synthesize currentRequest=_currentRequest;
@property(nonatomic) long long retryTimes; // @synthesize retryTimes=_retryTimes;
@property(retain, nonatomic) NSString *currentAid; // @synthesize currentAid=_currentAid;
@property(retain, nonatomic) NSString *currentPurchaseCode; // @synthesize currentPurchaseCode=_currentPurchaseCode;
@property(retain, nonatomic) NSString *env; // @synthesize env=_env;
@property(readonly, nonatomic) _Bool inPurchasing; // @synthesize inPurchasing=_inPurchasing;
- (void).cxx_destruct;
- (id)getPurchaeCode:(long long)arg1;
- (id)getOfferid:(id)arg1;
- (id)serviceName:(id)arg1;
- (id)purchaseName:(id)arg1;
- (id)purchaseImage:(id)arg1;
- (void)_showAlertWithTitle:(id)arg1 msg:(id)arg2;
- (void)hideMaskView;
- (void)showMaskViewWithMessage:(id)arg1 animateActivity:(_Bool)arg2;
- (void)_notifyUserWhenErrorOccured:(id)arg1 request:(id)arg2;
- (void)onLoginExpiry:(id)arg1;
- (void)performUserLogin;
- (void)onResp:(id)arg1;
- (void)needLogin;
- (void)purchaseProductFromRequest:(id)arg1;
- (id)getMonthRequst:(id)arg1 purchaseCode:(id)arg2 openkey:(id)arg3 aid:(id)arg4 month:(long long)arg5 canChange:(_Bool)arg6;
- (void)purchaseProductByUnofficalMidasWithContext:(id)arg1 withCustomPurchaseCode:(id)arg2 aid:(id)arg3 month:(long long)arg4 canChange:(_Bool)arg5;
- (void)refreshVIPState;
- (void)onNetWorkEorror:(int)arg1 withRequestInfo:(id)arg2;
- (void)onDistributeGoodsFailue:(id)arg1 withErrorMessage:(id)arg2 withErrorCode:(int)arg3;
- (void)onDistributeGoodsFinish:(id)arg1;
- (void)onIAPPayFailue:(id)arg1 withError:(id)arg2;
- (void)onGetProductInfoFailue:(id)arg1;
- (void)onIAPPaymentSucess:(id)arg1;
- (void)onOrderFailue:(id)arg1 withErrorMessage:(id)arg2 withErrorCode:(int)arg3;
- (id)currencySymbol:(id)arg1;
- (void)onOrderFinish:(id)arg1 withRequestInfo:(id)arg2;
- (void)log:(id)arg1;
- (void)parameterWrong:(id)arg1;
- (void)onLaunProductListFailue:(id)arg1 withErrorMessage:(id)arg2 withErrorCode:(int)arg3;
- (void)onLaunProductListFinish:(id)arg1 withJsoninfo:(id)arg2;
- (void)launchPaymentWithRequest:(id)arg1;
- (void)purchaseProduct:(id)arg1 items:(id)arg2 source:(id)arg3 aid:(id)arg4 offid:(id)arg5;
- (id)getAid:(id)arg1;
- (void)processPaymentForProduct:(id)arg1 item:(long long)arg2 aid:(id)arg3 source:(id)arg4 type:(long long)arg5 context:(id)arg6;
- (void)registerPayment:(id)arg1;
- (void)registerBaseMidasInfo;
- (id)getCustomizedCode:(id)arg1 wechatUserCode:(id)arg2 qqUserCode:(id)arg3;
- (id)getPF;
- (id)getSessionType;
- (id)getSessionid;
- (void)getOpenkey:(CDUnknownBlockType)arg1;
- (id)getOpenid;
- (int)getLoginType;
- (id)skey;
- (id)uin;
- (_Bool)useGuestMode;
- (void)dealloc;
- (void)initializeSDKEnvironment;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

