//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSMutableArray, NSString;

@interface QMPlayingListItem : NSObject <NSCoding, NSCopying>
{
    _Bool _bFolderSong;
    int _listType;
    int _listTag;
    int _assetsType;
    int _listPlayMode;
    NSMutableArray *_arraySongs;
    NSString *_strDescription;
    NSString *_strPlayingLine;
    long long _nItemId;
    unsigned long long _channelType;
}

@property(nonatomic) unsigned long long channelType; // @synthesize channelType=_channelType;
@property(nonatomic) long long nItemId; // @synthesize nItemId=_nItemId;
@property(retain, nonatomic) NSString *strPlayingLine; // @synthesize strPlayingLine=_strPlayingLine;
@property(nonatomic) _Bool bFolderSong; // @synthesize bFolderSong=_bFolderSong;
@property(nonatomic) int listPlayMode; // @synthesize listPlayMode=_listPlayMode;
@property(nonatomic) int assetsType; // @synthesize assetsType=_assetsType;
@property(nonatomic) int listTag; // @synthesize listTag=_listTag;
@property(nonatomic) int listType; // @synthesize listType=_listType;
@property(retain, nonatomic) NSString *strDescription; // @synthesize strDescription=_strDescription;
@property(retain, nonatomic) NSMutableArray *arraySongs; // @synthesize arraySongs=_arraySongs;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

