//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "AVCaptureVideoDataOutputSampleBufferDelegate-Protocol.h"
#import "DecoderDelegate-Protocol.h"

@class AVCaptureDevice, AVCaptureSession, AVCaptureVideoPreviewLayer, CMAccelerometerData, CMMotionManager, NSDate, NSSet, NSString, NSThread, ParsedResult;
@protocol QMQRCodeScannerDelegate;

@interface QMQRCodeScanner : NSObject <DecoderDelegate, AVCaptureVideoDataOutputSampleBufferDelegate>
{
    NSSet *readers;
    ParsedResult *parsedResult;
    AVCaptureSession *captureSession;
    AVCaptureVideoPreviewLayer *prevLayer;
    _Bool decoding;
    AVCaptureDevice *captureDevice;
    NSThread *decodeThread;
    _Bool bConfigured;
    NSDate *_preFocusTime;
    int _focusCount;
    unsigned long long _frameCount;
    CMAccelerometerData *_oldAccelerometerData;
    CMMotionManager *_cmotionManager;
    double _updateInterval;
    _Bool _bMotionMgrOpen;
    AVCaptureVideoPreviewLayer *previewLayer;
    id <QMQRCodeScannerDelegate> delegate;
}

+ (_Bool)isSupported;
@property(retain, nonatomic) NSSet *readers; // @synthesize readers;
@property(nonatomic) __weak id <QMQRCodeScannerDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) ParsedResult *parsedResult; // @synthesize parsedResult;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *previewLayer; // @synthesize previewLayer;
@property(retain, nonatomic) AVCaptureSession *captureSession; // @synthesize captureSession;
- (void).cxx_destruct;
- (void)decoder:(id)arg1 foundPossibleResultPoint:(struct CGPoint)arg2;
- (void)decoder:(id)arg1 failedToDecodeImage:(id)arg2 usingSubset:(id)arg3 reason:(id)arg4;
- (void)notifyDelegate:(id)arg1;
- (void)decoder:(id)arg1 didDecodeImage:(id)arg2 usingSubset:(id)arg3 withResult:(id)arg4;
- (void)presentResultPoints:(id)arg1 forImage:(id)arg2 usingSubset:(id)arg3;
- (void)presentResultForString:(id)arg1;
- (void)decoder:(id)arg1 decodingImage:(id)arg2 usingSubset:(id)arg3;
- (void)decoder:(id)arg1 willDecodeImage:(id)arg2 usingSubset:(id)arg3;
- (struct CGImage *)CGImageRotated180:(struct CGImage *)arg1;
- (struct CGImage *)CGImageRotated90:(struct CGImage *)arg1;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)decodeImageThread:(id)arg1;
- (void)resetFocusParam;
- (void)focusToCenter:(id)arg1;
- (void)captureFocus;
- (void)needCaptureFocus;
- (void)stopAccelerometerUpdates;
- (void)startAccelerometerUpdates;
- (void)stopRunning;
- (void)startRunning;
- (void)close;
- (id)bestSuitablePresetForCaptrueDevice:(id)arg1;
- (void)configure;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

