//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, QMQRCodeScanner;

@protocol QMQRCodeScannerDelegate <NSObject>
- (void)qrCodeScanner:(QMQRCodeScanner *)arg1 failWithReason:(NSString *)arg2;
- (_Bool)qrCodeScanner:(QMQRCodeScanner *)arg1 didScanResult:(NSString *)arg2;
@end

