//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSData, NSMutableArray, NSMutableSet, NSString;

@interface QMRecogniProtocol : ProtocolBaseJason
{
    _Bool _isHumResult;
    float _figerprintDuration;
    float _prob;
    NSMutableArray *_recognizedSongs;
    NSData *_data;
    NSString *_sdkVersion;
    long long _sesssionId;
    long long _eFeatureType;
    NSMutableSet *_resultSongInfos;
}

@property(retain) NSMutableSet *resultSongInfos; // @synthesize resultSongInfos=_resultSongInfos;
@property float prob; // @synthesize prob=_prob;
@property long long eFeatureType; // @synthesize eFeatureType=_eFeatureType;
@property float figerprintDuration; // @synthesize figerprintDuration=_figerprintDuration;
@property long long sesssionId; // @synthesize sesssionId=_sesssionId;
@property(retain) NSString *sdkVersion; // @synthesize sdkVersion=_sdkVersion;
@property(retain) NSData *data; // @synthesize data=_data;
@property(retain) NSMutableArray *recognizedSongs; // @synthesize recognizedSongs=_recognizedSongs;
@property _Bool isHumResult; // @synthesize isHumResult=_isHumResult;
- (void).cxx_destruct;
- (id)extraHttpRequestHeader;
- (_Bool)needsUnzip:(id)arg1;
- (_Bool)isDataBeginWithFiveZero;
- (id)AES:(id)arg1 KEY:(id)arg2;
- (id)md5:(id)arg1;
- (id)makeInfo;
- (id)makeTime;
- (id)translateToRecognizedSong:(id)arg1;
- (void)reorderAndClipResult;
- (void)onParseJasonData:(id)arg1;
- (id)trimReceivedStr:(id)arg1;
- (id)createPostData:(id)arg1 SIDStr:(id)arg2;
- (id)getUrl;
- (int)cid;
- (id)initWithData:(id)arg1 sdkVersion:(id)arg2 sessionId:(long long)arg3 duration:(float)arg4 type:(long long)arg5 prob:(float)arg6;

@end

