//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

@class NSArray;
@protocol QMRecommendViewControllerDelegate;

@interface QMRecommendViewController : SkinViewController
{
    id <QMRecommendViewControllerDelegate> _delegate;
    long long _recommendType;
    NSArray *_songs;
    NSArray *_songList;
    long long _recommendPosition;
    unsigned long long _count;
    double _width;
    double _height;
    struct CGRect _settedframe;
}

@property(nonatomic) struct CGRect settedframe; // @synthesize settedframe=_settedframe;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double width; // @synthesize width=_width;
@property(nonatomic) unsigned long long count; // @synthesize count=_count;
@property(nonatomic) long long recommendPosition; // @synthesize recommendPosition=_recommendPosition;
@property(retain, nonatomic) NSArray *songList; // @synthesize songList=_songList;
@property(retain, nonatomic) NSArray *songs; // @synthesize songs=_songs;
@property(nonatomic) long long recommendType; // @synthesize recommendType=_recommendType;
@property(nonatomic) __weak id <QMRecommendViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)reloadSongListPlayingStatus;
- (void)playStatusDidChange:(id)arg1;
- (void)playListDidChange:(id)arg1;
- (void)readyToPlayChannelItem:(id)arg1;
- (void)setViewFrame:(struct CGRect)arg1;
- (void)didReceiveMemoryWarning;
- (void)updateUI;
- (_Bool)isNeedAddBottomLine;
- (void)dismissrecommendView;
- (void)addPlayChannelStat:(id)arg1;
- (void)playSongListEvent:(id)arg1;
- (void)downloadSongEvent:(id)arg1;
- (void)updateFolderImage:(id)arg1 andChannelItem:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (struct CGRect)reFrame;
- (int)vcType;
- (id)getAllVCType;
- (void)addClickStatusDownloadSong;
- (void)addClickStatusPlaySong;
- (id)getSongInfoAtIndexPath:(id)arg1;
- (void)showLoadingView;
- (void)viewDidLoad;
- (void)viewDidPop;
- (id)songsTableView;
- (void)newTable;
- (void)loadView;
- (_Bool)useBgImage;
- (void)dealloc;
- (id)initWithWidth:(double)arg1 height:(double)arg2 recommendPosition:(long long)arg3 count:(unsigned long long)arg4;
- (id)initWithWidth:(double)arg1 height:(double)arg2;

@end

