//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

#import "RecognizeHistoryVC-Protocol.h"
#import "RecognizeResultVC-Protocol.h"
#import "RecognizingVC-Protocol.h"

@class NSString, QMTabBar, RecognizeHistoryVC, RecognizeResultVC, RecognizingVC;

@interface QMRecognizerVC : SkinViewController <RecognizeResultVC, RecognizingVC, RecognizeHistoryVC>
{
    _Bool _autoStartRecognize;
    int _currentVCType;
    RecognizingVC *_recgnizingVC;
    RecognizeResultVC *_recognizeResultVC;
    RecognizeHistoryVC *_recognizeHistoryVC;
    long long _eRecognizeVCStatus;
    QMTabBar *_tabBar;
}

@property(nonatomic) int currentVCType; // @synthesize currentVCType=_currentVCType;
@property(retain) QMTabBar *tabBar; // @synthesize tabBar=_tabBar;
@property long long eRecognizeVCStatus; // @synthesize eRecognizeVCStatus=_eRecognizeVCStatus;
@property(retain) RecognizeHistoryVC *recognizeHistoryVC; // @synthesize recognizeHistoryVC=_recognizeHistoryVC;
@property(retain) RecognizeResultVC *recognizeResultVC; // @synthesize recognizeResultVC=_recognizeResultVC;
@property(retain) RecognizingVC *recgnizingVC; // @synthesize recgnizingVC=_recgnizingVC;
@property _Bool autoStartRecognize; // @synthesize autoStartRecognize=_autoStartRecognize;
- (void).cxx_destruct;
- (void)vcToExpose:(int)arg1;
- (void)onNotifyShowMiniPlayer;
- (void)onNotifyRecognizeProcessFailed:(id)arg1;
- (void)onNotifyRecognizeRecordedVolumn:(id)arg1;
- (void)onNotifyRecognizeStatusChange:(id)arg1;
- (void)openLink:(id)arg1 withLink:(id)arg2;
- (void)updateTabbarTitleColor;
- (void)addTabTitleToTabBar;
- (id)selectetdItemImage:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)accessibilityLabel:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)touchDown:(id)arg1 itemAtIndex:(unsigned long long)arg2;
- (id)imageFor:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)recognizeHistoryVC:(id)arg1 batchDeleteMatchedSessions:(id)arg2;
- (void)recognizeHistoryVC:(id)arg1 deleteMatchedSession:(id)arg2;
- (void)recognizeHistoryVC:(id)arg1 deleteUnMatchedSession:(id)arg2;
- (void)recognizeHistoryVC:(id)arg1 retryWithSession:(id)arg2;
- (void)recognizeResultVC:(id)arg1 feedBackWithSession:(id)arg2;
- (void)recognizeResultVC:(id)arg1 pushWebView:(id)arg2;
- (void)recognizeResultVC:(id)arg1 recognizeSession:(id)arg2 chooseResult:(id)arg3;
- (void)recognizeResultVC:(id)arg1 retryWithSession:(id)arg2;
- (void)recognizeResultVC:(id)arg1 switchToRecognizing:(_Bool)arg2;
- (void)recognizingVC:(id)arg1 switchToStatus:(_Bool)arg2;
- (id)getAllVCType;
- (void)retrySession:(id)arg1;
- (id)retryTipsByResult:(long long)arg1;
- (void)changeRecognizeStatus:(long long)arg1 attachMode:(_Bool)arg2;
- (void)playRecognizeResultFromWatchKit:(id)arg1;
- (void)switchRecord;
- (void)show:(id)arg1;
- (void)stopRecognizeFromWatchKit;
- (void)stopOrShowResultFromWatchKit;
- (void)startRecognizeFromWatchKit;
- (void)reqSong:(id)arg1;
- (void)didShake:(id)arg1;
- (void)doHandlePushComming:(id)arg1;
- (void)onNotifyReturnMiniPlayerFromPlayingView:(id)arg1;
- (_Bool)showDelBtnInActionSheet:(id)arg1;
- (_Bool)enableShake;
- (int)vcType;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (long long)vcStatusFromSessionStatus:(long long)arg1;
- (void)attachRecognizeStatus;
- (void)dealloc;
- (void)loadView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

