//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSData;

@interface QMRecogniUploadProtoco : ProtocolBaseJason
{
    _Bool _isHumResult;
    NSData *_mRecordData;
}

@property _Bool isHumResult; // @synthesize isHumResult=_isHumResult;
@property(retain) NSData *mRecordData; // @synthesize mRecordData=_mRecordData;
- (void).cxx_destruct;
- (_Bool)needsUnzip:(id)arg1;
- (_Bool)isDataBeginWithFiveZero;
- (void)onParseJasonData:(id)arg1;
- (id)createPostData:(id)arg1 SIDStr:(id)arg2;
- (id)trimReceivedStr:(id)arg1;
- (id)extraHttpRequestHeader;
- (id)getUrl;
- (int)cid;
- (id)initWithUploadData:(id)arg1 isHumResult:(_Bool)arg2;

@end

