//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

#import "ImageManagerDelegate-Protocol.h"
#import "OnLineSearchResultDelegate-Protocol.h"
#import "ProtocolHostDelegate-Protocol.h"
#import "QMNewUserRecommendViewDelegate-Protocol.h"
#import "QMTabBarDelegate-Protocol.h"
#import "QMWXH5DownloadRecommendViewDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class DiscoverRootViewController, GenericWebViewController, IPlimitVC, NSArray, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, OnLineSearchViewController, QMMyMusicSplitVC, QMNewUserRecommendView, QMTabBar, QMWXH5DownloadRecommendView, UIButton, UIImageView, UILabel, UINavigationController, UIView;

@interface QMRootTopTabBarVC : SkinViewController <QMNewUserRecommendViewDelegate, QMWXH5DownloadRecommendViewDelegate, OnLineSearchResultDelegate, QMTabBarDelegate, UINavigationControllerDelegate, ProtocolHostDelegate, ImageManagerDelegate>
{
    QMTabBar *tabBar;
    QMMyMusicSplitVC *myMusicRootVC;
    GenericWebViewController *channelRootVC;
    GenericWebViewController *mvTabRootVC;
    DiscoverRootViewController *discoverRootVC;
    QMNewUserRecommendView *_newUserRecommendView;
    QMWXH5DownloadRecommendView *_wxH5DownloadRecommendView;
    _Bool _showProfileView;
    _Bool _isConcisePatternOn;
    _Bool _contentLoaded;
    int _currentShowTabIndex;
    NSArray *_mainHeaderTabComponents;
    UIView *_mainContainerView;
    QMTabBar *_verticalTab;
    QMTabBar *_horizontalTab;
    UIButton *_setBtn;
    UIView *_userView;
    UINavigationController *_profileVCNav;
    UIImageView *_imageViewDefaultHeader;
    UIImageView *_imageViewHeader;
    UILabel *_loginTip;
    NSMutableArray *_userIcoImageViewArray;
    UIView *_userIconsContainerView;
    UINavigationController *_showingNav;
    IPlimitVC *_rootIPLimitVC;
    NSMutableArray *_arrayYellowPoint;
    NSMutableSet *_setRedPointReason;
    NSMutableDictionary *_hasSolvedPlayTask;
    NSMutableArray *_finalShowUserIconsArray;
    OnLineSearchViewController *_onLineSearchVC;
}

@property(retain, nonatomic) OnLineSearchViewController *onLineSearchVC; // @synthesize onLineSearchVC=_onLineSearchVC;
@property(retain, nonatomic) NSMutableArray *finalShowUserIconsArray; // @synthesize finalShowUserIconsArray=_finalShowUserIconsArray;
@property(retain, nonatomic) NSMutableDictionary *hasSolvedPlayTask; // @synthesize hasSolvedPlayTask=_hasSolvedPlayTask;
@property(nonatomic) _Bool contentLoaded; // @synthesize contentLoaded=_contentLoaded;
@property(retain, nonatomic) NSMutableSet *setRedPointReason; // @synthesize setRedPointReason=_setRedPointReason;
@property(retain, nonatomic) NSMutableArray *arrayYellowPoint; // @synthesize arrayYellowPoint=_arrayYellowPoint;
@property(retain, nonatomic) IPlimitVC *rootIPLimitVC; // @synthesize rootIPLimitVC=_rootIPLimitVC;
@property(retain, nonatomic) UINavigationController *showingNav; // @synthesize showingNav=_showingNav;
@property(retain, nonatomic) UIView *userIconsContainerView; // @synthesize userIconsContainerView=_userIconsContainerView;
@property(retain, nonatomic) NSMutableArray *userIcoImageViewArray; // @synthesize userIcoImageViewArray=_userIcoImageViewArray;
@property(retain, nonatomic) UILabel *loginTip; // @synthesize loginTip=_loginTip;
@property(retain, nonatomic) UIImageView *imageViewHeader; // @synthesize imageViewHeader=_imageViewHeader;
@property(retain, nonatomic) UIImageView *imageViewDefaultHeader; // @synthesize imageViewDefaultHeader=_imageViewDefaultHeader;
@property(retain, nonatomic) UINavigationController *profileVCNav; // @synthesize profileVCNav=_profileVCNav;
@property(retain, nonatomic) UIView *userView; // @synthesize userView=_userView;
@property(retain, nonatomic) UIButton *setBtn; // @synthesize setBtn=_setBtn;
@property(retain, nonatomic) QMTabBar *horizontalTab; // @synthesize horizontalTab=_horizontalTab;
@property(retain, nonatomic) QMTabBar *verticalTab; // @synthesize verticalTab=_verticalTab;
@property(retain, nonatomic) UIView *mainContainerView; // @synthesize mainContainerView=_mainContainerView;
@property(retain, nonatomic) NSArray *mainHeaderTabComponents; // @synthesize mainHeaderTabComponents=_mainHeaderTabComponents;
@property(nonatomic) _Bool isConcisePatternOn; // @synthesize isConcisePatternOn=_isConcisePatternOn;
@property(nonatomic) int currentShowTabIndex; // @synthesize currentShowTabIndex=_currentShowTabIndex;
@property(nonatomic) _Bool showProfileView; // @synthesize showProfileView=_showProfileView;
@property(retain, nonatomic) DiscoverRootViewController *discoverRootVC; // @synthesize discoverRootVC;
@property(retain, nonatomic) GenericWebViewController *mvTabRootVC; // @synthesize mvTabRootVC;
@property(retain, nonatomic) GenericWebViewController *channelRootVC; // @synthesize channelRootVC;
@property(retain, nonatomic) QMMyMusicSplitVC *myMusicRootVC; // @synthesize myMusicRootVC;
@property(retain, nonatomic) QMTabBar *tabBar; // @synthesize tabBar;
- (void).cxx_destruct;
- (void)onNewUserRecommendViewGuessLikeClicked:(id)arg1;
- (void)onWXH5DownloadCancelButtonClicked;
- (void)onNewUserRecommendViewCancelButtonClicked;
- (void)onNewUserRecommendViewPlayButtonClickedWithIndex:(long long)arg1;
- (void)readyToPlayChannelItem:(id)arg1;
- (void)onNotifyGetVipLogoInfo:(id)arg1;
- (void)onNeedShowWXH5DonwloadRecommend:(id)arg1;
- (void)onNeedShowNewUserRecommend:(id)arg1;
- (void)onNotifyCarBluetoothAutoClosed:(id)arg1;
- (void)onNotifyShowDownloadQualityPrompt:(id)arg1;
- (void)onNotifyShowAutoSaveConditionNet:(id)arg1;
- (void)onNotifySystemFolderRedpointReasonGone:(id)arg1;
- (void)onNotifyUserFolderRedpointReasonGone:(id)arg1;
- (void)onNotifyAddRedPointReasonMyMusicNewLove:(id)arg1;
- (void)onNotifyUpdateRequestSongFinished:(id)arg1;
- (void)onNotifyKSongUpdate:(id)arg1;
- (void)onNotifyNewForMeInfo:(id)arg1;
- (void)onNotifyJumpToMyMusicTab:(id)arg1;
- (void)onNotifyUserLanguageChanged:(id)arg1;
- (void)searchViewControllerDidDissappear;
- (void)goToSearchTab;
- (void)onSearchAllButtonClicked:(id)arg1;
- (void)makeMoreBecomeFirstResponser;
- (void)jumpToMyMusicTab:(long long)arg1;
- (void)updateALLSongCell;
- (void)navigateToQPlayMoreVC;
- (void)navigateToFeedBackCategory;
- (void)goSquareCategoryVC:(long long)arg1 andName:(id)arg2;
- (void)goMusicHall:(unsigned long long)arg1;
- (void)goOldMusicHall:(unsigned long long)arg1 categoryDic:(id)arg2;
- (id)createYellowPointAtTabIndex:(int)arg1 offsetX:(double)arg2;
- (void)showYellowPoint:(int)arg1 visiable:(_Bool)arg2;
- (void)updateTabRedPointByAdd:(_Bool)arg1 tabIndex:(int)arg2;
- (void)firstTimeUpdateRedPoint;
- (_Bool)hasRedPointReasonAtTab:(int)arg1;
- (void)fillRedPointReason;
- (void)updateRedPoint;
- (void)refreshRedPointFromProtocol:(id)arg1 fromType:(int)arg2;
- (void)startRedPointProtocol;
- (int)getTabIndexByRedPointReason:(int)arg1;
- (void)removeRedPointReason:(int)arg1;
- (void)addRedPointReason:(int)arg1;
- (void)jumpToAlbumModeSetting;
- (void)jumpToImportSongs:(id)arg1;
- (void)showAppThemeDetailVC:(id)arg1;
- (void)jumpToAppThemeLocalManagerVC;
- (void)showAppThemeMainVC;
- (void)jumpToThemeDetailVC:(id)arg1;
- (void)jumpToRecognizeVC;
- (void)updateDownloadCell:(id)arg1;
- (_Bool)containNavigationController:(id)arg1;
- (Class)channelRootVCClass;
- (void)onColorStyleChanged;
- (void)setForbidden:(id)arg1;
- (void)showFootTabBar:(_Bool)arg1 isAnimated:(_Bool)arg2;
- (void)animationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)jumpToDtsSetting;
- (void)jumpToQPlayAutoSetting;
- (void)jumpToQPlaySetting;
- (void)jumpToPreferencesSetting;
- (void)onImagetWithInfo:(id)arg1 ImageFile:(id)arg2;
- (void)jumpToChannelViewWithMid:(int)arg1 AndKey1:(id)arg2 AndKey2:(id)arg3 AndKey3:(id)arg4 AndKey4:(int)arg5 AndKey5:(int)arg6 AndKey6:(int)arg7 AndKey7:(id)arg8 AndRaddioPlay:(int)arg9 AndPeriod:(id)arg10 AndAction:(id)arg11 AndIndex:(int)arg12 bNeedRoot:(_Bool)arg13 otherParas:(id)arg14 fromVC:(id)arg15 animated:(_Bool)arg16;
- (void)jumpToChannelViewWithMid:(int)arg1 AndKey1:(id)arg2 AndKey2:(id)arg3 AndKey3:(id)arg4 AndKey4:(int)arg5 AndKey5:(int)arg6 AndKey6:(int)arg7 AndKey7:(id)arg8 AndRaddioPlay:(int)arg9 AndPeriod:(id)arg10 AndAction:(id)arg11 AndIndex:(int)arg12 bNeedRoot:(_Bool)arg13 otherParas:(id)arg14 fromVC:(id)arg15;
- (void)livePlayAction:(id)arg1 title:(id)arg2;
- (void)jumpToMusicCircleAlbumCommentDetailWithMid:(int)arg1 AndKey1:(id)arg2 AndKey3:(id)arg3;
- (void)jumpToMyMusicViewWithMid:(int)arg1 AndKey1:(id)arg2 AndKey2:(id)arg3;
- (void)jumpToMoreViewWithMid:(int)arg1 AndKey1:(id)arg2 AndKey2:(id)arg3;
- (void)showRequestSongView;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showNewVersionAlert:(id)arg1;
- (void)openTodayPlayList:(long long)arg1 jumpOnly:(_Bool)arg2;
- (int)_playModeByTodayItemType:(int)arg1;
- (int)_todayItemStatusClick:(int)arg1;
- (void)_jumpToFind;
- (void)_jumpToChannelRecommandVC;
- (void)openWebViewOutOffApp:(id)arg1;
- (void)openWebViewInApp:(id)arg1;
- (void)showPlayWindow:(id)arg1;
- (void)showPlayingFakeSongList:(id)arg1;
- (id)vcFromByReportId:(id)arg1 start:(_Bool)arg2;
- (void)delayShowDownloadActionsheet;
- (void)showPlayingList:(id)arg1 songArray:(id)arg2 action:(id)arg3 toDownload:(_Bool)arg4 reportId:(id)arg5 start:(_Bool)arg6 itemID:(long long)arg7 typeID:(long long)arg8;
- (void)showPlayingList:(id)arg1 songArray:(id)arg2 assetsType:(int)arg3 action:(id)arg4 toDownload:(_Bool)arg5 reportId:(id)arg6 start:(_Bool)arg7 itemID:(long long)arg8 typeID:(long long)arg9 tjreport:(id)arg10 tjtjreport:(id)arg11;
- (void)delayShowPlayingList:(unsigned long long)arg1 index:(id)arg2 songArray:(id)arg3 action:(id)arg4 toDownload:(_Bool)arg5 reportId:(id)arg6 start:(_Bool)arg7 itemID:(long long)arg8 typeID:(long long)arg9;
- (void)downloadMusic:(id)arg1;
- (void)handleOtherOpenInfo:(id)arg1 byStart:(id)arg2;
- (void)handleOpenCategoryDetailWithCategoryId:(int)arg1;
- (void)hostCallBackWithWorkProtocol:(id)arg1 protocolError:(id)arg2;
- (_Bool)isShowingMyMusicRootVC;
- (void)setSelectIndex:(int)arg1;
- (id)getRootChannelVC;
- (id)currentTabVC;
@property(readonly, nonatomic) __weak UINavigationController *currentNavigationController;
- (void)showNavControllerInMainContainer:(id)arg1;
- (void)jumpToCurrentTab;
- (void)jumpToTab:(int)arg1;
- (void)buttonClickReport:(unsigned long long)arg1;
- (void)addViewToMainContainer:(id)arg1;
- (void)loadTabViewAtIndex:(unsigned long long)arg1;
- (void)touchDown:(id)arg1 itemAtIndex:(unsigned long long)arg2;
- (void)touchDown:(id)arg1 itemAtIndex:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)selectedItem:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)selectedImageAtIndex:(unsigned long long)arg1;
- (void)clearAllSelect;
- (id)imageAtIndex:(unsigned long long)arg1;
- (id)titleAtIndex:(unsigned long long)arg1;
- (void)touchUpInside:(id)arg1 itemAtIndex:(unsigned long long)arg2;
- (id)selectedImageView:(id)arg1;
- (id)selectetdItemImage:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)imageFor:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)accessibilityLabel:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)showSettingView:(id)arg1;
- (id)createSetButton;
- (void)onNotifyLogout:(id)arg1;
- (void)onNotifyUserHeaderImageDownloaded:(id)arg1;
- (void)onNotifyVipPurchaseSuccess:(id)arg1;
- (void)onNotifyGetUserInfoSuccess:(id)arg1;
- (void)addUserInfoNotify;
- (void)onTouchUpInsideUserHeader:(id)arg1;
- (id)makeFinalShowUserIconsArray:(id)arg1;
- (void)setUserIcons:(id)arg1;
- (void)updateUserView;
- (id)createUserView;
- (id)getTabComponents;
- (void)createMainTabber;
- (struct CGRect)getMainContainerFrame;
- (void)loadView;
- (void)setTabBarButtonState:(int)arg1 tabbar:(id)arg2;
- (void)setUnselectedForTabbar:(id)arg1;
- (void)refreshLeftTabbarBG;
- (void)refreshIPadSkin;
- (void)reLayoutTo:(int)arg1;
- (void)reLayout:(long long)arg1;
- (struct CGRect)reFrame;
- (id)strVCtype;
- (int)vcType;
- (void)loadContent;
- (void)onList:(id)arg1 ChangeByType:(int)arg2 Index:(int)arg3 Info:(id)arg4;
- (void)checkNewVersion;
- (void)checkNewVersionAndNotice;
- (void)refreshGenericView;
- (void)popGestureRecognize;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

