//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NewPlayingListBaseVC.h"

#import "NewPlayingCellTableViewCellDelegate-Protocol.h"

@class NSString;
@protocol QMRoamingDeviceSelectDelegate;

@interface QMRoamingDevicesVC : NewPlayingListBaseVC <NewPlayingCellTableViewCellDelegate>
{
    id <QMRoamingDeviceSelectDelegate> _roamingDeviceSelectDelegate;
    unsigned long long _selectedDeviceIndex;
}

@property(nonatomic) unsigned long long selectedDeviceIndex; // @synthesize selectedDeviceIndex=_selectedDeviceIndex;
@property(nonatomic) __weak id <QMRoamingDeviceSelectDelegate> roamingDeviceSelectDelegate; // @synthesize roamingDeviceSelectDelegate=_roamingDeviceSelectDelegate;
- (void).cxx_destruct;
- (void)prepareDeleteSong:(unsigned long long)arg1 isManual:(_Bool)arg2;
- (void)selectRoamingDeviceIndex:(long long)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)dismissAnimationDidFinish;
- (void)delayHiddenPlayingList;
- (void)hiddenPlayingList;
- (void)_makeBaseViewBackGroundColor;
- (void)buildView;
- (id)deviceList;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

