//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIView;

@protocol QMSearchHeaderViewDelegate <NSObject>
- (void)onQMSearchViewRecognizeButtonClicked:(UIView *)arg1;
- (void)onQMSearchViewDidSelected:(UIView *)arg1;

@optional
- (void)onQMSearchViewVoiceButtonClicked:(UIView *)arg1;
@end

