//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ComCollectionCell.h"

@class QMLabel, UIButton, UIView;
@protocol QMSearchHeaderViewDelegate;

@interface QMSearchHeaderView : ComCollectionCell
{
    _Bool _showRecognize;
    QMLabel *_placeHolder;
    id <QMSearchHeaderViewDelegate> _delegate;
    UIButton *_recognizeButton;
    UIView *_iconLabelGroup;
}

@property(retain) UIView *iconLabelGroup; // @synthesize iconLabelGroup=_iconLabelGroup;
@property(retain) UIButton *recognizeButton; // @synthesize recognizeButton=_recognizeButton;
@property _Bool showRecognize; // @synthesize showRecognize=_showRecognize;
@property(nonatomic) __weak id <QMSearchHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) QMLabel *placeHolder; // @synthesize placeHolder=_placeHolder;
- (void).cxx_destruct;
- (void)onUserLanguageChanged;
- (id)getdefaultYunyingKey;
- (void)onDefaultSearchKeyChanged:(id)arg1;
- (void)onNotifySkinConciseModeChange:(_Bool)arg1;
- (void)onNotifySkinSettingChange:(id)arg1;
- (void)onTouchUpInsideRecognize:(id)arg1;
- (void)onTouchUpInsideVoiceSearch:(id)arg1;
- (void)onTouchUpInsideSearchLocal:(id)arg1;
- (void)setSelected:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)createHeaderView:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

