//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "ImageManagerDelegate-Protocol.h"
#import "QzonePhotoAPIDelegate-Protocol.h"
#import "SongListSearchVCDelegate-Protocol.h"
#import "WXApiDelegate-Protocol.h"

@class JSResponseCallbackObject, NSString, ShareActionsheet, ShareInfo, UINavigationController, UIViewController, WVJBResponseCallbackObject;

@interface QMShareManager : NSObject <ImageManagerDelegate, WXApiDelegate, SongListSearchVCDelegate, QzonePhotoAPIDelegate>
{
    UINavigationController *_navShare;
    _Bool isShareToWXTimeLine;
    _Bool _fromShare;
    int shareTag;
    int _eShareTo;
    ShareInfo *shareInfo;
    UIViewController *_rootSearchVC;
    ShareActionsheet *_actionsheet;
    WVJBResponseCallbackObject *_responseCallbackObject;
    JSResponseCallbackObject *_MClientResponseObject;
    NSString *_asynImgUrl;
}

+ (id)sharedManager;
@property(copy, nonatomic) NSString *asynImgUrl; // @synthesize asynImgUrl=_asynImgUrl;
@property(nonatomic) int eShareTo; // @synthesize eShareTo=_eShareTo;
@property(retain, nonatomic) JSResponseCallbackObject *MClientResponseObject; // @synthesize MClientResponseObject=_MClientResponseObject;
@property(retain, nonatomic) WVJBResponseCallbackObject *responseCallbackObject; // @synthesize responseCallbackObject=_responseCallbackObject;
@property(retain, nonatomic) ShareActionsheet *actionsheet; // @synthesize actionsheet=_actionsheet;
@property(retain, nonatomic) UIViewController *rootSearchVC; // @synthesize rootSearchVC=_rootSearchVC;
@property(nonatomic) _Bool fromShare; // @synthesize fromShare=_fromShare;
@property(retain, nonatomic) ShareInfo *shareInfo; // @synthesize shareInfo;
@property(nonatomic) _Bool isShareToWXTimeLine; // @synthesize isShareToWXTimeLine;
@property(nonatomic) int shareTag; // @synthesize shareTag;
- (void).cxx_destruct;
- (void)onImagetWithInfo:(id)arg1 Image:(id)arg2;
- (void)tryExecQZoneResp:(int)arg1;
- (void)tryExecQQResp:(int)arg1;
- (void)tryExecWechatResp:(int)arg1;
- (void)sharePhotoResult:(int)arg1;
- (void)processQQShareResp:(id)arg1;
- (void)onResp:(id)arg1;
- (void)setValuesBeforeOnRespReturn;
- (void)showSharedAlert:(id)arg1 orWithViewController:(id)arg2;
- (void)onReq:(id)arg1;
- (void)showQQMusicRootSearchUI;
- (void)hideQQMusicRootSearchUI;
- (void)delayAddVCView:(id)arg1;
- (void)toShareWithShareinfo:(id)arg1 shareTo:(int)arg2 AndJSResponseCallbackObject:(id)arg3;
- (void)doShareAfterGetImage;
- (void)getImageFromServer;
- (void)hideLoading;
- (void)showLoading;
- (void)toShareWithShareinfo:(id)arg1 shareTo:(int)arg2 hasTopCustomView:(_Bool)arg3 AndCallBackObject:(id)arg4;
- (void)toShareWithShareinfo:(id)arg1 hasTopCustomView:(_Bool)arg2 AndCallBackObject:(id)arg3;
- (void)toShareBlackModelWithShareinfo:(id)arg1 hasTopCustomView:(_Bool)arg2;
- (void)toShareWithShareinfo:(id)arg1 hasTopCustomView:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

