//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@class SilentUserRecommendItemInfo;
@protocol QMSilentUserRecommendViewDelegate;

@interface QMSilentUserRecommendView : UIImageView
{
    id <QMSilentUserRecommendViewDelegate> _delegate;
    SilentUserRecommendItemInfo *_silentUserRecommendItemInfo;
    long long _infoIndexInItemArray;
}

@property(nonatomic) long long infoIndexInItemArray; // @synthesize infoIndexInItemArray=_infoIndexInItemArray;
@property(retain, nonatomic) SilentUserRecommendItemInfo *silentUserRecommendItemInfo; // @synthesize silentUserRecommendItemInfo=_silentUserRecommendItemInfo;
@property(nonatomic) __weak id <QMSilentUserRecommendViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onNotifyColorStyleChanged:(id)arg1;
- (void)onCancelButtonClicked;
- (void)onConfirmButtonClicked;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

