//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary, NSString;

@interface QMSpiderCommand : NSObject
{
    NSString *_sendCase;
    NSDictionary *_conditions;
    double _biteTime;
}

@property(nonatomic) double biteTime; // @synthesize biteTime=_biteTime;
@property(retain, nonatomic) NSDictionary *conditions; // @synthesize conditions=_conditions;
@property(retain, nonatomic) NSString *sendCase; // @synthesize sendCase=_sendCase;
- (void).cxx_destruct;
- (id)description;

@end

