//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class QMTableView, UIView;

@protocol QMTableViewProtocol <NSObject>

@optional
- (_Bool)miniplayerShouldHide;
- (_Bool)tableViewNotHiddenAndHasMoreData:(QMTableView *)arg1;
- (double)defaultContentOffsetY;
- (_Bool)canDeletetableFootView;
- (void)buildTableFootView;
- (void)tableView:(QMTableView *)arg1 hitView:(UIView *)arg2;
- (_Bool)moreDataIsLoading:(QMTableView *)arg1;
- (void)processingLoadMoreAction:(QMTableView *)arg1;
- (_Bool)hasMoreDataInTableView:(QMTableView *)arg1;
@end

