//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QMRecommendViewController.h"

#import "BEActionSheetDelegate-Protocol.h"

@class NSString;

@interface QMWXH5DownloadTableViewVC : QMRecommendViewController <BEActionSheetDelegate>
{
}

- (void)actionSheet:(id)arg1 confirmButtonClickedWithChoiceValue:(id)arg2 identifier:(id)arg3;
- (void)addClickStatusDownloadSong;
- (void)addClickStatusPlaySong;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

