//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "QMRecommendViewControllerDelegate-Protocol.h"

@class NSArray, NSString, QMRecommendViewController, UIImageView;
@protocol QMWXH5DownloadRecommendViewDelegate;

@interface QMWXH5DownloadRecommendView : UIView <QMRecommendViewControllerDelegate>
{
    UIImageView *_bgImageView;
    QMRecommendViewController *_tableViewVC;
    UIView *_headerView;
    UIView *_footerView;
    id <QMWXH5DownloadRecommendViewDelegate> _delegate;
    NSArray *_songList;
}

@property(retain, nonatomic) NSArray *songList; // @synthesize songList=_songList;
@property(nonatomic) __weak id <QMWXH5DownloadRecommendViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)recommendViewControllerDismiss:(id)arg1;
- (void)cancel;
- (void)onDownloadSongButtonClicked:(id)arg1;
- (unsigned int)_getMaxFullCellCountInBgImageView;
- (void)_layoutSubviewWhileMultiSong;
- (void)_layoutSubviewWhileSingleSong;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

