//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSMutableArray, NSString, QPlaySpeaker;
@protocol QPlayQueueDataSoucce;

@interface QPlayQueue : NSObject
{
    NSMutableArray *tracks;
    NSArray *songs;
    long long index;
    int queueID;
    int queueUpdateID;
    QPlaySpeaker *speaker;
    id <QPlayQueueDataSoucce> dataSource;
    NSString *QueueOwnerID;
    NSString *QueueOwnerContext;
}

@property(retain, nonatomic) NSArray *songs; // @synthesize songs;
@property(retain, nonatomic) NSString *QueueOwnerContext; // @synthesize QueueOwnerContext;
@property(retain, nonatomic) NSString *QueueOwnerID; // @synthesize QueueOwnerID;
@property int queueUpdateID; // @synthesize queueUpdateID;
@property int queueID; // @synthesize queueID;
@property(nonatomic) long long index; // @synthesize index;
@property(nonatomic) __weak id <QPlayQueueDataSoucce> dataSource; // @synthesize dataSource;
@property(nonatomic) __weak QPlaySpeaker *speaker; // @synthesize speaker;
@property(retain, nonatomic) NSMutableArray *tracks; // @synthesize tracks;
- (void).cxx_destruct;
- (void)save;
- (long long)queueCapability;
- (long long)indexOfTrackURLInQueue:(id)arg1;
- (id)songInTheQueueByIndex:(long long)arg1;
- (long long)indexOfTrackInQueue:(id)arg1;
- (long long)indexOfSong:(id)arg1;
- (_Bool)isLastSongInQueue:(id)arg1;
- (id)songInTheQueueByID:(unsigned long long)arg1;
- (id)songInTheQueue:(id)arg1;
- (id)makeMetaDataForQPlayQueue:(id)arg1;
- (long long)getIndex;
- (void)restore;
- (id)initWithSong:(id)arg1 dataSource:(id)arg2 queueOwnerID:(id)arg3 queueContext:(id)arg4 queueID:(int)arg5;
- (void)fillQueueFromSongAfterVkeyReady:(id)arg1;
- (id)init:(id)arg1 song:(id)arg2;
- (void)updateQQueue:(id)arg1;
- (void)updateQPlaySong:(id)arg1;
- (id)createQQueue:(id)arg1 index:(long long)arg2;

@end

