//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface QPlayUpnpIcon : NSObject
{
    NSString *resourceName;
    void *cObject;
}

@property(readonly) __weak NSString *resourceName; // @synthesize resourceName;
@property(readonly) void *cObject; // @synthesize cObject;
- (void).cxx_destruct;
- (void)setResourceName:(id)arg1;
- (long long)depth;
- (long long)height;
- (long long)width;
- (id)mimeType;
- (id)url;
- (id)init;
- (id)initWithCObject:(void *)arg1;

@end

