//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSString;

@interface QPlayAutoGetCarPicProtocol : ProtocolBaseJason
{
    NSString *Brand;
    NSString *PicUrl;
}

@property(retain, nonatomic) NSString *PicUrl; // @synthesize PicUrl;
@property(retain, nonatomic) NSString *Brand; // @synthesize Brand;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getUrl;
- (_Bool)canReportError;
- (int)cid;
- (id)init;

@end

