//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"

@class QQApiObject;

@interface QQApiObjectCoderImpl : NSObject <NSCoding>
{
    QQApiObject *_obj;
}

@property(retain, nonatomic) QQApiObject *obj; // @synthesize obj=_obj;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithObject:(id)arg1;

@end

