//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface QQFriendsGroupItem : NSObject
{
    long long _groupid;
    NSString *_name;
    long long _totalnum;
}

+ (id)tranlateToQQFriendsGroupItemFromJsonData:(id)arg1;
@property(nonatomic) long long totalnum; // @synthesize totalnum=_totalnum;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) long long groupid; // @synthesize groupid=_groupid;
- (void).cxx_destruct;

@end

