//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "ProtocolHostDelegate-Protocol.h"

@class SharedProtocol;

@interface QQMusicShareStat : NSObject <ProtocolHostDelegate>
{
    SharedProtocol *protocol;
}

+ (id)sharedQQMusicShareStat;
- (void).cxx_destruct;
- (void)shareMessage:(id)arg1 dest:(long long)arg2 shareInfo:(id)arg3;
- (void)dealloc;
- (id)init;

@end

