//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "HookViewController.h"

#import "NetStatusManagerProtocol-Protocol.h"
#import "ProtocolHostDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class NSString;

@interface QQMuiscHomeViewController : HookViewController <NetStatusManagerProtocol, UIAlertViewDelegate, ProtocolHostDelegate>
{
    _Bool bCancelAlertWifiTips;
    _Bool isAlertViewDownloadLimitShow;
    _Bool isAlertViewDownloadLimitAutoShowStop;
    _Bool _orientation;
    int _appWindowMode;
    long long _nKeyboardHeight;
}

@property(nonatomic) _Bool orientation; // @synthesize orientation=_orientation;
@property(nonatomic) int appWindowMode; // @synthesize appWindowMode=_appWindowMode;
@property(nonatomic) long long nKeyboardHeight; // @synthesize nKeyboardHeight=_nKeyboardHeight;
@property(nonatomic) _Bool bCancelAlertWifiTips; // @synthesize bCancelAlertWifiTips;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)uploadStatusOfAppWindowMode:(int)arg1;
- (void)hideModalView;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)relayoutTo:(int)arg1;
- (void)reLayout:(int)arg1;
- (void)UIStatusBarOrientation:(id)arg1;
- (void)refreshiPadSkin;
- (void)createLeftDefaultView;
- (void)refreshTipView;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)onNotifyPopWebPage:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)netReachabilityByWifiChanged:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)delayToInitThirdDeviceMonitor;
- (void)viewDidLoad;
- (_Bool)canBecomeFirstResponder;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

