//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSFileManagerDelegate-Protocol.h"
#import "NSURLConnectionDataDelegate-Protocol.h"

@class NSFileManager, NSMutableArray, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue, OS_dispatch_semaphore;

@interface QQOfflineWebApp : NSObject <NSFileManagerDelegate, NSURLConnectionDataDelegate>
{
    NSMutableArray *_expiredBids;
    NSFileManager *_fileManager;
    NSObject<OS_dispatch_semaphore> *_webappCacheNewSemaphore;
    NSString *_documentPath;
    NSString *_pathToWebappCacheInDocuments;
    NSString *_pathToWebappCacheNewInDocuments;
    NSString *_pathToWebappCacheInQQApp;
    NSMutableArray *_updatingBusinesses;
    NSString *_clientVersion;
    long long _currentBid;
    NSObject<OS_dispatch_queue> *_updateQueue;
    NSObject<OS_dispatch_queue> *_downloadQueue;
    NSMutableDictionary *_urlMap;
}

+ (id)getInstance;
@property(retain, nonatomic) NSMutableDictionary *urlMap; // @synthesize urlMap=_urlMap;
- (void).cxx_destruct;
- (int)internalDownloadUpdateForBusiness:(id)arg1 url:(id)arg2;
- (id)internalShouldUpdateForBusiness:(id)arg1 responseText:(id)arg2;
- (id)internalGetServerResponseForBusiness:(id)arg1;
- (void)downloadUpdateForBusiness:(id)arg1 zipUrl:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)checkUpdateOnlyForBusiness:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)onQQLoginSuccessNotification:(id)arg1;
- (_Bool)fileManager:(id)arg1 shouldProceedAfterError:(id)arg2 copyingItemAtPath:(id)arg3 toPath:(id)arg4;
- (id)uuid;
- (void)setBusiness:(id)arg1 isCurrentlyUpdating:(_Bool)arg2;
- (_Bool)isCurrentlyUpdating:(id)arg1;
- (_Bool)isCurrentlyUpdating;
- (void)unmarkCheckUpdateRecentlyForBusiness:(id)arg1;
- (void)markCheckUpdateRecentlyForBusiness:(id)arg1;
- (_Bool)hasAlreadyCheckUpdateRecentlyForBusiness:(id)arg1;
- (int)updateIntervalForBusiness:(id)arg1;
- (_Bool)remoteVersionNumber:(long long)arg1 isBiggerThenLocalVersionNumberOfBusiness:(id)arg2;
- (long long)readLocalVersionNumberForBusiness:(id)arg1;
- (long long)readUpdateFrequencyForBusiness:(id)arg1;
- (id)readLocalConfigForBusiness:(id)arg1;
- (_Bool)copyWebappCacheFromQQAppToDocuments;
- (_Bool)removeWebappCacheInDocuments;
- (void)markBundleFilesAlreadyCopied;
- (_Bool)alreadyCopiedBundleFilesToDocuments;
- (_Bool)hasNewVersionInQQAppBundle;
- (id)localFileContentForUrl:(id)arg1;
- (_Bool)hasLocalVersionForUrl:(id)arg1;
- (id)localPathForUrl:(id)arg1 withBid:(_Bool)arg2;
- (id)urlMapKeyForUrl:(id)arg1;
- (long long)bidForUrl:(id)arg1;
- (void)rebuildUrlMap;
- (void)handleUnprocessedUpdates;
- (void)checkUpdateHelperForBusiness:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)checkUpdateForBusiness:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)checkUpdateForBusiness:(id)arg1;
- (void)checkUpdateForUrl:(id)arg1;
- (int)localVersionOfBusiness:(id)arg1;
- (void)ensureCacheFolder0Exists;
- (_Bool)clearWebAppCacheFolder;
- (_Bool)initializeWebAppCacheInDocuments;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

