//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray;

@interface QWRecognizeModel : NSObject
{
    long long _recoState;
    NSArray *_resultList;
}

@property(retain, nonatomic) NSArray *resultList; // @synthesize resultList=_resultList;
@property(nonatomic) long long recoState; // @synthesize recoState=_recoState;
- (void).cxx_destruct;

@end

