//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSData, NSString;

@interface QWSongInfo : NSObject
{
    _Bool _collceted;
    unsigned long long _songid;
    NSString *_songName;
    NSString *_singerName;
    NSArray *_lyrics;
    NSData *_albumImage;
}

@property(nonatomic) _Bool collceted; // @synthesize collceted=_collceted;
@property(retain, nonatomic) NSData *albumImage; // @synthesize albumImage=_albumImage;
@property(retain, nonatomic) NSArray *lyrics; // @synthesize lyrics=_lyrics;
@property(retain, nonatomic) NSString *singerName; // @synthesize singerName=_singerName;
@property(retain, nonatomic) NSString *songName; // @synthesize songName=_songName;
@property(nonatomic) unsigned long long songid; // @synthesize songid=_songid;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;
- (id)init;

@end

