//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSDictionary, NSString, SongListItem;

@interface RadioProtocol : ProtocolBaseJason
{
    _Bool _refreshing;
    _Bool _firstPlaying;
    int _radioId;
    unsigned long long _channelType;
    SongListItem *_songListItem;
    NSDictionary *_rawJsonData;
    NSDictionary *_tjReportDic;
    NSString *_vcFrom;
}

@property(nonatomic) _Bool firstPlaying; // @synthesize firstPlaying=_firstPlaying;
@property(retain) NSString *vcFrom; // @synthesize vcFrom=_vcFrom;
@property(retain, nonatomic) NSDictionary *tjReportDic; // @synthesize tjReportDic=_tjReportDic;
@property(nonatomic) _Bool refreshing; // @synthesize refreshing=_refreshing;
@property(retain, nonatomic) NSDictionary *rawJsonData; // @synthesize rawJsonData=_rawJsonData;
@property(retain, nonatomic) SongListItem *songListItem; // @synthesize songListItem=_songListItem;
@property(nonatomic) int radioId; // @synthesize radioId=_radioId;
@property(nonatomic) unsigned long long channelType; // @synthesize channelType=_channelType;
- (void).cxx_destruct;
- (void)fromRawJsonData:(id)arg1;
- (void)onParseJasonData:(id)arg1;
- (id)getUrl;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (_Bool)needCheckDidSendRequest;
- (id)init;

@end

