//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RAPIScreen.h"

#import "IDSpellerDelegate-Protocol.h"

@class NSMutableArray, NSString, RAPISearchResultsScreen, RAPISearchScreenConfig, SearchScreenView;

@interface RAPISearchScreen : RAPIScreen <IDSpellerDelegate>
{
    NSMutableArray *_groupedSearchResultItems;
    SearchScreenView *_searchScreenView;
    RAPISearchScreenConfig *_config;
    RAPISearchResultsScreen *_searchResultsScreen;
}

@property(retain) RAPISearchResultsScreen *searchResultsScreen; // @synthesize searchResultsScreen=_searchResultsScreen;
@property(retain) RAPISearchScreenConfig *config; // @synthesize config=_config;
@property(retain) SearchScreenView *searchScreenView; // @synthesize searchScreenView=_searchScreenView;
@property(retain) NSMutableArray *groupedSearchResultItems; // @synthesize groupedSearchResultItems=_groupedSearchResultItems;
- (void).cxx_destruct;
- (void)delegate_onSearchStringChanged:(id)arg1;
- (id)delegate_getMoreLabelForGroup:(long long)arg1;
- (id)delegate_getLabelForEmptyList;
- (long long)delegate_getTargetScreenForRow:(long long)arg1 forGroup:(long long)arg2;
- (id)delegate_getStringForRow:(long long)arg1 forGroup:(long long)arg2;
- (long long)delegate_getItemCountForGroup:(long long)arg1;
- (id)delegate_getGroupLabelForGroup:(long long)arg1;
- (long long)delegate_getGroupCount;
- (id)delegate_getLoadingLabel;
- (_Bool)delegate_canProvideDataImmediately;
- (void)showLoadingMessage;
- (void)updateScreenContent;
- (_Bool)canProvideDataImmediately;
- (void)onFocusGained:(long long)arg1;
- (void)onViewAppeared;
- (id)getScreenDelegate;
- (void)spellerDidSelectOK:(id)arg1;
- (void)speller:(id)arg1 didSelectResultAtIndex:(long long)arg2;
- (void)speller:(id)arg1 didChangeText:(id)arg2;
- (id)initWithView:(id)arg1 andConfig:(id)arg2 andContext:(id)arg3 andSearchResultsScreen:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

