//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"
#import "SosoRecorderListener-Protocol.h"

@class NSArray, NSMutableArray, NSMutableData, NSMutableSet, NSString, RecognizedSong, SosoRecorder;

@interface RecognizeSession : NSObject <SosoRecorderListener, NSCoding>
{
    _Bool _isHumResult;
    _Bool _recording;
    _Bool _haveSendProcesFailedNotification;
    float _lastRequestDuration;
    float _lastRequestProb;
    long long _sessionId;
    long long _eRecognizeStatus;
    NSArray *_recognizedSongs;
    RecognizedSong *_recognizedSong;
    long long _startTime;
    double _firstRecordedTime;
    NSMutableData *_recordedDataCache;
    CDUnknownBlockType _statusChangeBlock;
    CDUnknownBlockType _recordVolumnBlock;
    SosoRecorder *_recorder;
    NSMutableArray *_timers;
    long long _recordedCountInBytes;
    NSString *_version;
    long long _lastRequestFeatureType;
    NSMutableSet *_timerUsedCountSet;
    long long _lastProtocolError;
}

+ (id)qafpVersion;
@property long long lastProtocolError; // @synthesize lastProtocolError=_lastProtocolError;
@property(retain) NSMutableSet *timerUsedCountSet; // @synthesize timerUsedCountSet=_timerUsedCountSet;
@property _Bool haveSendProcesFailedNotification; // @synthesize haveSendProcesFailedNotification=_haveSendProcesFailedNotification;
@property _Bool recording; // @synthesize recording=_recording;
@property float lastRequestProb; // @synthesize lastRequestProb=_lastRequestProb;
@property long long lastRequestFeatureType; // @synthesize lastRequestFeatureType=_lastRequestFeatureType;
@property float lastRequestDuration; // @synthesize lastRequestDuration=_lastRequestDuration;
@property(retain) NSString *version; // @synthesize version=_version;
@property long long recordedCountInBytes; // @synthesize recordedCountInBytes=_recordedCountInBytes;
@property(retain) NSMutableArray *timers; // @synthesize timers=_timers;
@property(retain) SosoRecorder *recorder; // @synthesize recorder=_recorder;
@property(copy) CDUnknownBlockType recordVolumnBlock; // @synthesize recordVolumnBlock=_recordVolumnBlock;
@property(copy) CDUnknownBlockType statusChangeBlock; // @synthesize statusChangeBlock=_statusChangeBlock;
@property(retain) NSMutableData *recordedDataCache; // @synthesize recordedDataCache=_recordedDataCache;
@property double firstRecordedTime; // @synthesize firstRecordedTime=_firstRecordedTime;
@property long long startTime; // @synthesize startTime=_startTime;
@property(retain) RecognizedSong *recognizedSong; // @synthesize recognizedSong=_recognizedSong;
@property(retain) NSArray *recognizedSongs; // @synthesize recognizedSongs=_recognizedSongs;
@property _Bool isHumResult; // @synthesize isHumResult=_isHumResult;
@property long long eRecognizeStatus; // @synthesize eRecognizeStatus=_eRecognizeStatus;
@property long long sessionId; // @synthesize sessionId=_sessionId;
- (void).cxx_destruct;
- (long long)compareByCreateTimeReversed:(id)arg1;
- (void)sendRecordedDataWithResult;
- (void)chooiceResult:(id)arg1;
- (_Bool)isFailedStatus:(long long)arg1;
- (void)abandon;
- (id)uploadFileTime;
- (id)uploadFileName;
- (void)uploadRecordedData:(_Bool)arg1;
- (void)onTimerSendFingerprintStopRecord:(_Bool)arg1 tryHum:(_Bool)arg2 timerIndex:(int)arg3;
- (void)removeTimerIndexAndCheckFinished:(int)arg1;
- (float)processedDuration;
- (void)onTimeoutRecognize;
- (int)powerOfData:(short *)arg1 count:(unsigned int)arg2;
- (int)normalizePower:(int)arg1 Min:(int)arg2 max:(int)arg3;
- (int)calcPowerOfData:(short *)arg1 count:(unsigned int)arg2;
- (void)onWaveData:(void *)arg1 packageNum:(unsigned int)arg2;
- (void)onRecorderStop;
- (void)onRecorderStart;
- (id)figerprintData;
- (id)recordedData;
- (void)setFigerprintData:(id)arg1;
- (void)flushCachedRecordedData;
- (void)addRecordedData:(id)arg1;
- (id)figerprintFilePath;
- (id)recordedFilePath;
- (id)saveFolder;
- (id)sessionKey;
- (void)clearAllTimers;
- (void)stopRecorder;
- (void)changeStatus:(long long)arg1;
- (long long)recognizeStatusByProtocolError:(long long)arg1;
- (void)rerecognizeWithBlock:(CDUnknownBlockType)arg1;
- (int)failedClickStatus:(long long)arg1;
- (void)recognizeFailed:(long long)arg1;
- (void)recognizeSuccess:(id)arg1 isHumResult:(_Bool)arg2;
- (void)recognizeSuccess:(id)arg1 isHumResult:(_Bool)arg2 withTimerIndex:(unsigned long long)arg3;
- (void)startRecognizeWithError:(id *)arg1 statusChangeBlock:(CDUnknownBlockType)arg2 recordVolumnBlock:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

