//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

#import "ImageManagerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"

@class ChannelItemKey, MVInfo, NSString, SongListItem;
@protocol ReleatedMVPlayDelegate;

@interface ReleatedMVVC : SkinViewController <UITableViewDataSource, UIScrollViewDelegate, ImageManagerDelegate>
{
    MVInfo *_currentPlayingVideo;
    SongListItem *_songListItem;
    ChannelItemKey *_channelItemKey;
    id <ReleatedMVPlayDelegate> _delegate;
    struct CGRect _viewFrame;
}

@property(nonatomic) id <ReleatedMVPlayDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) struct CGRect viewFrame; // @synthesize viewFrame=_viewFrame;
@property(retain, nonatomic) ChannelItemKey *channelItemKey; // @synthesize channelItemKey=_channelItemKey;
@property(retain, nonatomic) SongListItem *songListItem; // @synthesize songListItem=_songListItem;
@property(retain, nonatomic) MVInfo *currentPlayingVideo; // @synthesize currentPlayingVideo=_currentPlayingVideo;
- (void).cxx_destruct;
- (id)list;
- (void)mvListDataDidUpdate:(id)arg1;
- (void)onImagetWithInfo:(id)arg1 Image:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)reFreshWithNetworkDetection;
- (void)reFresh;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 withVideo:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

