//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolAuthBase.h"

@class ListBase;

@interface ReqSongRecordProtocol : ProtocolAuthBase
{
    ListBase *m_listBase;
    int m_eHasAnyMoreAdjust;
    int m_eReqMethodType;
    int m_iNewToMeCount;
    _Bool m_bForceRefresh;
}

@property(nonatomic) _Bool m_bForceRefresh; // @synthesize m_bForceRefresh;
@property(nonatomic) int m_iNewToMeCount; // @synthesize m_iNewToMeCount;
@property(nonatomic) int m_eReqMethodType; // @synthesize m_eReqMethodType;
@property(nonatomic) int m_eHasAnyMoreAdjust; // @synthesize m_eHasAnyMoreAdjust;
@property(retain, nonatomic) ListBase *m_listBase; // @synthesize m_listBase;
- (void).cxx_destruct;
- (_Bool)IsShouldDeleteFirstTimeLine:(id)arg1 andArrayDown:(id)arg2;
- (void)onParseXmlData:(struct _xmlDoc *)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getReqSongRecordId:(id)arg1;
- (id)getUrl;
- (id)init;

@end

