//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class RqdNetRequest;

@interface RqdStrategyQueryHandler : NSObject
{
    int queryInterval;
    RqdNetRequest *_req;
}

+ (id)sharedInstance;
@property(retain, nonatomic) RqdNetRequest *req; // @synthesize req=_req;
@property(nonatomic) int queryInterval; // @synthesize queryInterval;
- (void).cxx_destruct;
- (void)finishWithResponse:(id)arg1 reqPkg:(id)arg2;
- (void)failWithResponse:(id)arg1 reqPkg:(id)arg2;
- (void)failQuery:(id)arg1;
- (void)startStrategyQuery;
- (void)checkStrategyQuery:(double)arg1;
- (id)init;

@end

