//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SearchResultBaseTabVC, SearchSongTabVC, SongInfo;

@protocol SearchSongTabVCDelegate <NSObject>
- (struct CGRect)getTabVCFrame:(SearchResultBaseTabVC *)arg1;

@optional
- (void)searchSongTabVC:(SearchSongTabVC *)arg1 didSelectSong:(SongInfo *)arg2 assetsType:(int)arg3;
@end

