//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SongCell.h"

@class UIImageView, UILabel;

@interface SearchResultSongCell : SongCell
{
    _Bool _showAddToNextPlayButton;
    UILabel *_lyricLabel;
    UIImageView *_lyricIcon;
    UILabel *_songDescLabel;
    UIImageView *_autoSaveFinishView;
}

@property(retain, nonatomic) UIImageView *autoSaveFinishView; // @synthesize autoSaveFinishView=_autoSaveFinishView;
@property(nonatomic) _Bool showAddToNextPlayButton; // @synthesize showAddToNextPlayButton=_showAddToNextPlayButton;
@property(retain, nonatomic) UILabel *songDescLabel; // @synthesize songDescLabel=_songDescLabel;
@property(retain, nonatomic) UIImageView *lyricIcon; // @synthesize lyricIcon=_lyricIcon;
@property(retain, nonatomic) UILabel *lyricLabel; // @synthesize lyricLabel=_lyricLabel;
- (void).cxx_destruct;
- (void)resetSecondLevelLabelFrame;
- (void)setAutoSaveStatus:(int)arg1;
- (void)fillCellWithSongWithExpInfo:(id)arg1 assertType:(int)arg2;
- (void)_onNotifyColorStyleChanged:(id)arg1;
- (id)accessibilityLabel;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

