//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBase.h"

@class NSData, NSString;

@interface SendLogProtocol : ProtocolBase
{
    NSData *m_data;
    NSString *_logCase;
}

+ (void)sendData:(id)arg1 logCase:(id)arg2;
@property(retain, nonatomic) NSString *logCase; // @synthesize logCase=_logCase;
@property(retain, nonatomic) NSData *m_data; // @synthesize m_data;
- (void).cxx_destruct;
- (void)startWorkWithFinishBlock:(CDUnknownBlockType)arg1;
- (void)startWork;
- (_Bool)useBackQQUin;
- (void)onParseXmlData:(struct _xmlDoc *)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getUrl;
- (id)initWithData:(id)arg1;

@end

