//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSDate, SilentUserRecommendInfo;

@interface SilentUserRecommendConfig : NSObject <NSCoding>
{
    long long _hadShowCount;
    NSDate *_lastSilentDate;
    long long _silentedDayCount;
    long long _silentedLaunchCount;
    SilentUserRecommendInfo *_silentUserRecommendInfo;
}

@property(retain, nonatomic) SilentUserRecommendInfo *silentUserRecommendInfo; // @synthesize silentUserRecommendInfo=_silentUserRecommendInfo;
@property(nonatomic) long long silentedLaunchCount; // @synthesize silentedLaunchCount=_silentedLaunchCount;
@property(nonatomic) long long silentedDayCount; // @synthesize silentedDayCount=_silentedDayCount;
@property(retain, nonatomic) NSDate *lastSilentDate; // @synthesize lastSilentDate=_lastSilentDate;
@property(nonatomic) long long hadShowCount; // @synthesize hadShowCount=_hadShowCount;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;

@end

