//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface SilentUserRecommendItemInfo : NSObject <NSCoding>
{
    long long _recordId;
    long long _recordType;
    NSString *_title;
    NSString *_buttonTitle;
    NSString *_tjReport;
}

@property(retain, nonatomic) NSString *tjReport; // @synthesize tjReport=_tjReport;
@property(retain, nonatomic) NSString *buttonTitle; // @synthesize buttonTitle=_buttonTitle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long recordType; // @synthesize recordType=_recordType;
@property(nonatomic) long long recordId; // @synthesize recordId=_recordId;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;

@end

