//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, NSString, SimpleDownloadTask;

@protocol SimpleDownloadTaskDelegate <NSObject>
- (void)downloadTask:(SimpleDownloadTask *)arg1 didDownloadFailed:(NSError *)arg2;
- (void)downloadTask:(SimpleDownloadTask *)arg1 didDownloadSuccessWithFile:(NSString *)arg2;
@end

