//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QMNewInfo.h"

@class NSString;

@interface SingerBuluoNewInfo : QMNewInfo
{
    _Bool _hasPoint;
    int _singerId;
    int _bid;
    NSString *_msg;
}

+ (id)parseInfoFromJsonData:(id)arg1;
@property(retain, nonatomic) NSString *msg; // @synthesize msg=_msg;
@property(nonatomic) _Bool hasPoint; // @synthesize hasPoint=_hasPoint;
@property(nonatomic) int bid; // @synthesize bid=_bid;
@property(nonatomic) int singerId; // @synthesize singerId=_singerId;
- (void).cxx_destruct;
- (id)description;

@end

