//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@interface SingerListenSyncProtocol : ProtocolBaseJason
{
    _Bool isAdd;
    unsigned long long singerId;
    long long _timetag;
}

@property(nonatomic) long long timetag; // @synthesize timetag=_timetag;
@property(nonatomic) unsigned long long singerId; // @synthesize singerId;
@property(nonatomic) _Bool isAdd; // @synthesize isAdd;
- (_Bool)isSuccessfulReturnCode;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getUrl;
- (_Bool)canReportError;
- (int)cid;

@end

