//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSArray;

@interface SingerListenQueryProtocol : ProtocolBaseJason
{
    long long _oldTime;
    long long timetag;
    NSArray *singerList;
}

@property(retain, nonatomic) NSArray *singerList; // @synthesize singerList;
@property(nonatomic) long long timetag; // @synthesize timetag;
- (void).cxx_destruct;
- (id)translateSingerInfoFromJsonData:(id)arg1;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getUrl;
- (_Bool)canReportError;
- (int)cid;
- (id)initWithTimetag:(long long)arg1;

@end

