//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSMutableArray;

@interface SingerListenItem : NSObject <NSCoding, NSCopying>
{
    long long timeTag;
    unsigned long long uin;
    NSMutableArray *listenList;
}

+ (void)saveListenSingerlistWithItem:(id)arg1;
+ (id)loadListenSingerListByUin:(unsigned long long)arg1;
+ (id)getSingerListenFilePathForUin:(unsigned long long)arg1;
+ (id)unarchiveObjectFromFile:(id)arg1;
+ (void)archiveObject:(id)arg1 toFile:(id)arg2;
@property(retain) NSMutableArray *listenList; // @synthesize listenList;
@property unsigned long long uin; // @synthesize uin;
@property long long timeTag; // @synthesize timeTag;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

