//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseTabVC.h"

#import "ForceTouchCellDelegate-Protocol.h"
#import "SimilarRecAlbumCellDelegate-Protocol.h"
#import "SimilarRecMVCellDelegate-Protocol.h"
#import "SimilarRecSingerCellDelegate-Protocol.h"

@class ListBase, NSString, SingerCluster, UIView;

@interface SingerTabVC : BaseTabVC <SimilarRecMVCellDelegate, SimilarRecAlbumCellDelegate, SimilarRecSingerCellDelegate, ForceTouchCellDelegate>
{
    _Bool _bClickedSimilarRec;
    SingerCluster *_singerCluster;
    ListBase *_listBase;
    long long _tabType;
    UIView *_H5View;
    long long _tabbarToOpViewDistance;
    struct CGPoint _tableViewLastContentOffset;
}

@property long long tabbarToOpViewDistance; // @synthesize tabbarToOpViewDistance=_tabbarToOpViewDistance;
@property(retain) UIView *H5View; // @synthesize H5View=_H5View;
@property _Bool bClickedSimilarRec; // @synthesize bClickedSimilarRec=_bClickedSimilarRec;
@property struct CGPoint tableViewLastContentOffset; // @synthesize tableViewLastContentOffset=_tableViewLastContentOffset;
@property long long tabType; // @synthesize tabType=_tabType;
@property(retain) ListBase *listBase; // @synthesize listBase=_listBase;
@property(retain) SingerCluster *singerCluster; // @synthesize singerCluster=_singerCluster;
- (void).cxx_destruct;
- (void)customPopAction:(id)arg1 commitViewController:(id)arg2;
- (id)vcForForceTouchCell:(id)arg1;
- (void)didClickedSimilarRecSingerCell:(id)arg1 AtCloumn:(long long)arg2;
- (void)didClickedSimilarRecAlbumCell:(id)arg1 AtCloumn:(long long)arg2;
- (void)didClickedSimilarRecMVCell:(id)arg1 AtCloumn:(long long)arg2;
- (_Bool)isEnableSearch;
- (_Bool)shouldShowSearchSong;
- (_Bool)shouldShowShareSinger;
- (_Bool)showSingerInfoBtnInActionSheet:(id)arg1;
- (_Bool)moreDataIsLoading:(id)arg1;
- (void)processingLoadMoreAction:(id)arg1;
- (_Bool)hasMoreDataInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)totalTableCellsHeight;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)fillCell:(id)arg1 WithSong:(id)arg2;
- (void)handleBatchAction:(long long)arg1;
- (void)onSongsEdit:(id)arg1;
- (void)downloadAll;
- (long long)playButtonModeThisVC;
- (id)getH5TabUrl;
- (_Bool)isNeedSongTableView;
- (int)vcType;
- (id)_addRedMaskToCell:(id)arg1;
- (void)searchTabSong;
- (_Bool)isNeedSearchBar;
- (void)scrollViewDidScrollForDown:(id)arg1;
- (void)scrollViewDidScrollForUp:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setContentMinY:(double)arg1;
- (double)defaultContentOffsetY;
- (id)list;
- (void)reFresh;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithSingerCluster:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

