//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ImageManagerDelegate-Protocol.h"

@class NSString, SingerInfo, UIImageView, UILabel;
@protocol SingerHeaderViewDelegate;

@interface SingerHeaderView : UIView <ImageManagerDelegate>
{
    int _index;
    UILabel *_centerLabel;
    UIImageView *_iconImageView;
    UIImageView *_vipLogoView;
    SingerInfo *_singInfo;
    double _width;
    id <SingerHeaderViewDelegate> _delegate;
}

@property(nonatomic) int index; // @synthesize index=_index;
@property(nonatomic) __weak id <SingerHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double width; // @synthesize width=_width;
@property(retain, nonatomic) SingerInfo *singInfo; // @synthesize singInfo=_singInfo;
@property(retain, nonatomic) UIImageView *vipLogoView; // @synthesize vipLogoView=_vipLogoView;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UILabel *centerLabel; // @synthesize centerLabel=_centerLabel;
- (void).cxx_destruct;
- (void)headerTouch:(id)arg1;
- (void)onImagetWithInfo:(id)arg1 Image:(id)arg2;
- (void)updateUI;
- (id)initWithHeaderWidth:(double)arg1 songInfo:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

