//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ClusterInfo.h"

#import "RecentUsedProtocol-Protocol.h"

@class BuluoCluster, MusicCluster, NSArray, NSMutableArray, NSString, ShowCluster;

@interface SingerCluster : ClusterInfo <RecentUsedProtocol>
{
    unsigned long long singerId;
    int songNum;
    int albumNum;
    int folderNum;
    int mvNum;
    int listener;
    NSString *img;
    NSString *des;
    int needExtandInfo;
    long long songOrAlbumOrMV;
    MusicCluster *songs;
    MusicCluster *albums;
    MusicCluster *mvs;
    MusicCluster *songFolder;
    _Bool _isVip;
    _Bool _isFollow;
    int _orderNum;
    unsigned long long singerUin;
    NSString *_singerMid;
    long long _singerType;
    ShowCluster *_showInfo;
    BuluoCluster *_buluoInfo;
    NSString *_bigPic;
    unsigned long long _favSongNum;
    unsigned long long _favAlbumNum;
    unsigned long long _favSongListNum;
    NSString *_detailUrl;
    NSArray *_tabSelectors;
    NSArray *_tabComponents;
    NSMutableArray *_similarSingers;
    NSMutableArray *_similarMVs;
    NSMutableArray *_similarAlubms;
}

@property(retain, nonatomic) NSMutableArray *similarAlubms; // @synthesize similarAlubms=_similarAlubms;
@property(retain, nonatomic) NSMutableArray *similarMVs; // @synthesize similarMVs=_similarMVs;
@property(retain, nonatomic) NSMutableArray *similarSingers; // @synthesize similarSingers=_similarSingers;
@property(retain, nonatomic) NSArray *tabComponents; // @synthesize tabComponents=_tabComponents;
@property(retain) NSArray *tabSelectors; // @synthesize tabSelectors=_tabSelectors;
@property(retain, nonatomic) NSString *detailUrl; // @synthesize detailUrl=_detailUrl;
@property(nonatomic) unsigned long long favSongListNum; // @synthesize favSongListNum=_favSongListNum;
@property(nonatomic) unsigned long long favAlbumNum; // @synthesize favAlbumNum=_favAlbumNum;
@property(nonatomic) unsigned long long favSongNum; // @synthesize favSongNum=_favSongNum;
@property(retain, nonatomic) NSString *bigPic; // @synthesize bigPic=_bigPic;
@property(retain, nonatomic) BuluoCluster *buluoInfo; // @synthesize buluoInfo=_buluoInfo;
@property(retain, nonatomic) ShowCluster *showInfo; // @synthesize showInfo=_showInfo;
@property(nonatomic) _Bool isFollow; // @synthesize isFollow=_isFollow;
@property(nonatomic) _Bool isVip; // @synthesize isVip=_isVip;
@property(nonatomic) long long singerType; // @synthesize singerType=_singerType;
@property(nonatomic) int orderNum; // @synthesize orderNum=_orderNum;
@property(retain, nonatomic) NSString *singerMid; // @synthesize singerMid=_singerMid;
@property(retain, nonatomic) NSString *des; // @synthesize des;
@property(nonatomic) unsigned long long singerUin; // @synthesize singerUin;
@property(retain, nonatomic) MusicCluster *songFolder; // @synthesize songFolder;
@property(retain, nonatomic) MusicCluster *mvs; // @synthesize mvs;
@property(retain, nonatomic) MusicCluster *albums; // @synthesize albums;
@property(retain, nonatomic) MusicCluster *songs; // @synthesize songs;
@property(nonatomic) long long songOrAlbumOrMV; // @synthesize songOrAlbumOrMV;
@property(nonatomic) int needExtandInfo; // @synthesize needExtandInfo;
@property(retain, nonatomic) NSString *img; // @synthesize img;
@property(nonatomic) int folderNum; // @synthesize folderNum;
@property(nonatomic) int mvNum; // @synthesize mvNum;
@property(nonatomic) int songNum; // @synthesize songNum;
@property(nonatomic) int listener; // @synthesize listener;
@property(nonatomic) int albumNum; // @synthesize albumNum;
@property(nonatomic) unsigned long long singerId; // @synthesize singerId;
- (void).cxx_destruct;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

