//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

@interface SkinViewController (backGroundSong)
- (id)presentViewControllerFrom;
- (void)gotoWebpageWithURL:(id)arg1;
- (void)showBackGroundManagePage;
- (void)showBackGroundListPage;
- (void)showUpdateDiamondAlert;
- (void)setBackGroundSongsFinish:(id)arg1;
- (_Bool)setBackGroundSongsAction:(id)arg1 withAID:(id)arg2;
- (void)setBackGroundSongsAction:(id)arg1;
@end

