//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

@interface SkinViewController (Index)
- (void)index_scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)index_scrollViewDidEndDecelerating:(id)arg1;
- (void)index_scrollViewWillBeginDecelerating:(id)arg1;
- (void)index_scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)index_scrollViewWillBeginDragging:(id)arg1;
- (void)index_scrollViewDidScroll:(id)arg1;
- (void)delayCallTouchUpInside:(id)arg1;
- (void)onIndexTouchupInside:(struct CGPoint)arg1;
- (void)onIndexChanged:(id)arg1;
- (double)customIndexViewY;
- (struct CGRect)indexFrame;
- (void)createIndexView;
@end

