//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

@interface SkinViewController (BlankTips)
+ (void)showBannerTips:(id)arg1 WithIcon:(long long)arg2;
- (void)onTouchUpInsideReFreshWithNetworkDetection:(id)arg1;
- (void)hideNonStoppedBannerTips;
- (void)showNonStoppedBannerTips:(id)arg1 WithIcon:(long long)arg2;
- (void)dismissMsgView:(id)arg1;
- (void)showComMsgBoxWithMsg:(id)arg1 ArrowLoction:(struct CGPoint)arg2;
- (void)hideNetErrView;
- (void)resetNoNetImageTopOffset:(double)arg1;
- (void)showNoNetViewWithInfo1:(id)arg1 andInfo2:(id)arg2 iconName:(id)arg3 topOffset:(double)arg4 errorCode:(long long)arg5;
- (void)tappedCloseWifiOnlyButton:(id)arg1;
- (id)closeWiFiOnlyButton;
- (void)showNoNetViewWithInfo1:(id)arg1 andInfo2:(id)arg2 iconName:(id)arg3 errorCode:(long long)arg4;
- (struct CGRect)getNetErrShowFrame;
- (void)showNetErrView;
- (void)showNetErrWithResult:(int)arg1 withTopOffset:(double)arg2;
- (void)showNetErrWithResult:(int)arg1;
- (void)hideLoadingView;
- (id)loadingViewText;
- (void)showAllTypeLoadingView:(_Bool)arg1 height:(double)arg2;
- (void)adjustPositionToFit:(id)arg1;
- (void)showCustomLoadingViewWithHeight:(double)arg1;
- (void)showLoadingView;
- (_Bool)isBannerTipsShow;
- (void)finishedTips;
- (void)dismissTipsWithAnimated:(_Bool)arg1;
- (void)dismissTips;
- (void)changeTipsEnable;
- (void)hideBannerTipsImmedirtery;
- (void)hideBannerTips;
- (void)showBannerTips:(id)arg1 WithIcon:(long long)arg2 Force:(_Bool)arg3;
- (void)showBannerTips:(id)arg1 WithIcon:(long long)arg2 withTipsType:(long long)arg3 withForceClearQueue:(_Bool)arg4;
- (void)showBannerTips:(id)arg1 WithIcon:(long long)arg2;
- (void)showBannerTips:(id)arg1 WithIcon:(long long)arg2 withActionTitle:(id)arg3 withTipsDisappearTime:(int)arg4 withEventBlock:(CDUnknownBlockType)arg5;
- (void)showBannerTips:(id)arg1 WithIcon:(long long)arg2 withActionTitle:(id)arg3 withEventBlock:(CDUnknownBlockType)arg4;
- (void)showChannelBannerTips:(id)arg1 WithIcon:(long long)arg2 Force:(_Bool)arg3;
- (void)showChannelBannerTips:(id)arg1 WithIcon:(long long)arg2;
- (id)createNewBannerTips:(id)arg1 WithIcon:(long long)arg2;
- (id)createIcon:(long long)arg1;
- (_Bool)showContinuousBannerTips;
- (void)freshAllExceptionView;
- (void)hideAll;
- (void)showTable;
- (void)fresh:(id)arg1;
- (void)addEmptyView:(id)arg1;
- (id)emptyViewText;
- (void)showEmptyView;
- (id)createEmptyViewButton:(id)arg1 sel:(SEL)arg2;
- (id)noNetViewCustomButton;
- (id)emptyViewCustomButton;
- (id)emptyViewBgText2;
- (id)emptyViewBgText;
- (id)emptyViewBgImage;
@end

