//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

#import "ChannelAlertViewDelegate-Protocol.h"

@class NSString;

@interface SkinViewController (ChannelExtension) <ChannelAlertViewDelegate>
- (void)handleReadyToPlayChannelItem:(id)arg1 channelItem:(id)arg2;
- (void)handleReadyToPlayChannelItemError:(id)arg1 channelItemKey:(id)arg2;
- (void)readyToPlayChannelItem:(id)arg1;
- (void)reallyPlayChannel:(id)arg1;
- (void)reallyPlayChannel:(id)arg1 fromSong:(id)arg2;
- (void)navigateToMyCircle:(unsigned long long)arg1;
- (void)_animateTitleBackFromNavBarWithAnimate:(_Bool)arg1;
- (void)_animateTitleBackFromNavBar;
- (void)_animateTitleToNavBarWithText:(id)arg1 withAnimate:(_Bool)arg2;
- (void)_animateTitleToNavBarWithText:(id)arg1;
- (_Bool)reachMaxLimited;
- (void)showWebViewWithPageUrl:(id)arg1 defaultTitle:(id)arg2;
- (void)navigateToSingerVC:(id)arg1 coverPage:(long long)arg2;
- (void)navigateToSingerVC:(id)arg1;
- (id)getDestViewControllerByCreator:(id)arg1;
- (void)navigateToPersonalCenter:(id)arg1 fromVC:(id)arg2;
- (void)channelAlertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)jumpToViewByMid:(int)arg1 AndKey1:(id)arg2 AndKey2:(id)arg3 AndKey3:(id)arg4 AndKey4:(int)arg5 AndKey5:(int)arg6 AndKey6:(int)arg7 AndKey7:(id)arg8 bNeedAnimated:(_Bool)arg9 fromVC:(id)arg10;
- (_Bool)playChannel:(id)arg1;
- (_Bool)navigateToChannel:(id)arg1 fromvc:(id)arg2 animated:(_Bool)arg3;
- (_Bool)navigateToChannel:(id)arg1 fromvc:(id)arg2;
- (void)handleFetchRadioListStatus:(long long)arg1 radioProtocol:(id)arg2 protocolError:(id)arg3;
- (id)createFrom:(id)arg1;
- (void)setCircleJumpSongToController:(id)arg1;
- (_Bool)navigateToChannel:(id)arg1;
- (void)showVipChannelStuckAlert;
- (void)handleVipChannel:(id)arg1;
- (void)handleExpiredChannel:(id)arg1;
- (_Bool)isExpiredChannel:(id)arg1;
- (_Bool)isValidChannel:(id)arg1;
- (_Bool)isSamePlayingList:(id)arg1;
- (void)showTips:(id)arg1;
- (void)addBottomGreenLine;
- (void)addChannelLayoutTableViewWithFrame:(struct CGRect)arg1 inView:(id)arg2 bottomShadow:(_Bool)arg3;
- (struct CGRect)_defaultChannelLayoutTableViewFrame;
- (void)addChannelLayoutShadowTableView;
- (void)addChannelLayoutTableView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

