//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

@interface SkinViewController (Anchor)
- (void)refreshAnchorButton;
- (struct CGPoint)anchorButtonPosition:(struct CGSize)arg1;
- (void)notifyToAnchorWhenScrollViewDidBeginDragging:(id)arg1;
- (long long)anchorButtonScrollPosition;
- (void)anchorButtonClicked:(id)arg1;
- (id)playingIndexPath;
- (void)hideAnchorButton;
- (void)showAnchorViewWhenNeed;
@end

