//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

#import "HPGrowingTextViewDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class FeedCommentInfo, HPGrowingTextView, MusicCircleFeed, NSMutableArray, NSString, UIView;

@interface SkinViewController_Comment : SkinViewController <HPGrowingTextViewDelegate, UIActionSheetDelegate>
{
    _Bool isRecomment;
    HPGrowingTextView *textView;
    UIView *containerView;
    MusicCircleFeed *commentFeed;
    NSMutableArray *requestArray;
    FeedCommentInfo *commentInfo;
    FeedCommentInfo *lastcommentInfo;
    UIView *_commentSender;
}

@property(retain, nonatomic) UIView *commentSender; // @synthesize commentSender=_commentSender;
@property(nonatomic) _Bool isRecomment; // @synthesize isRecomment;
@property(retain, nonatomic) FeedCommentInfo *lastcommentInfo; // @synthesize lastcommentInfo;
@property(retain, nonatomic) FeedCommentInfo *commentInfo; // @synthesize commentInfo;
@property(retain, nonatomic) NSMutableArray *requestArray; // @synthesize requestArray;
@property(retain, nonatomic) MusicCircleFeed *commentFeed; // @synthesize commentFeed;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView;
@property(retain, nonatomic) HPGrowingTextView *textView; // @synthesize textView;
- (void).cxx_destruct;
- (_Bool)growingTextView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)growingTextView:(id)arg1 willChangeHeight:(float)arg2;
- (_Bool)validateInput;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)sendComment:(id)arg1;
- (void)resignTextView;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (_Bool)isNeedHideContainViewWhenKeyBoardHide;
- (void)showDeleteActionSheet:(id)arg1 feedInfo:(id)arg2;
- (void)reCommentOnComment:(id)arg1 feed:(id)arg2 withSender:(id)arg3;
- (void)startCommentOnFeed:(id)arg1 withSender:(id)arg2;
- (void)buildTextViewUI;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

