//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SkinViewController.h"

@interface SkinViewController (more)
- (void)setRedPointStyle:(id)arg1 withCellHeight:(double)arg2 withLabel:(id)arg3;
- (void)setLabelOriginY:(id)arg1 withCellHeight:(double)arg2;
- (void)setCellRightLabelStyle:(id)arg1 withCellHeight:(double)arg2;
- (void)setCellRightLabelStyle:(id)arg1;
- (void)showWXMissView:(int)arg1;
- (void)setTableViewFooterTextStyle:(id)arg1;
- (void)setTableViewHeaderTextStyle:(id)arg1;
- (id)setTableViewHeaderTitle:(id)arg1;
- (id)moreRootSwitchCellRowForTableView:(id)arg1 AtIndexPath:(id)arg2;
- (id)moreRootCellRowForTableView:(id)arg1 AtIndexPath:(id)arg2;
@end

