//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SongListBaseViewController.h"

@interface SongListBaseViewController (action)
- (void)setDnotLike;
- (void)setPrefer;
- (void)_showSelectDownloadQualityActionSheet:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)downloadAll;
- (id)batchDownlaodSongs;
- (void)addToMyFavorList:(id)arg1;
- (void)shareSinger;
- (void)shareCurrentList;
- (void)actionSheetAutoDownChange:(id)arg1;
- (void)actionSheetWillHide:(id)arg1;
- (id)defaultCreateNewFolderName;
- (void)actionSheet:(id)arg1 actionSheetButtonClickedAtIndex:(long long)arg2;
- (void)addToMyFavor;
- (void)onSongsEdit:(id)arg1;
- (void)onTouchUpInsideEdit:(id)arg1;
- (void)turnOnAutoSave;
- (void)offlineSwitchChanged:(id)arg1;
- (_Bool)isAutoSwtichOn;
- (void)setAutoSwith:(id)arg1;
- (_Bool)_isSongFolderDetail;
- (_Bool)shouldShowComment;
- (_Bool)isCanEditSong;
- (_Bool)isCanDownloadAll;
- (_Bool)isEnableComment;
- (_Bool)isEnableSearch;
- (_Bool)isEnableShare;
- (_Bool)isEnableAddTo;
- (void)showActionSheet:(id)arg1;
- (_Bool)shouldShowPerfreSet;
- (_Bool)shouldShowDoNotLike;
- (_Bool)shouldShowSearchSong;
- (_Bool)shouldShowShareSinger;
- (_Bool)showShareSongListItem;
- (_Bool)showCollectToOwnFolder;
- (void)initActionIndex;
@end

