//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray;

@interface SpeedLimitMode : NSObject
{
    long long _timeDistanceToUnlimtDonloadNextBlock;
    NSArray *_blockEndTimes;
    long long _keepAliveSpeedInBytesPerSecond;
}

@property long long keepAliveSpeedInBytesPerSecond; // @synthesize keepAliveSpeedInBytesPerSecond=_keepAliveSpeedInBytesPerSecond;
@property(retain) NSArray *blockEndTimes; // @synthesize blockEndTimes=_blockEndTimes;
@property long long timeDistanceToUnlimtDonloadNextBlock; // @synthesize timeDistanceToUnlimtDonloadNextBlock=_timeDistanceToUnlimtDonloadNextBlock;
- (void).cxx_destruct;
- (long long)nextNearbyBlockEndTimeByTime:(double)arg1;
- (_Bool)shouldLimitSpeed:(double)arg1 existDataDuration:(double)arg2 nextBlockEndTime:(long long)arg3 nextNextBlockEndTime:(long long)arg4;
- (long long)nextSpeedInBytesPerSecond:(double)arg1 existDataDuration:(double)arg2;
- (void)setKeepAliveSpeedInBytedPerSecond:(long long)arg1;
- (id)initWithTimeDistance:(long long)arg1 blockEndTimes:(id)arg2;

@end

