//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface SQLSelectTargetColumnInfo : NSObject
{
    _Bool _needToCreateInstance;
    NSString *_columnName;
    CDUnknownBlockType _setterBlock;
}

@property(copy, nonatomic) CDUnknownBlockType setterBlock; // @synthesize setterBlock=_setterBlock;
@property(nonatomic) _Bool needToCreateInstance; // @synthesize needToCreateInstance=_needToCreateInstance;
@property(copy, nonatomic) NSString *columnName; // @synthesize columnName=_columnName;
- (void).cxx_destruct;

@end

