//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ChannelItem, SquareFocusScrollView;

@protocol SquareFocusScrollViewDelegate <NSObject>

@optional
- (void)requestToPlayChannel:(ChannelItem *)arg1;
- (void)SquareFocusScrollViewDidScroll:(SquareFocusScrollView *)arg1;
- (void)SquareFocusScrollView:(SquareFocusScrollView *)arg1 longPressed:(ChannelItem *)arg2;
- (void)SquareFocusScrollView:(SquareFocusScrollView *)arg1 didSelectItem:(ChannelItem *)arg2;
@end

