//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SquareFocusScrollView, SquareFocusView;

@protocol SquareFocusScrollViewDataSource <NSObject>
- (void)SquareFocusScrollView:(SquareFocusScrollView *)arg1 paintView:(SquareFocusView *)arg2 atPage:(long long)arg3;
- (long long)numberOfPagesForFocusScrollView:(SquareFocusScrollView *)arg1;
@end

