//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ChannelBaseTabVC.h"

#import "SquareFocusScrollViewDelegate-Protocol.h"

@class ChannelV4Category, NSMutableArray, NSString, SquareFocusScrollView;

@interface SquareTabVC : ChannelBaseTabVC <SquareFocusScrollViewDelegate>
{
    _Bool _isFocusViewShowInScreen;
    _Bool _loadingMore;
    NSMutableArray *_bannerDataArray;
    ChannelV4Category *_categrotyData;
    ChannelV4Category *_lastCategrotyData;
    SquareFocusScrollView *_squareFocusScrollView;
}

@property(retain, nonatomic) SquareFocusScrollView *squareFocusScrollView; // @synthesize squareFocusScrollView=_squareFocusScrollView;
@property(nonatomic) _Bool loadingMore; // @synthesize loadingMore=_loadingMore;
@property(retain, nonatomic) ChannelV4Category *lastCategrotyData; // @synthesize lastCategrotyData=_lastCategrotyData;
@property(retain, nonatomic) ChannelV4Category *categrotyData; // @synthesize categrotyData=_categrotyData;
@property(retain) NSMutableArray *bannerDataArray; // @synthesize bannerDataArray=_bannerDataArray;
@property _Bool isFocusViewShowInScreen; // @synthesize isFocusViewShowInScreen=_isFocusViewShowInScreen;
- (void).cxx_destruct;
- (_Bool)moreDataIsLoading:(id)arg1;
- (void)processingLoadMoreAction:(id)arg1;
- (_Bool)hasMoreDataInTableView:(id)arg1;
- (void)SquareFocusScrollView:(id)arg1 didSelectItem:(id)arg2;
- (void)onNotifyUserLanguageChanged:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)requestToPlayChannel:(id)arg1;
- (void)requestToShowChannel:(id)arg1;
- (void)didClickDarenFollowButton:(id)arg1;
- (void)didSortButton:(id)arg1;
- (void)didClickMoreBtn:(id)arg1;
- (void)didClickCategoryBtn:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)updateBannerViewState;
- (void)_channelSquareDataDidUpdate:(id)arg1;
- (void)reFreshWithCategory:(id)arg1 andIsForce:(_Bool)arg2;
- (void)reFreshWithCategoryId:(long long)arg1;
- (void)reFreshWithCategory:(id)arg1;
- (void)reFresh;
- (int)vcType;
- (void)addPlayChannelStat:(id)arg1;
- (void)willActiveCurrentTab;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

