//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class ChannelItem, QMLabel, QMWebImageView, UIActivityIndicatorView, UIButton, UIButtonWithImageInfo, UIImageView, UILabel, UIView;
@protocol SquareFocusViewDelagete;

@interface SquareFocusView : UIControl
{
    QMWebImageView *_squareFocusImageView;
    UIView *_channelInfoContainerView;
    ChannelItem *_channelItem;
    id <SquareFocusViewDelagete> _delegate;
    UIImageView *_defaultImageView;
    UIButtonWithImageInfo *_buttonWithImage;
    UIActivityIndicatorView *_loadingIndiView;
    UIButton *_songListPlayingButton;
    UILabel *_mainTitle;
    QMLabel *_descLabel;
}

@property(retain, nonatomic) QMLabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UILabel *mainTitle; // @synthesize mainTitle=_mainTitle;
@property(retain, nonatomic) UIButton *songListPlayingButton; // @synthesize songListPlayingButton=_songListPlayingButton;
@property(retain, nonatomic) UIActivityIndicatorView *loadingIndiView; // @synthesize loadingIndiView=_loadingIndiView;
@property(retain, nonatomic) UIButtonWithImageInfo *buttonWithImage; // @synthesize buttonWithImage=_buttonWithImage;
@property(retain, nonatomic) UIImageView *defaultImageView; // @synthesize defaultImageView=_defaultImageView;
@property(nonatomic) __weak id <SquareFocusViewDelagete> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) ChannelItem *channelItem; // @synthesize channelItem=_channelItem;
@property(retain, nonatomic) UIView *channelInfoContainerView; // @synthesize channelInfoContainerView=_channelInfoContainerView;
@property(retain, nonatomic) QMWebImageView *squareFocusImageView; // @synthesize squareFocusImageView=_squareFocusImageView;
- (void).cxx_destruct;
- (void)reloadSongListPlayingStatus;
- (void)playStatusDidChange:(id)arg1;
- (void)playListDidChange:(id)arg1;
- (void)doClickPlayingButton:(id)arg1;
- (void)imageButtonDidTap:(id)arg1;
- (id)trimImage:(id)arg1;
- (id)imageUrlForItem:(id)arg1;
- (void)updateChannelInfoViewWithChannelItem:(id)arg1;
- (void)addChannelInfoView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

