//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSArray;

@interface SubscribeProtocol : ProtocolBaseJason
{
    _Bool _setSeq;
    NSArray *_subscribeChannelItems;
    NSArray *_unsubscribeChannelItems;
    long long _timetag;
}

@property(nonatomic) _Bool setSeq; // @synthesize setSeq=_setSeq;
@property(nonatomic) long long timetag; // @synthesize timetag=_timetag;
@property(retain, nonatomic) NSArray *unsubscribeChannelItems; // @synthesize unsubscribeChannelItems=_unsubscribeChannelItems;
@property(retain, nonatomic) NSArray *subscribeChannelItems; // @synthesize subscribeChannelItems=_subscribeChannelItems;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (_Bool)canReportError;
- (id)getUrl;
- (int)cid;

@end

