//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface SuperSoundManager : NSObject
{
    _Bool _isEnable;
    float _currentIntensity;
    int _currentEffectType;
    void *_superSoundInstance;
}

+ (id)sharedManager;
@property(nonatomic) void *superSoundInstance; // @synthesize superSoundInstance=_superSoundInstance;
@property(nonatomic) _Bool isEnable; // @synthesize isEnable=_isEnable;
@property(nonatomic) int currentEffectType; // @synthesize currentEffectType=_currentEffectType;
@property(nonatomic) float currentIntensity; // @synthesize currentIntensity=_currentIntensity;
- (int)effectTypeForPlayStat;
- (void)processPCM:(void *)arg1 dataLength:(unsigned int)arg2;
- (float)getSliderValueFromIntensity:(float)arg1 andEffectType:(int)arg2;
- (void)setIntensityThroughSliderValue:(float)arg1 forEffectType:(int)arg2;
- (void)setIntensity:(float)arg1 forEffectType:(int)arg2;
- (void)setEffectType:(int)arg1;
- (float)getDefaultIntensityForEffectType:(int)arg1;
- (void)loadLastestIntensityAndEffectType;
- (void)createSuperSoundInstanceWithSampleRate:(int)arg1 andChannels:(int)arg2;
- (int)initSuperSound;
- (id)init;

@end

