//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TADCDESUtil : NSObject
{
}

+ (id)desDataWithEBC:(id)arg1 key:(id)arg2 encrypt:(_Bool)arg3;
+ (id)desDataWithCBC:(id)arg1 key:(id)arg2 encrypt:(_Bool)arg3 iv:(const char *)arg4;

@end

