//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIVisualEffectView.h>

@interface TADVisualEffectView : UIVisualEffectView
{
    _Bool _passThrough;
}

@property(nonatomic) _Bool passThrough; // @synthesize passThrough=_passThrough;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)init;

@end

