//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString;

@interface TreeNode : NSObject
{
    TreeNode *p_node;
    NSMutableArray *children;
    id data;
    NSString *title;
    NSString *key;
    _Bool expanded;
    _Bool visited;
}

+ (void)getNodes:(id)arg1:(id)arg2;
+ (id)findNodeByKey:(id)arg1:(id)arg2;
@property(nonatomic) _Bool visited; // @synthesize visited;
@property(nonatomic) _Bool expanded; // @synthesize expanded;
@property(retain, nonatomic) NSString *key; // @synthesize key;
@property(retain, nonatomic) NSString *title; // @synthesize title;
@property(retain, nonatomic) id data; // @synthesize data;
@property(retain, nonatomic) NSMutableArray *children; // @synthesize children;
@property(retain, nonatomic) TreeNode *p_node; // @synthesize p_node;
- (void).cxx_destruct;
- (id)description;
- (_Bool)hasChildren;
- (int)deep;
- (int)childrenCount;
- (void)addChild:(id)arg1;
- (id)init;

@end

