//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary;

@interface TTEntityTables : NSObject
{
    NSDictionary *_iso88591;
}

@property(readonly, nonatomic) NSDictionary *iso88591; // @synthesize iso88591=_iso88591;
- (void)dealloc;

@end

