//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TVKMakeJsonData.h"

@class NSString;

@interface TVKVideoKeyDataController : TVKMakeJsonData
{
    long long videoDataType;
    NSString *keysName;
}

@property(retain, nonatomic) NSString *keysName; // @synthesize keysName;
@property(nonatomic) long long videoDataType; // @synthesize videoDataType;
- (void)enscapeData:(id)arg1 withDataUserInfo:(id)arg2;
- (id)initWithInterfaceType:(long long)arg1;
- (void)dealloc;

@end

