//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSObject;

@interface UICellButton : UIButton
{
    NSObject *_btnObject;
}

@property(retain, nonatomic) NSObject *btnObject; // @synthesize btnObject=_btnObject;
- (void).cxx_destruct;
- (void)setIndicatorImage:(_Bool)arg1;
- (void)setSubLabelViewsTextColor:(id)arg1;
- (void)setHighlighted:(_Bool)arg1;

@end

