//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIColor.h>

@interface UIColor (TTCategory)
+ (id)colorWithHue:(double)arg1 saturation:(double)arg2 value:(double)arg3 alpha:(double)arg4;
- (double)value;
- (double)saturation;
- (double)hue;
- (id)shadow;
- (id)highlight;
- (id)addHue:(double)arg1 saturation:(double)arg2 value:(double)arg3;
- (id)copyWithAlpha:(double)arg1;
- (id)multiplyHue:(double)arg1 saturation:(double)arg2 value:(double)arg3;
@end

