//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (DBImageColor)
- (id)lighterColorForColor:(id)arg1;
- (id)secondaryColorFromBackgroundColor:(id)arg1 primaryColor:(id)arg2;
- (id)primaryColorFromBackgroundColor:(id)arg1;
- (id)averageColorForImage:(id)arg1;
- (id)footerAverageColor;
- (id)headerAverageColor;
- (id)averageColor;
- (id)getImprovedColorFromColor:(id)arg1 backgroundColor:(id)arg2;
- (float)squareDistanceInRGBSpaceBetweenColorA:(id)arg1 colorB:(id)arg2;
- (id)getSubImageWithRect:(struct CGRect)arg1;
- (id)getColorArrayWithCount:(int)arg1;
@end

