//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (TADBlurView)
- (id)tad_blurredImageWithRadius:(double)arg1 iterations:(unsigned long long)arg2 tintColor:(id)arg3;
@end

