//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (Load)
+ (id)getXPath:(id)arg1 scale:(long long)arg2;
+ (id)imageWithContentsOfFileChange:(id)arg1;
+ (void)load;
- (id)initWithContentsOfFileChange:(id)arg1;
@end

