//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView;

@interface UIViewWaves : UIView
{
    UIImageView *imageViewWave1;
    UIImageView *imageViewWave2;
    UIImageView *imageViewWave3;
}

- (void).cxx_destruct;
- (void)setInterfaceOfPower:(int)arg1;
- (void)setRealTimePower:(int)arg1;
- (void)resetWaves;
- (id)initWithFrame:(struct CGRect)arg1;

@end

