//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class UpgradeInfo;

@interface UnifiedUpgradeProtocol : ProtocolBaseJason
{
    UpgradeInfo *_upgradeInfo;
}

@property(retain, nonatomic) UpgradeInfo *upgradeInfo; // @synthesize upgradeInfo=_upgradeInfo;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (_Bool)canReportError;
- (id)getUrl;
- (int)cid;

@end

