//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, UrlAudioData;

@protocol UrlAudioDataDelegate <NSObject>
- (_Bool)needMoreData;
- (void)onNeedUpdateErrorCode:(int)arg1;
- (void)onUpdateCDNIp:(NSString *)arg1;
- (void)onHijacked:(_Bool)arg1;
- (void)onURLChanged:(UrlAudioData *)arg1 urlIndex:(int)arg2 changeURLCount:(int)arg3;
@end

