//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

#import "ImageManagerDelegate-Protocol.h"

@class NSString;

@interface URLImageView : UIImageView <ImageManagerDelegate>
{
    _Bool _bBubbleUrl;
    NSString *_url;
    NSString *_defaultImageName;
}

@property _Bool bBubbleUrl; // @synthesize bBubbleUrl=_bBubbleUrl;
@property(retain) NSString *defaultImageName; // @synthesize defaultImageName=_defaultImageName;
@property(retain) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (void)onImagetWithInfo:(id)arg1 Image:(id)arg2;
- (_Bool)refresh;
- (_Bool)setBubbleUrl:(id)arg1 withDefaultBubbleImg:(id)arg2 fliped:(_Bool)arg3;
- (_Bool)setURL:(id)arg1 defaultImage:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

