//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface UsedSpaceHelper : NSObject
{
}

+ (void)_clearAppThemeExceptCurrent;
+ (void)_emptyFolder:(id)arg1 emptyDir:(_Bool)arg2;
+ (void)_emptyRecentPlayList;
+ (void)_clearFirstPieceCacheFolder;
+ (void)clearUsedSpaceWithTypes:(long long)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)calculateUsedSpaceOfTypes:(long long)arg1 completion:(CDUnknownBlockType)arg2;
+ (id)usedSpaceItemForType:(long long)arg1 inItems:(id)arg2;
+ (id)literalSizeStringForUsedSpace:(long long)arg1;

@end

