//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface Version : NSObject
{
}

+ (id)getVersionStringWithBuild;
+ (int)innerBuildNumber;
+ (_Bool)isReviewerUsing;
+ (_Bool)isInReview;
+ (id)osVersion;
+ (_Bool)rdmVersion;
+ (_Bool)grayVersion;
+ (id)translateUnformatVersionToDotVersion:(id)arg1;
+ (id)transLateDotVersionToUnformatVersion:(id)arg1;
+ (id)getCurrentVersionString;
+ (id)getAppVersionString;
+ (id)appVersionInUserAgent;
+ (int)getSvnVersion;
+ (id)getQQMusicVersion:(_Bool)arg1;

@end

