//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface VideoSetData : NSObject
{
    NSString *videoSetBrief;
    NSString *videoSetId;
    NSString *videoSetLogo;
    NSString *videoSetName;
}

@property(retain, nonatomic) NSString *videoSetName; // @synthesize videoSetName;
@property(retain, nonatomic) NSString *videoSetLogo; // @synthesize videoSetLogo;
@property(retain, nonatomic) NSString *videoSetId; // @synthesize videoSetId;
@property(retain, nonatomic) NSString *videoSetBrief; // @synthesize videoSetBrief;
- (id)initWithBrief:(id)arg1 withSetId:(id)arg2 withSetLogo:(id)arg3 withSetName:(id)arg4;

@end

