//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol VideoPlayerControlViewDelegate <NSObject>
- (void)showBannerTips:(NSString *)arg1 WithIcon:(long long)arg2;
- (int)getCurrentClarityType;
- (void)pipClicked;
- (void)downloadMV;
- (void)freeFlowCheck;
- (void)changeClarity:(NSString *)arg1;
- (void)shareMV;
- (void)setSeekPlayTime:(double)arg1;
- (void)setMovieScalingMode:(int)arg1;
- (void)setVolume:(float)arg1;
- (void)playSongAtIndex:(int)arg1;
- (void)stop;
- (void)pause;
- (void)play;
@end

