//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "AVPictureInPictureControllerDelegate-Protocol.h"
#import "TVKMediaPlaybackDelegate-Protocol.h"

@class AVPictureInPictureController, ChannelItem, MVInfo, NSArray, NSString, NSTimer, SingleHourglass, StatInfo, TVKMediaPlayer, UIViewController, VideoPlayerViewController;

@interface VideoPlayerDelegateV2 : NSObject <TVKMediaPlaybackDelegate, AVPictureInPictureControllerDelegate>
{
    int _curPlayIndex;
    int _lastIndex;
    MVInfo *_curMVInfo;
    NSString *_title;
    _Bool _forwardAction;
    _Bool _netWorkTipFlag;
    _Bool _netBgNotify;
    _Bool _goToNextMV;
    _Bool _statusBarHide;
    _Bool _userStop;
    _Bool _recoverFromPiP;
    MVInfo *_needPlayMVInfo;
    UIViewController *_mvPlayerVC;
    StatInfo *_statInfo;
    NSString *_fromType;
    SingleHourglass *_totalHourglass;
    SingleHourglass *_hourglass;
    SingleHourglass *_bufferingHourglass;
    unsigned long long _iBufferTimesCount;
    NSTimer *_timer;
    double _bufferTime;
    ChannelItem *_channelItem;
    _Bool _skippingAD;
    _Bool _didEnterBackgroud;
    _Bool _isShowVideoView;
    _Bool _isLocalMV;
    _Bool _isManualTrigPause;
    _Bool _isInPip;
    TVKMediaPlayer *_mvPlayer;
    NSArray *_mvList;
    VideoPlayerViewController *_videoPlayerViewController;
    NSString *_uin;
    UIViewController *_lastModalVC;
    AVPictureInPictureController *_pipctrller;
}

+ (id)sharedVideoPlayerDelegate;
@property(retain, nonatomic) AVPictureInPictureController *pipctrller; // @synthesize pipctrller=_pipctrller;
@property(readonly, nonatomic) _Bool isInPip; // @synthesize isInPip=_isInPip;
@property(nonatomic) _Bool isManualTrigPause; // @synthesize isManualTrigPause=_isManualTrigPause;
@property(nonatomic) __weak UIViewController *lastModalVC; // @synthesize lastModalVC=_lastModalVC;
@property(retain, nonatomic) MVInfo *curMVInfo; // @synthesize curMVInfo=_curMVInfo;
@property(nonatomic) _Bool isLocalMV; // @synthesize isLocalMV=_isLocalMV;
@property(retain, nonatomic) NSString *uin; // @synthesize uin=_uin;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) VideoPlayerViewController *videoPlayerViewController; // @synthesize videoPlayerViewController=_videoPlayerViewController;
@property(retain, nonatomic) NSArray *mvList; // @synthesize mvList=_mvList;
@property(retain, nonatomic) TVKMediaPlayer *mvPlayer; // @synthesize mvPlayer=_mvPlayer;
- (void).cxx_destruct;
- (void)switchToFullScreenPlayMode:(_Bool)arg1;
- (void)pictureInPictureController:(id)arg1 restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:(CDUnknownBlockType)arg2;
- (void)pictureInPictureControllerDidStopPictureInPicture:(id)arg1;
- (void)pictureInPictureControllerWillStopPictureInPicture:(id)arg1;
- (void)pictureInPictureControllerDidStartPictureInPicture:(id)arg1;
- (void)playNextOrStop;
- (_Bool)pauseOrPlayVideo;
- (void)recoverADPlayOrSkip;
- (void)mediaPlayer:(id)arg1 eventOccur:(int)arg2 userInfo:(id)arg3;
- (void)mediaPlayer:(id)arg1 screenChanged:(_Bool)arg2;
- (void)mediaPlayer:(id)arg1 stateChanged:(int)arg2 withError:(id)arg3;
- (id)mediaPlayer:(id)arg1 willPlayUrl:(id)arg2;
- (void)checkMVPlayerView;
- (void)jumpToGreenDiamondWebVCWithJumpUrl:(id)arg1;
- (void)jumpToGreenDiamondWebVC;
- (void)showGreenDiamondAlert;
- (id)errorPlayerTipString:(int)arg1 errorCode:(int)arg2;
- (id)errorDownLoadTipString:(int)arg1 errorCode:(int)arg2;
- (void)checkBufferingDone;
- (void)playMVWithMVList:(id)arg1 andIndex:(long long)arg2 isLocal:(struct SFlexInteger)arg3;
- (void)playList:(id)arg1 parentViewController:(id)arg2 uin:(unsigned long long)arg3 playSongIndex:(int)arg4 listTitle:(id)arg5 from:(id)arg6 channelItem:(id)arg7 isLocalMV:(struct SFlexInteger)arg8 localMVPath:(id)arg9;
- (_Bool)isFullScreenMode;
- (void)hidePresentedVC;
- (_Bool)isPiPActive;
- (void)recoverPlayerModalVC;
- (void)didEnterBackground;
- (id)setMakeFreeUrl:(id)arg1;
- (void)recoverPlay;
- (_Bool)isMVPlaying;
- (_Bool)isMVPlayerShow;
- (id)mvPlayerVC;
- (void)checkFreeFlowState;
- (void)checkBgNetChangeEvent;
- (void)checkISPNetwork;
- (void)checkNetState;
- (_Bool)isCurrentMVDownload;
- (void)togglePiPMode;
- (void)downloadMV;
- (void)freeFlowCheck;
- (void)recoverStatusBar;
- (_Bool)getNetWorkTipFlag;
- (void)setNetWorkTipFlag:(_Bool)arg1;
- (id)getClarityArray;
- (void)changeClarity:(id)arg1;
- (int)getFormatTypeFromString:(id)arg1;
- (id)getCurrentClarityName;
- (_Bool)isLocalMVFlag;
- (id)getMVtitleAtIndex:(int)arg1;
- (id)getListTitle;
- (void)shareMVAction;
- (void)setMovieScalingMode:(_Bool)arg1;
- (int)getPlayerState;
- (void)stop;
- (void)forcePause;
- (void)pause;
- (void)play;
- (void)setSeekPlayTime:(double)arg1;
- (void)playMV:(id)arg1;
- (void)playSongIndex:(int)arg1;
- (int)getCurrentIndex;
- (double)getDuration;
- (double)getPlayableDuration;
- (double)getCurrentPlaybackTime;
- (void)willResignActive;
- (void)didBecomeActive;
- (void)willPlayVideo;
- (void)resetCustomToolBarFrame;
- (id)addViewCustomToolBar;
- (id)getVideoVid;
- (void)setDefaultClarity;
- (int)getCurrentClarity;
- (void)recoverPlayBack;
- (void)stopPlayBack;
- (void)delayCheck;
- (void)initVideoPlayer;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

