//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface VQMTAPasteboard : NSObject
{
}

+ (id)getCompanyDomain;
+ (id)get:(id)arg1;
+ (void)set:(id)arg1 value:(id)arg2;

@end

