//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QMBaseModel.h"

@class NSString;

@interface WangsuFreeFlowItem : QMBaseModel
{
    _Bool _isFree;
    _Bool _isRoam;
    int _freeFlowServerPort;
    long long _flowCurrent;
    NSString *_freeFlowServerIP;
    NSString *_areas;
    NSString *_authKey;
    NSString *_baseTimeStamp;
    NSString *_phoneNumber;
    NSString *_phoneIP;
    NSString *_token;
    NSString *_cpOrder;
    unsigned long long _elapsedWhenAuth;
}

+ (id)translateJSONDataToNSObject:(id)arg1;
@property(nonatomic) unsigned long long elapsedWhenAuth; // @synthesize elapsedWhenAuth=_elapsedWhenAuth;
@property(retain, nonatomic) NSString *cpOrder; // @synthesize cpOrder=_cpOrder;
@property(retain, nonatomic) NSString *token; // @synthesize token=_token;
@property(retain, nonatomic) NSString *phoneIP; // @synthesize phoneIP=_phoneIP;
@property(retain, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(retain, nonatomic) NSString *baseTimeStamp; // @synthesize baseTimeStamp=_baseTimeStamp;
@property(retain, nonatomic) NSString *authKey; // @synthesize authKey=_authKey;
@property(retain, nonatomic) NSString *areas; // @synthesize areas=_areas;
@property(nonatomic) int freeFlowServerPort; // @synthesize freeFlowServerPort=_freeFlowServerPort;
@property(retain, nonatomic) NSString *freeFlowServerIP; // @synthesize freeFlowServerIP=_freeFlowServerIP;
@property(nonatomic) long long flowCurrent; // @synthesize flowCurrent=_flowCurrent;
@property(nonatomic) _Bool isRoam; // @synthesize isRoam=_isRoam;
@property(nonatomic) _Bool isFree; // @synthesize isFree=_isFree;
- (void).cxx_destruct;
- (_Bool)isUsable;

@end

