//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "IDViewDelegate-Protocol.h"

@class NSString, WarningStateView;

@interface WarningViewController : NSObject <IDViewDelegate>
{
    NSString *_message;
    WarningStateView *_warningView;
}

@property(retain) WarningStateView *warningView; // @synthesize warningView=_warningView;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (void)viewDidBecomeFocused:(id)arg1;
- (id)initWithView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

