//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface wax_dispatch : NSObject
{
}

+ (void)asyncAfterOnMainQueue:(unsigned long long)arg1 block:(id)arg2 name:(id)arg3;
+ (void)asyncAfterOnMainQueue:(unsigned long long)arg1 block:(CDUnknownBlockType)arg2;
+ (void)asyncOnMainQueue:(id)arg1 name:(id)arg2;
+ (void)asyncOnMainQueue:(CDUnknownBlockType)arg1;

@end

