//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray;
@protocol WaxTestManagerDelegate;

@interface WaxTestManager : NSObject
{
    id <WaxTestManagerDelegate> _delegate;
    NSMutableArray *_loadedScriptFiles;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *loadedScriptFiles; // @synthesize loadedScriptFiles=_loadedScriptFiles;
@property(nonatomic) __weak id <WaxTestManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)startAutoTest;
- (void)runLuaScriptFile:(id)arg1;
- (id)init;

@end

