//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBBaseResponse.h"

@class WBAuthorizeResponse;

@interface WBShareMessageToContactResponse : WBBaseResponse
{
    WBAuthorizeResponse *_authResponse;
}

@property(retain, nonatomic) WBAuthorizeResponse *authResponse; // @synthesize authResponse=_authResponse;
- (void).cxx_destruct;
- (void)loadFromDictionary:(id)arg1;
- (void)storeToDictionary:(id)arg1;
- (_Bool)canBeReceived;
- (_Bool)canBeSent;

@end

