//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSData, NSString;

@interface WXFileObject : NSObject
{
    NSString *fileExtension;
    NSData *fileData;
}

+ (id)object;
@property(retain, nonatomic) NSData *fileData; // @synthesize fileData;
@property(retain, nonatomic) NSString *fileExtension; // @synthesize fileExtension;
- (void)dealloc;
- (id)init;

@end

