//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSString;

@interface WXFriendItem : ProtocolBaseJason
{
    _Bool _isFollow;
    unsigned int _sex;
    NSString *_nickname;
    unsigned long long _uin;
    NSString *_openId;
    NSString *_country;
    NSString *_province;
    NSString *_city;
    NSString *_headPic;
}

+ (id)tranlateToWXFriendItemFromJsonData:(id)arg1;
@property(nonatomic) _Bool isFollow; // @synthesize isFollow=_isFollow;
@property(retain, nonatomic) NSString *headPic; // @synthesize headPic=_headPic;
@property(nonatomic) unsigned int sex; // @synthesize sex=_sex;
@property(retain, nonatomic) NSString *city; // @synthesize city=_city;
@property(retain, nonatomic) NSString *province; // @synthesize province=_province;
@property(retain, nonatomic) NSString *country; // @synthesize country=_country;
@property(retain, nonatomic) NSString *openId; // @synthesize openId=_openId;
@property(nonatomic) unsigned long long uin; // @synthesize uin=_uin;
@property(retain, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
- (void).cxx_destruct;
- (id)description;

@end

