//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSArray;

@interface WXH5DownloadRecommendProtocol : ProtocolBaseJason
{
    NSArray *_wxH5DownloadedSongList;
}

@property(retain, nonatomic) NSArray *wxH5DownloadedSongList; // @synthesize wxH5DownloadedSongList=_wxH5DownloadedSongList;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (_Bool)needsUnzip:(id)arg1;
- (_Bool)isDataBeginWithFiveZero;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getUrl;
- (int)cid;

@end

