//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  4 2017 14:06:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "QMCreatorViewDelegate-Protocol.h"

@class NSString, QMCreatorView, ShareView, UILabel, ZanMessageObject;
@protocol ZanMessageCellDelegate;

@interface ZanMessageCell : UITableViewCell <QMCreatorViewDelegate>
{
    struct CGRect _originShareViewFrame;
    id <ZanMessageCellDelegate> _delegate;
    ZanMessageObject *_zanMsgObj;
    ShareView *_shareView;
    UILabel *_dateLabel;
    QMCreatorView *_zanPersonView;
}

+ (double)cellHeightForZanMessage:(id)arg1;
@property(retain, nonatomic) QMCreatorView *zanPersonView; // @synthesize zanPersonView=_zanPersonView;
@property(retain, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain, nonatomic) ShareView *shareView; // @synthesize shareView=_shareView;
@property(readonly, nonatomic) ZanMessageObject *zanMsgObj; // @synthesize zanMsgObj=_zanMsgObj;
@property(nonatomic) __weak id <ZanMessageCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didClick;
- (void)creatorViewDidClick:(id)arg1;
- (id)initWithDelegate:(id)arg1;
- (id)reuseIdentifier;
- (void)setZanObject:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

